-- ============================================================================
-- creche_demo — partie 2/3 : les séances, rattachées à leur séquence
--
-- Le titre d'une séance EST son THÈME (zone libre saisie par le professionnel).
-- `mode` : standard | remediation | approfondissement | autonomie
-- `style` : classique | ludique | structure | concis
-- `esquisse` : JSON {a,b,c} — les trois temps que l'adulte pose avant de générer.
-- `position` : l'ordre dans la séquence.
--
-- EN CRÈCHE, UNE SÉANCE N'EST PAS UN COURS. C'est une proposition : le matériel
-- est installé, l'adulte se met à hauteur, et l'enfant vient ou ne vient pas.
-- « Remédiation » ne veut pas dire rattrapage mais reprise autrement, souvent
-- parce que la proposition était trop difficile ou trop bruyante. « Autonomie »
-- désigne le jeu libre : l'adulte prépare, puis se retire et observe.
-- Les durées sont courtes — vingt minutes est déjà long à cet âge.
-- ============================================================================

INSERT INTO seances (user_id, sequence_id, position, titre, description, matiere, niveau,
                     duree_minutes, mode, competences, materiel, esquisse, contraintes, style,
                     resultat, created_at, updated_at) VALUES

-- ── Séquence 1 — Motricité et coordination ──────────────────────────────────
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 1, 1,
 'Attraper, lâcher, viser : la main qui apprend à choisir',
 'Trois plateaux installés au sol, chacun demandant un geste différent de la main. Les enfants passent de l''un à l''autre librement ; l''adulte nomme le geste sans le corriger.',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 25, 'standard',
 '["Saisir un objet en ajustant l''écartement des doigts","Lâcher volontairement, au bon endroit","Coordonner le regard et la main sur une cible"]',
 'Un puzzle à encastrer sans boutons, un trieur de formes, des perles à enfiler avec cordelette rigide, trois tapis, un panier vide par plateau.',
 '{"a":"Installation à vue des enfants : ils voient le matériel sortir, c''est déjà le début (5 min).","b":"Exploration libre des trois plateaux, l''adulte assis au sol nomme ce qui se passe (15 min).","c":"Rangement fait avec eux, chaque objet retrouve son panier (5 min)."}',
 'Ne jamais remettre une pièce à sa place à la place de l''enfant. Les perles restent sous surveillance directe : cordelette rigide obligatoire.',
 'classique',
 E'# Attraper, lâcher, viser\n\n## Intention\nÀ cet âge, la main n''apprend pas à « réussir » un encastrement : elle apprend à ajuster. L''écart entre ce que l''œil vise et ce que la main fait se réduit à force d''essais ratés. Cette séance multiplie donc les essais, et ne valorise aucun résultat.\n\n## Installation\nTrois plateaux espacés d''un mètre, au sol, sur trois tapis distincts. Chacun ne propose qu''un seul geste :\n\n| Plateau | Objet | Geste travaillé |\n|---|---|---|\n| 1 | Puzzle à encastrer | Poser dans un creux qui a la même forme |\n| 2 | Trieur de formes | Faire passer par un trou, sans le voir en entier |\n| 3 | Perles et cordelette | Enfiler : deux mains qui font deux choses différentes |\n\nLe troisième est nettement plus difficile. Il est là pour les plus grands, et pour que les plus petits le regardent faire.\n\n## Déroulé\n\n### 1. Sortir le matériel devant eux (5 min)\nOn n''installe pas avant leur arrivée. Voir le panier s''ouvrir fait partie de la proposition : l''attente prépare le geste.\n\n### 2. Exploration libre (15 min)\nL''adulte s''assoit au sol, à hauteur, et ne fait rien d''autre que nommer : « tu tournes la pièce », « elle ne rentre pas de ce côté », « tu as lâché dans le panier ». On décrit, on ne félicite pas — la satisfaction vient de l''objet qui tombe au bon endroit, pas du regard de l''adulte.\n\nUn enfant qui vide le panier sans rien encastrer travaille lui aussi : vider et remplir est le geste premier.\n\n### 3. Ranger ensemble (5 min)\nChaque objet retrouve son panier, avec eux. Le rangement est la dernière manipulation de la séance, pas une corvée qui la termine.\n\n## Ce qu''on observe\n- L''enfant regarde-t-il l''objet avant de tendre la main, ou tend-il la main d''abord ?\n- Tourne-t-il la pièce quand elle ne rentre pas, ou force-t-il ?\n- Lâche-t-il quand il veut, ou l''objet lui échappe-t-il encore ?\n\n## Sécurité\nPerles : uniquement avec cordelette rigide et à portée de main de l''adulte. Aucune pièce de moins de 4 cm laissée sans surveillance directe.\n\n## Prolongement\nLaisser un seul des trois plateaux en accès libre l''après-midi. Ce que l''enfant refait seul, sans adulte, dit ce qu''il a vraiment acquis.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 1, 2,
 'Le corps qui se déplace : ramper, grimper, redescendre',
 'Un parcours bas en trois éléments, franchissable dans les deux sens. Ceux qui ne marchent pas encore l''empruntent à quatre pattes ; le parcours n''a pas de sens obligatoire.',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 30, 'standard',
 '["Se déplacer en variant les appuis","Franchir un obstacle bas sans aide","Redescendre — le geste le moins spontané","S''arrêter, se retourner, repartir"]',
 'Deux modules de mousse (une marche, un plan incliné), un tunnel en tissu, quatre balles en éponge, tapis de sol sur toute la zone.',
 '{"a":"Le parcours est montré une fois, en le faisant soi-même, sans commentaire (5 min).","b":"Passages libres, autant de fois que voulu, dans le sens que l''enfant choisit (20 min).","c":"Les balles en éponge sont lâchées dans la zone : le parcours devient poursuite (5 min)."}',
 'Ne jamais hisser un enfant sur un module : ce qu''il ne monte pas seul, il ne sait pas le redescendre. Rester à côté du plan incliné, mains disponibles, sans toucher.',
 'structure',
 E'# Ramper, grimper, redescendre\n\n## Intention\nLa descente s''apprend après la montée, et c''est là que se produisent les chutes. Cette séance propose autant de descentes que de montées, et l''adulte n''en escamote aucune.\n\n## Le parcours\n\n**1. Le tunnel** — se baisser, avancer à quatre pattes, ne plus voir l''adulte pendant deux secondes. Pour certains, c''est l''élément le plus difficile de la séance.\n\n**2. La marche de mousse** — monter dessus, se redresser, redescendre. On laisse l''enfant chercher : à reculons, sur les fesses, en se tenant. Chaque solution est bonne, aucune n''est proposée.\n\n**3. Le plan incliné** — monter, puis se retourner pour redescendre. C''est le seul élément où l''adulte se tient à côté, mains disponibles, sans jamais poser les mains sur l''enfant tant qu''il ne tombe pas.\n\n## Déroulé\n\n### 1. Montrer en faisant (5 min)\nUne fois, en silence, l''adulte fait le parcours. Pas d''explication : les mots ne servent à rien ici, l''imitation fait tout.\n\n### 2. Passages libres (20 min)\nAucun ordre imposé, aucun tour de rôle. Un enfant qui refait dix fois le tunnel et ignore le reste travaille exactement ce qu''il a besoin de travailler.\n\n### 3. Les balles (5 min)\nQuatre balles en éponge lâchées dans la zone. Le parcours devient prétexte : on court après, on se baisse, on lance. La dépense monte d''un cran, puis on arrête net — c''est ce qui permet d''enchaîner sur un temps calme.\n\n## Ce qu''on observe\n- L''enfant s''engage-t-il seul, ou attend-il un regard avant chaque élément ?\n- Comment redescend-il ? À reculons est un vrai progrès, pas une hésitation.\n- Refait-il le même élément en boucle ? C''est le signe d''une acquisition en cours.\n\n## Sécurité\nTapis sous chaque module, sans interstice. Un adulte reste fixe près du plan incliné pendant toute la séance ; le second circule.\n\n## Après\nEnchaîner immédiatement sur un temps de retour au calme. Une salle de motricité qu''on quitte en courant se paie sur le repas qui suit.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 1, 3,
 'Après l''élan, le calme : redescendre en douceur',
 'Le temps qui suit la motricité. On ne demande pas le silence : on propose des gestes lents et une ronde chantée qui ralentit d''elle-même.',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 15, 'remediation',
 '["Percevoir son corps au repos","Suivre un rythme qui ralentit","Accepter le contact au sol, allongé"]',
 'Tapis, lumière baissée, un foulard léger par enfant, une comptine connue du groupe.',
 '{"a":"Ronde chantée debout, en tournant, sur un rythme d''abord vif (5 min).","b":"La même comptine, deux fois plus lente, assis en cercle (5 min).","c":"Allongés, le foulard passe lentement sur les bras et les jambes (5 min)."}',
 'Aucun enfant n''est obligé de s''allonger. Celui qui reste assis participe autant.',
 'concis',
 E'# Après l''élan, le calme\n\n## Pourquoi cette séance existe\nElle a été ajoutée après constat : le groupe sortait de motricité surexcité, et le repas devenait ingérable. Le problème n''était pas la motricité, c''était l''absence de descente.\n\n## Déroulé\n\n**1. Ronde vive (5 min)** — debout, en cercle, la comptine que tout le monde connaît, tempo normal. On accepte les cris : c''est le sommet, il faut y passer.\n\n**2. La même, ralentie (5 min)** — assis, la même comptine, deux fois plus lente. Ne rien annoncer. Le groupe suit sans qu''on le demande : c''est le tempo qui commande, pas la consigne.\n\n**3. Le foulard (5 min)** — allongés ou assis, l''adulte passe un foulard léger sur les bras, les jambes, jamais le visage. On nomme : « ton bras », « ta main », « ton pied ».\n\n## Ce qu''on observe\n- Le groupe ralentit-il avec le tempo, ou faut-il encore le dire avec des mots ?\n- Qui a besoin du contact du foulard, qui le refuse ?\n- Combien de temps l''allongement tient-il ? Trente secondes est déjà un résultat.\n\n## Ce qui ne marche pas\nDemander le silence. Éteindre brutalement la lumière. Passer directement de la course au tapis : sans le palier intermédiaire, la descente ne se fait pas.',
 now(), now()),

-- ── Séquence 2 — Réflexion, raisonnement et repérage ─────────────────────────
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 2, 1,
 'Un objet, une place : trier et ranger pour de vrai',
 'Le tri n''est pas un exercice : c''est le rangement de la salle, fait avec eux, avec des bacs photographiés.',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 20, 'standard',
 '["Trier selon un critère unique","Associer un objet à l''image qui le représente","Ranger un ensemble jusqu''au bout"]',
 'Boîtes gigognes, cubes de construction de couleur, trois bacs avec la photo de leur contenu collée devant.',
 '{"a":"Tout est volontairement mélangé dans un grand bac au centre (2 min).","b":"Chacun prend un objet et cherche le bac qui va avec ; l''adulte nomme la couleur ou la forme (13 min).","c":"On vérifie ensemble bac par bac, sans corriger ce qui reste mal placé (5 min)."}',
 'Ne pas ajouter de second critère (couleur ET taille) : à cet âge, un critère à la fois.',
 'ludique',
 E'# Un objet, une place\n\n## Intention\nTrier suppose de tenir un critère en tête pendant tout le geste. C''est un travail mental considérable à deux ans. On n''en demande qu''un seul à la fois — la couleur, ou la taille, jamais les deux.\n\n## Installation\nTrois bacs, chacun portant devant lui la photo de ce qu''il contient. La photo n''est pas décorative : c''est elle qui rend le rangement possible sans l''adulte, tous les jours de l''année.\n\n## Déroulé\n\n### 1. Le grand mélange (2 min)\nOn verse tout au centre du tapis. Le désordre est volontaire et il fait rire — c''est ce qui donne envie de s''y mettre.\n\n### 2. Chacun cherche (13 min)\nUn objet à la fois. L''adulte nomme ce que l''enfant fait : « un rouge avec les rouges », « celui-là est plus gros ». Il ne dit jamais « non, pas là ».\n\nUn enfant qui empile au lieu de trier fait autre chose de très bien — on le laisse, on nomme l''empilement.\n\n### 3. On regarde ensemble (5 min)\nBac par bac. On constate à voix haute ce qu''on voit, y compris les intrus : « il y a un bleu chez les rouges ». On ne le déplace pas. Le voir suffit ; c''est la prochaine fois qu''il bougera.\n\n## Ce qu''on observe\n- L''enfant tient-il son critère jusqu''au bout, ou change-t-il en cours de route ?\n- Utilise-t-il la photo du bac, ou cherche-t-il l''adulte du regard ?\n- Va-t-il chercher un objet oublié sous le meuble ? C''est le signe qu''il a une représentation complète de l''ensemble.\n\n## Prolongement\nLe même dispositif devient le rangement quotidien de la salle. C''est là qu''il prend son sens : trier pour de vrai, pas pour l''exercice.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 2, 2,
 'Ce qui a disparu revient : cacher, chercher, retrouver',
 'Une série de cachettes de plus en plus difficiles, du foulard posé sur l''objet jusqu''à la boîte fermée.',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 20, 'standard',
 '["Chercher un objet qu''on ne voit plus","Se souvenir de l''endroit où il a été mis","Anticiper : chercher là où il pourrait être"]',
 'Deux foulards, une boîte à couvercle, trois objets familiers du groupe, un jeu de cartes de mémoire à grandes images.',
 '{"a":"Sous le foulard, devant eux : l''objet est caché à vue (5 min).","b":"Dans la boîte fermée, puis derrière le dos : la cachette n''est plus visible (10 min).","c":"Les cartes de mémoire, deux paires seulement, retournées lentement (5 min)."}',
 'Deux paires suffisent pour commencer. Six paires est un jeu d''adulte déguisé.',
 'structure',
 E'# Ce qui a disparu revient\n\n## Intention\nSavoir qu''un objet continue d''exister quand on ne le voit plus n''a rien d''évident : c''est une acquisition, et elle se construit par étapes. Cette séance les propose dans l''ordre, du plus facile au plus difficile.\n\n## Les trois étapes, dans l''ordre\n\n**1. Caché à vue.** L''objet est posé devant l''enfant, on met un foulard dessus pendant qu''il regarde. Il soulève. Presque tous réussissent — c''est le point de départ, pas l''objectif.\n\n**2. Caché hors de vue.** L''objet entre dans une boîte, la boîte se ferme. Puis l''objet passe derrière le dos de l''adulte. Ici, certains abandonnent immédiatement : ils ne cherchent pas ce qu''ils n''ont pas vu partir.\n\n**3. Deux cachettes possibles.** L''objet peut être sous l''un des deux foulards. L''enfant doit se souvenir, puis, s''il se trompe, chercher sous l''autre. C''est la vraie marche de la séance.\n\n## Le jeu de mémoire\nDeux paires, pas plus. Cartes à grandes images, retournées lentement, en nommant chaque image. Le but n''est pas de gagner : c''est de dire « je l''ai déjà vue, elle est là ».\n\n## Ce qu''on observe\n- L''enfant cherche-t-il, ou se détourne-t-il dès que l''objet disparaît ?\n- Après une erreur, cherche-t-il ailleurs, ou refait-il exactement le même geste ?\n- Cache-t-il lui-même, pour l''adulte ? C''est l''étape suivante, et elle vient toute seule.\n\n## Ce qui gâche la séance\nAller trop vite. Cacher pendant que l''enfant regarde ailleurs. Rire quand il se trompe : il arrête de chercher.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 2, 3,
 'Combien il y en a : les premières quantités',
 'On ne compte pas, on met en correspondance. Un domino contre un domino, un point contre un point.',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 20, 'approfondissement',
 '["Associer deux quantités identiques sans les compter","Reproduire une disposition simple","Dire un mot-nombre en pointant, même sans exactitude"]',
 'Un kit de dominos à gros points, des cubes-puzzle, un tapis uni pour que les points ressortent.',
 '{"a":"L''adulte pose un domino, l''enfant en cherche un pareil (7 min).","b":"On aligne : chaque domino trouve son jumeau, côte à côte (8 min).","c":"Cubes-puzzle : reconstituer une image sur quatre faces (5 min)."}',
 'Ne pas corriger un comptage faux. « Un, deux, cinq » en pointant trois objets est déjà un progrès énorme : il y a une correspondance.',
 'classique',
 E'# Combien il y en a\n\n## Intention\nCompter juste viendra bien plus tard. Ce qui se construit ici, c''est autre chose : comprendre que deux collections peuvent « aller ensemble » parce qu''elles ont autant d''éléments. C''est de la mise en correspondance, pas de l''arithmétique.\n\n## Déroulé\n\n### 1. Trouver le même (7 min)\nL''adulte pose un domino bien visible. L''enfant cherche celui qui a la même chose dessus. On ne dit pas « trois » : on dit « pareil ».\n\n### 2. Aligner les paires (8 min)\nChaque domino trouvé se pose contre son jumeau. L''alignement rend le résultat visible : la ligne qui s''allonge est plus parlante que n''importe quelle félicitation.\n\n### 3. Les cubes-puzzle (5 min)\nQuatre cubes, une image à reconstituer. Le raisonnement change de nature : il faut tourner mentalement avant de tourner avec les mains.\n\n## Ce qu''on observe\n- L''enfant compare-t-il les deux dominos du regard, ou prend-il au hasard ?\n- Pointe-t-il chaque point en disant un mot ? Même faux, c''est le début du dénombrement.\n- Tourne-t-il un cube en le regardant, ou l''essaie-t-il face après face ?\n\n## Pourquoi ne pas corriger\nUn enfant qui dit « un, deux, cinq » en pointant trois objets a compris l''essentiel : un mot par objet, une seule fois chacun. La suite exacte des mots-nombres s''apprendra par la comptine, pas par la correction.\n\n## Prolongement\nLes mêmes dominos, laissés en libre accès. Certains les rangeront en ligne toute la semaine, sans qu''on demande rien.',
 now(), now()),

-- ── Séquence 3 — Langage ─────────────────────────────────────────────────────
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 3, 1,
 'L''imagier de tous les jours : nommer ce qu''on voit',
 'Un imagier ouvert sur les genoux, deux ou trois enfants autour. Puis le même jeu, sans livre, sur ce que la pièce contient.',
 'Langage', 'Moyens-Grands (1-3 ans)', 15, 'standard',
 '["Pointer une image nommée par l''adulte","Nommer à son tour, même approximativement","Faire le lien entre l''image et l''objet réel"]',
 'Deux imagiers cartonnés à images simples, les objets réels correspondants (une cuillère, une chaussure, une balle) posés à côté.',
 '{"a":"L''adulte ouvre l''imagier et nomme, sans questionner (5 min).","b":"« Où est la balle ? » — l''enfant pointe, puis nomme s''il veut (5 min).","c":"On retrouve l''objet réel dans la pièce et on le pose sur l''image (5 min)."}',
 'Ne jamais faire répéter. Un enfant qui pointe sans parler a compris — c''est la compréhension qui précède toujours la parole.',
 'classique',
 E'# L''imagier de tous les jours\n\n## Intention\nLe vocabulaire ne s''enseigne pas, il se dépose. L''adulte nomme beaucoup, en situation, et l''enfant prélève ce dont il a besoin. Cette séance organise un moment où l''on nomme dense, à deux ou trois, jamais en grand groupe.\n\n## Déroulé\n\n### 1. Nommer sans demander (5 min)\nL''imagier est ouvert sur les genoux, les enfants collés contre. L''adulte nomme ce qu''il montre, une image après l''autre. Aucune question. On tourne la page quand ils tournent la tête.\n\n### 2. Pointer (5 min)\n« Où est la balle ? » L''enfant pointe. C''est tout ce qui est demandé. Celui qui nomme spontanément est écouté et repris — sans correction : s''il dit « baba », on répond « oui, la balle », et on continue.\n\n### 3. De l''image à l''objet (5 min)\nOn va chercher l''objet réel dans la pièce, on le pose sur son image. Ce trajet-là est le cœur de la séance : il installe que l''image représente quelque chose qui existe ailleurs.\n\n## Ce qu''on observe\n- L''enfant pointe-t-il ce qui est nommé, ou pointe-t-il au hasard ?\n- Nomme-t-il de lui-même, hors sollicitation ?\n- Reconnaît-il l''objet réel à partir de l''image, et non l''inverse ?\n\n## Les langues de la maison\nTrois enfants du groupe entendent une autre langue chez eux. On nomme en français, et on accueille le mot de la maison quand il vient — sans le traduire aussitôt. Les deux langues se construisent ensemble, elles ne se gênent pas.\n\n## Ce qui casse le moment\nFaire répéter. Interroger en série. Passer à cinq enfants : au-delà de trois, ce n''est plus un imagier, c''est une leçon.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 3, 2,
 'Le tête-à-tête : une petite parlotte',
 'Un enfant, un adulte, cinq minutes, rien d''autre. Le temps de langage le plus efficace de la journée, et le plus difficile à tenir.',
 'Langage', 'Moyens-Grands (1-3 ans)', 10, 'autonomie',
 '["Prendre son tour dans un échange à deux","Répondre à une sollicitation par un son, un mot, un geste","Soutenir un regard pendant l''échange"]',
 'Rien. Un coin tranquille, un adulte assis, et un enfant. Éventuellement l''objet que l''enfant tient déjà.',
 '{"a":"L''adulte s''assoit près d''un enfant occupé et se tait (1 min).","b":"Il nomme ce que l''enfant fait, puis attend — vraiment (5 min).","c":"L''échange s''arrête quand l''enfant s''en va : c''est lui qui décide (4 min)."}',
 'Ne pas déplacer l''enfant, ne pas lui retirer son objet, ne pas poser plus d''une question par minute. Le silence après une question fait partie de la question.',
 'concis',
 E'# Une petite parlotte\n\n## Intention\nEn collectivité, un enfant peut passer une journée entière sans qu''on lui parle à lui seul. Ce temps-là répare exactement cela : cinq minutes, un seul enfant, aucun objectif.\n\n## Déroulé\n\n**1. S''asseoir et se taire (1 min)**\nL''adulte rejoint un enfant déjà occupé. Il ne propose rien, ne demande rien. Il se rend disponible, et cela se voit.\n\n**2. Nommer, puis attendre (5 min)**\n« Tu as mis le cube dedans. » Puis silence. Un enfant de dix-huit mois met parfois huit secondes à répondre — huit secondes pendant lesquelles un adulte pressé aura déjà parlé trois fois. L''attente est la technique principale de cette séance.\n\n**3. Laisser partir (4 min)**\nQuand l''enfant s''en va, c''est fini. On ne rappelle pas, on ne prolonge pas. C''est ce qui fait qu''il reviendra.\n\n## Ce qu''on observe\n- L''enfant tourne-t-il la tête vers l''adulte quand celui-ci parle ?\n- Y a-t-il alternance : il fait, l''adulte dit, il refait ?\n- Produit-il un son en réponse — même un seul ?\n\n## Pourquoi « autonomie »\nLe mode est celui du jeu libre : l''adulte ne dirige rien. Il accompagne ce que l''enfant a choisi de faire. La séance n''a pas de contenu propre — son contenu, c''est l''enfant.\n\n## La difficulté réelle\nTenir cinq minutes sans être appelé ailleurs. Cela suppose que la collègue prend le groupe et le sait. Sans cet accord d''équipe, la petite parlotte n''a jamais lieu.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 3, 3,
 'L''histoire qu''on redemande : raconter, rejouer, refaire',
 'Une histoire très courte, racontée trois fois de la même façon, puis rejouée avec trois objets. Puis le livre qu''on fabrique avec leurs photos.',
 'Langage', 'Moyens-Grands (1-3 ans)', 20, 'approfondissement',
 '["Écouter une histoire courte jusqu''au bout","Anticiper la suite d''un récit connu","Reconnaître sa propre photo dans un livre"]',
 'Un album cartonné très court, trois objets figurant les personnages, des photos des enfants imprimées, du carton, de la colle.',
 '{"a":"L''histoire, racontée exactement comme la fois d''avant (5 min).","b":"On la rejoue avec les trois objets, les enfants tiennent un objet chacun (8 min).","c":"On colle deux photos dans le livre du groupe et on le relit (7 min)."}',
 'Raconter à l''identique. Changer les mots d''une histoire connue déstabilise à cet âge — la répétition exacte est ce qui permet l''anticipation.',
 'ludique',
 E'# L''histoire qu''on redemande\n\n## Intention\nUn enfant qui réclame la même histoire pour la neuvième fois ne s''ennuie pas : il vérifie. Savoir ce qui va arriver, et que cela arrive vraiment, est une source de sécurité — et c''est aussi ce qui permet d''anticiper, donc de parler avant l''adulte.\n\n## Déroulé\n\n### 1. À l''identique (5 min)\nLes mêmes mots, les mêmes intonations, les mêmes pauses. Sur la page attendue, l''adulte s''arrête une seconde de trop : quelqu''un dira le mot à sa place. C''est le but.\n\n### 2. Rejouer avec trois objets (8 min)\nTrois objets pour trois personnages. Chaque enfant en tient un et le fait avancer quand c''est son tour. L''histoire passe du livre aux mains : c''est un changement de registre considérable, et certains n''y entrent pas tout de suite.\n\n### 3. Le livre du groupe (7 min)\nOn colle deux photos d''enfants du groupe dans un album fabriqué, avec une phrase dictée par eux. Puis on le relit aussitôt. Se reconnaître dans un livre change le statut du livre.\n\n## Ce qu''on observe\n- L''enfant tourne-t-il les pages avant l''adulte ? Il connaît la suite.\n- Dit-il le mot manquant sur la pause ?\n- Se reconnaît-il sur la photo, et nomme-t-il les autres ?\n\n## Prolongement\nLe livre du groupe reste en accès libre. Il devient, en quelques semaines, le plus consulté de l''étagère — bien avant les albums du commerce.',
 now(), now()),

-- ── Séquence 4 — Créativité, imagination et expression ───────────────────────
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 4, 1,
 'La première trace : le geste avant le dessin',
 'Une grande feuille au sol, des gros crayons, et rien à représenter. On regarde ce que la main laisse derrière elle.',
 'Créativité, imagination et expression', 'Moyens-Grands (1-3 ans)', 20, 'standard',
 '["Laisser une trace volontaire","Regarder l''effet de son propre geste","Occuper un espace grand avec tout le bras"]',
 'Papier kraft en grand format fixé au sol, gros crayons de cire, blouses accessibles aux enfants, une éponge humide à portée.',
 '{"a":"La feuille est déroulée devant eux, on fixe les coins ensemble (3 min).","b":"Tracé libre, debout ou à genoux, sans consigne de contenu (12 min).","c":"On regarde la feuille entière, on nomme ce qu''on voit sans interpréter (5 min)."}',
 'Ne jamais demander « qu''est-ce que c''est ? ». À cet âge, ce n''est rien — c''est un geste, pas une image. On écrit le prénom à côté de la trace, jamais dessus.',
 'classique',
 E'# La première trace\n\n## Intention\nAvant de représenter, l''enfant découvre qu''il laisse une marque et que cette marque reste. Le plaisir est moteur, pas graphique : c''est le bras qui travaille, l''œil suit après.\n\n## Installation\nUne grande feuille de kraft fixée au sol, assez grande pour que trois enfants tiennent autour sans se gêner. Le sol plutôt que la table : à cet âge, le geste part de l''épaule, il a besoin de place.\n\n## Déroulé\n\n### 1. Dérouler ensemble (3 min)\nOn fixe les coins avec eux. Voir la surface apparaître prépare autant que la surface elle-même.\n\n### 2. Tracer (12 min)\nAucune consigne de contenu. Des gros crayons, en nombre suffisant pour éviter les conflits. L''adulte trace lui aussi, dans un coin, sans faire de modèle : pas de soleil, pas de bonhomme.\n\nUn enfant qui frotte le crayon sans regarder travaille le contact ; un autre qui fait un point unique et s''arrête a fait quelque chose de complet.\n\n### 3. Regarder (5 min)\nOn se met tous debout au-dessus de la feuille. L''adulte nomme ce qu''il voit — « là c''est très serré », « ici tu es allé jusqu''au bord » — sans jamais dire à quoi cela ressemble.\n\n## Ce qu''on observe\n- L''enfant regarde-t-il la trace pendant qu''il la fait ?\n- Change-t-il de couleur volontairement ?\n- Va-t-il jusqu''aux bords, ou reste-t-il devant lui ?\n\n## La règle d''équipe\nOn n''écrit jamais sur la production d''un enfant, on écrit à côté. On ne retouche rien, on n''ajoute rien, on ne découpe pas pour « faire joli » avant l''affichage.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 4, 2,
 'La matière dans les mains : pâte, papiers, colle',
 'Deux temps : la pâte à modeler qu''on ne façonne pas encore, et le collage où la colle intéresse plus que le résultat.',
 'Créativité, imagination et expression', 'Moyens-Grands (1-3 ans)', 25, 'standard',
 '["Explorer une matière par le toucher","Transformer volontairement : aplatir, rouler, déchirer","Coller, décoller, recoller"]',
 'Pâte à modeler souple, éléments naturels (coquillages, brindilles), papiers de textures variées, colle en bâton et colle liquide au pinceau, supports cartonnés.',
 '{"a":"La pâte seule, sans outil ni modèle (10 min).","b":"On y enfonce coquillages et brindilles : la matière garde l''empreinte (5 min).","c":"Table de collage : déchirer, coller, superposer (10 min)."}',
 'Aucun modèle montré. Aucune forme demandée. Un enfant qui malaxe vingt minutes sans rien produire a fait la séance en entier.',
 'ludique',
 E'# La matière dans les mains\n\n## Intention\nAvant de fabriquer quelque chose, il faut savoir ce que la matière fait quand on la presse. Cette séance ne produit rien et c''est voulu : elle donne le temps de l''exploration, qu''on saute presque toujours.\n\n## Déroulé\n\n### 1. La pâte seule (10 min)\nUne boule par enfant, souple, tiède si possible. Ni emporte-pièce, ni rouleau, ni modèle. On observe ce qui vient : taper, pincer, arracher un morceau, le recoller.\n\n### 2. L''empreinte (5 min)\nOn pose des coquillages, des brindilles, un bouchon. On appuie, on retire : la trace reste. C''est souvent le moment où le groupe devient silencieux — la surprise est réelle.\n\n### 3. Le collage (10 min)\nDes papiers de textures différentes : lisse, ondulé, crépon. Le déchirage compte autant que le collage. La colle liquide au pinceau est proposée à côté du bâton : elle demande un geste tout autre, plus lent.\n\n## Ce qu''on observe\n- L''enfant transforme-t-il volontairement, ou subit-il la matière ?\n- Recommence-t-il un geste qui a produit un effet ? C''est le début de l''intention.\n- Supporte-t-il d''avoir les mains sales ? Certains ont besoin de plusieurs séances pour y venir, et d''une éponge à portée.\n\n## Ce qui n''a pas sa place ici\nUn modèle affiché. Une consigne de forme. Un adulte qui fabrique un escargot « pour montrer » — après cela, plus personne n''explore, tout le monde essaie de refaire l''escargot.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 4, 3,
 'Prêter sa voix : marionnettes, sons et petits théâtres',
 'La marionnette parle à l''enfant avant que l''enfant parle à la marionnette. Puis on fabrique des sons avec le corps, sans instrument.',
 'Créativité, imagination et expression', 'Moyens-Grands (1-3 ans)', 20, 'standard',
 '["Attribuer une intention à un objet","Répondre à un personnage joué","Produire un son volontaire, avec son corps puis avec un objet"]',
 'Deux marionnettes à main, trois marionnettes à doigts, aucun instrument — les mains, les pieds, la bouche et une boîte en carton.',
 '{"a":"La marionnette arrive et parle à chacun, en le nommant (7 min).","b":"Les enfants prennent les marionnettes à doigts, l''adulte se tait (5 min).","c":"On fait de la musique sans instrument : frapper, souffler, taper le carton (8 min)."}',
 'Ne pas forcer un enfant à répondre à la marionnette. Certains en ont peur : elle reste alors à distance, et parle à quelqu''un d''autre.',
 'ludique',
 E'# Prêter sa voix\n\n## Intention\nFaire semblant est une acquisition majeure du deuxième anniversaire : donner à un objet une intention qu''il n''a pas. La marionnette est l''entrée la plus simple, parce que c''est l''adulte qui commence.\n\n## Déroulé\n\n### 1. La marionnette arrive (7 min)\nElle salue chaque enfant par son prénom, lui pose une question, attend. Elle ne touche personne sans prévenir. Elle se trompe, elle bafouille — un personnage un peu maladroit rassure plus qu''un personnage parfait.\n\n### 2. Ils la prennent (5 min)\nMarionnettes à doigts distribuées. L''adulte se tait complètement. Ce silence est la partie difficile : à la première hésitation, on a envie de relancer, et cela referme le jeu.\n\n### 3. Faire de la musique sans instrument (8 min)\nTaper des mains, des pieds, sur une boîte en carton, souffler. On cherche un son fort, puis un son doux. On répète un rythme court, deux frappes, et on voit qui le reprend.\n\n## Ce qu''on observe\n- L''enfant parle-t-il à la marionnette comme à quelqu''un ?\n- Fait-il parler la sienne, ou la manipule-t-il comme un objet ? Les deux sont normaux à cet âge.\n- Reprend-il un rythme entendu ? Deux frappes suffisent à le dire.\n\n## Attention\nUne marionnette qui gronde ou qui fait la leçon détruit le dispositif. Elle joue, elle s''étonne, elle se trompe. Elle n''éduque pas.',
 now(), now()),

-- ── Séquence 5 — Aptitudes sociales, confiance et sécurité affective ─────────
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 5, 1,
 'Bonjour : le rituel qui ouvre la journée',
 'Toujours le même ordre, toujours les mêmes mots. Le rituel du matin nomme les présents et annonce ce qui va se passer.',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 15, 'standard',
 '["Se reconnaître nommé dans un groupe","Repérer qui est là et qui manque","Anticiper les temps de la journée"]',
 'Un tapis de regroupement, les photos des enfants du groupe, une comptine d''appel toujours identique.',
 '{"a":"La comptine d''appel, dans le même ordre que d''habitude (5 min).","b":"Les photos : qui est là, qui n''est pas là aujourd''hui (5 min).","c":"On annonce ce qui va se passer, dans l''ordre, avec les mêmes mots (5 min)."}',
 'Ne pas modifier l''ordre. Ne pas sauter l''enfant absent : le nommer et dire qu''il est absent fait partie du travail.',
 'structure',
 E'# Bonjour\n\n## Intention\nUn tout-petit ne sait pas ce qui va lui arriver dans la journée. Le rituel d''accueil lui donne cette information, tous les jours, sous la même forme. C''est un dispositif de sécurité affective, pas une politesse.\n\n## Déroulé\n\n### 1. La comptine d''appel (5 min)\nToujours la même, toujours dans le même ordre. Chaque enfant est nommé. Celui qui ne répond pas est nommé quand même — l''entendre suffit.\n\n### 2. Qui est là (5 min)\nLes photos sont posées une à une. Les absents sont dits : « Naïm n''est pas là aujourd''hui, il reviendra demain. » On ne les escamote pas : un enfant qui manque et dont on ne parle pas apprend qu''on peut disparaître sans que personne ne le remarque.\n\n### 3. Ce qui va se passer (5 min)\nDans l''ordre, avec les mêmes mots que d''habitude : « on va jouer, puis on se lave les mains, puis on mange ». Trois étapes, pas plus.\n\n## Ce qu''on observe\n- L''enfant répond-il à son prénom, d''une façon ou d''une autre ?\n- Regarde-t-il la photo de l''absent ?\n- Anticipe-t-il l''étape suivante avant qu''on la dise ?\n\n## Ce qui abîme le rituel\nLe raccourcir un jour de retard. Changer l''ordre. Le confier chaque jour à quelqu''un d''autre : c''est la répétition qui fait l''effet, et la répétition inclut la voix.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 5, 2,
 'Le doudou, la référente, la séparation',
 'Accompagner le moment où le parent s''en va. Le doudou est disponible, la référente est la même, et la séparation est dite, jamais escamotée.',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 20, 'remediation',
 '["Se séparer en s''appuyant sur un objet familier","Exprimer sa peine et se laisser apaiser","Retrouver son parent sans avoir à tout rejouer"]',
 'Bac à doudous ouvert et accessible, un fauteuil bas près de la porte, les photos de famille plastifiées à hauteur d''enfant.',
 '{"a":"L''arrivée : le parent reste le temps convenu, toujours le même (7 min).","b":"Le départ est annoncé et fait — pas de sortie en cachette (3 min).","c":"On accompagne la peine : contact, doudou, photo de famille, mots (10 min)."}',
 'Un parent ne part jamais sans le dire, même si l''enfant pleure davantage sur le moment. Le doudou ne se retire ni au repas ni au jeu tant que l''enfant en a besoin.',
 'classique',
 E'# Le doudou, la référente, la séparation\n\n## Pourquoi cette séance est en « remédiation »\nElle a été reprise après une période difficile : quatre arrivées en un mois, et des matins qui s''éternisaient. Ce qui a changé, ce n''est pas l''enfant, c''est le cadre posé par l''équipe.\n\n## Les trois appuis\n\n**L''objet.** Le doudou est accessible à tout moment, dans un bac ouvert à hauteur d''enfant. Il n''est confisqué ni au repas, ni au jeu, ni « parce qu''il est grand maintenant ». C''est lui qui fait le lien entre la maison et ici.\n\n**La personne.** La même professionnelle accueille le même enfant, et l''accompagne au change, au repas et à l''endormissement. Ce n''est pas une préférence affective : c''est ce qui rend le lieu prévisible.\n\n**Le dire.** Le parent annonce son départ et part. Une sortie en cachette évite trois minutes de pleurs et coûte trois semaines de vigilance : l''enfant qui a vu son parent disparaître sans prévenir surveille désormais la porte au lieu de jouer.\n\n## Déroulé du matin\n\n### 1. Le temps convenu (7 min)\nLe parent reste la durée dont on a convenu ensemble, toujours la même. Ni deux minutes, ni vingt selon l''humeur.\n\n### 2. Le départ (3 min)\nAnnoncé, fait, sans revenir sur ses pas. La professionnelle prend le relais physiquement : elle porte, ou elle tend la main.\n\n### 3. L''accompagnement (10 min)\nOn ne dit pas « ce n''est rien ». On dit ce qui est : « maman est partie, elle revient après la sieste ». Le doudou est proposé, la photo de famille est à portée. Les pleurs ont le droit de durer.\n\n## Ce qu''on observe\n- L''enfant va-t-il chercher son doudou seul ?\n- Se laisse-t-il consoler par la référente, ou par n''importe qui ?\n- Combien de temps entre le départ et le retour au jeu ? C''est l''indicateur qui compte, pas l''intensité des pleurs.\n\n## Aux retrouvailles\nOn raconte la journée en deux phrases devant l''enfant. Il entend qu''il n''y a pas deux mondes séparés.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 5, 3,
 'Faire une place à l''autre : le groupe qui se fabrique',
 'Une trace collective où chacun laisse la sienne, et un temps de détente à deux. Le groupe se construit par le corps avant les mots.',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 25, 'approfondissement',
 '["Repérer un autre enfant et l''imiter","Attendre son tour dans un temps court","Se laisser toucher, toucher l''autre avec accord"]',
 'Grande feuille ronde, peinture à doigts non toxique, bassine d''eau tiède et serviettes, coussins pour le temps calme.',
 '{"a":"Chacun pose sa main peinte sur la feuille ronde, à son tour (12 min).","b":"On lave les mains ensemble, dans la même bassine (5 min).","c":"Temps de détente à deux : massage des mains, sur accord de chacun (8 min)."}',
 'Personne ne pose sa main de force. Un enfant qui refuse la peinture pose sa main sèche à côté : sa place est marquée quand même.',
 'ludique',
 E'# Faire une place à l''autre\n\n## Intention\nAvant deux ans, les enfants jouent côte à côte plutôt qu''ensemble. On ne force pas la coopération : on fabrique des occasions d''être ensemble sans avoir à partager, et on nomme ce qui se passe.\n\n## Déroulé\n\n### 1. Le cercle de mains (12 min)\nUne grande feuille ronde au centre. Chacun vient à son tour poser sa main peinte, en formant un cercle. L''attente est courte — deux enfants avant soi, pas huit.\n\nCelui qui ne veut pas de peinture pose sa main sèche : on trace le contour au crayon. Sa place est là, comme les autres.\n\n### 2. Se laver ensemble (5 min)\nUne seule bassine d''eau tiède, tout le monde y met les mains en même temps. Ce moment-là n''est pas de l''intendance : c''est le moment le plus collectif de la séance, et souvent le plus joyeux.\n\n### 3. La détente à deux (8 min)\nAssis face à face ou contre l''adulte, on masse doucement les mains — les siennes, puis celles de l''autre s''il est d''accord. On demande avant de toucher, à chaque fois. Ce que l''enfant apprend là vaut plus que le massage.\n\n## Ce qu''on observe\n- L''enfant regarde-t-il ce que fait son voisin ? L''imite-t-il ?\n- Supporte-t-il d''attendre deux tours ?\n- Demande-t-il, ou vérifie-t-il l''accord de l''autre avant de le toucher ?\n\n## Ce qui reste après\nLa feuille est affichée à hauteur d''enfant, avec les prénoms écrits à côté des mains — jamais dessus. Les enfants viennent y poser leur main, des semaines durant, pour vérifier que la leur y est encore.',
 now(), now());
