-- ============================================================================
-- creche_demo — partie 3/3 (b) : les activités des séquences 3 et 4
--                                (langage, puis créativité et expression)
-- ============================================================================

INSERT INTO activites (user_id, seance_id, position, activite_type_id, activite_label, sous_type,
                       nb, avec_correction, objet, matiere, niveau, ton, texte_source, resultat,
                       statut, created_at, updated_at) VALUES

-- ══ Séance 7 — L'imagier de tous les jours ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 7, 1, 76, 'activité de lecture', NULL,
 NULL, false, 'L''imagier à trois, sans question',
 'Langage', 'BMG_0-3', 'classique',
 'Fiche « Imagier » du référentiel d''éveil 0-3 ans : livre d''images cartonné, éveil du langage et de la curiosité, détente physique.',
 E'# L''imagier à trois, sans question\n\n**Âge** : 10 à 30 mois · **Trois enfants au maximum** · **10 minutes** · **Assis au sol, l''album sur les genoux**\n\n## Le principe\nOn nomme, on ne questionne pas. Le vocabulaire ne s''enseigne pas : il se dépose, à force d''être entendu en situation. Un adulte qui interroge en série obtient du silence ; un adulte qui nomme obtient des mots, plus tard, ailleurs.\n\n## L''installation\nTrois enfants, pas davantage. Au-delà, ce n''est plus un imagier, c''est une lecture collective — autre chose, moins efficace pour le langage. Les enfants sont contre l''adulte, l''album à plat sur les genoux, à hauteur de leurs yeux et non des siens.\n\n## Déroulé\n\n**On nomme, page après page.** « Une cuillère. » « Le chien. » Rien d''autre. On tourne la page quand ils tournent la tête, pas quand la page est finie.\n\n**On accepte l''ordre de l''enfant.** Celui qui revient trois fois à la même page a une raison. On y revient avec lui, sans commenter le saut.\n\n**On reprend sans corriger.** Il dit « baba » pour la balle : on répond « oui, la balle », et on continue. Jamais « répète », jamais « on dit... ».\n\n## Les langues de la maison\nQuand le mot vient dans l''autre langue, on l''accueille et on continue en français, sans traduire aussitôt. Les deux langues se construisent ensemble ; elles ne se gênent pas, et corriger la langue de la maison fait taire l''enfant dans les deux.\n\n## Ce qu''on observe\n- Pointe-t-il ce qui est nommé ?\n- Nomme-t-il spontanément, hors sollicitation ?\n- Tourne-t-il les pages lui-même, dans un sens ou dans l''autre ?\n\n## Prolongement direct\nAller chercher dans la pièce l''objet réel qui est sur l''image, et le poser dessus. Ce trajet installe que l''image représente quelque chose qui existe ailleurs — c''est le fondement de toute lecture.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 7, 2, 80, 'échange individuel', NULL,
 NULL, false, 'Je vois quelque chose : nommer ce que la pièce contient',
 'Langage', 'BMG_0-3', 'ludique',
 'Fiche « Je vois quelque chose » du référentiel d''éveil 0-3 ans : exploration sensorielle et langage.',
 E'# Je vois quelque chose\n\n**Âge** : 18 à 36 mois · **Un enfant, parfois deux** · **5 à 8 minutes** · **Aucun matériel**\n\n## Le jeu\nL''adulte regarde un objet de la pièce et le décrit sans le nommer : « je vois quelque chose de rouge, tout rond, et ça roule ». L''enfant cherche du regard, puis va le chercher.\n\n## Ce que cela travaille\nÉcouter jusqu''au bout, tenir deux ou trois indices ensemble, et faire le lien entre des mots et un objet présent. C''est un des rares jeux de langage où l''enfant n''a rien à dire pour réussir — ce qui le rend accessible à ceux qui ne parlent pas encore.\n\n## Déroulé\n\n**Commencer par un seul indice.** « Je vois quelque chose de rouge. » S''il trouve, on ajoute un deuxième indice au tour suivant. Trois indices est un plafond.\n\n**Laisser le temps.** Le silence après l''énoncé fait partie du jeu. Un enfant de deux ans met parfois dix secondes à balayer la pièce.\n\n**Inverser les rôles.** Vers trois ans, l''enfant propose à son tour — souvent en pointant l''objet en même temps qu''il le décrit. On fait semblant de chercher.\n\n## Ce qu''on observe\n- Cherche-t-il du regard avant de se lever ?\n- Tient-il les deux indices, ou n''en retient-il qu''un ?\n- Nomme-t-il l''objet trouvé, ou se contente-t-il de le montrer ?\n\n## Pourquoi en individuel\nÀ deux, ça marche. À six, le plus rapide répond toujours et les autres décrochent en trois tours. Ce jeu-là ne supporte pas le groupe.\n\n## Variante utile\nLes indices sonores : « j''entends quelque chose qui fait du bruit dans le couloir ». L''écoute mobilise autrement que le regard, et cela repose.',
 'termine', now(), now()),

-- ══ Séance 8 — Le tête-à-tête ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 8, 1, 80, 'échange individuel', NULL,
 NULL, false, 'Cinq minutes avec un seul enfant : nommer, puis attendre',
 'Langage', 'BMG_0-3', 'concis',
 'Fiche « Une petite parlotte » du référentiel d''éveil 0-3 ans, et repères sur le langage adressé à l''enfant.',
 E'# Cinq minutes avec un seul enfant\n\n**Âge** : tous · **Un enfant** · **5 minutes** · **Rien**\n\n## Le constat de départ\nEn collectivité, un enfant peut traverser une journée entière sans qu''on s''adresse à lui seul. Toutes les paroles lui arrivent comme membre du groupe : « on va manger », « les mains ». Ce temps-là répare exactement cela.\n\n## La technique, en trois gestes\n\n**S''asseoir près d''un enfant déjà occupé.** Ne rien proposer, ne rien demander. Se rendre disponible — et cela se voit tout de suite.\n\n**Nommer ce qu''il fait.** « Tu as mis le cube dedans. » Une phrase, courte, sur ce qu''il fait maintenant.\n\n**Attendre.** C''est toute la difficulté. Un enfant de dix-huit mois met parfois huit secondes à répondre : huit secondes pendant lesquelles un adulte pressé aura déjà parlé trois fois, et couvert la réponse qui venait.\n\n## La règle du départ\nQuand l''enfant s''en va, c''est fini. On ne rappelle pas, on ne prolonge pas, on ne conclut pas. C''est précisément ce qui fait qu''il reviendra.\n\n## Ce qu''on observe\n- Tourne-t-il la tête vers l''adulte quand celui-ci parle ?\n- Y a-t-il alternance — il fait, l''adulte dit, il refait ?\n- Produit-il un son en réponse, même un seul ?\n\n## La vraie difficulté\nTenir cinq minutes sans être appelé ailleurs. Cela suppose que la collègue prend le groupe et le sait. Sans cet accord d''équipe, la petite parlotte n''a simplement jamais lieu — et c''est ce qui se passe presque partout.\n\n## Combien de fois\nUn enfant par jour, noté sur la feuille de l''équipe. En trois semaines, chacun y est passé deux fois. C''est peu, et c''est déjà beaucoup plus que rien.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 8, 2, 79, 'activité d''expression', NULL,
 NULL, false, 'Les sons familiers : répondre à un son par un son',
 'Langage', 'BMG_0-3', 'ludique',
 'Fiches « Sons familiers » et « Est-ce que tu peux m''imiter ? » du référentiel d''éveil 0-3 ans.',
 E'# Les sons familiers\n\n**Âge** : 4 à 18 mois · **Un enfant** · **5 minutes** · **Face à face, très près**\n\n## Ce qui se joue\nAvant les mots, il y a le tour de parole. Un bébé qui produit un son, entend une réponse, et produit un autre son a compris le principe même de la conversation. Le contenu n''a aucune importance ; l''alternance a toute l''importance.\n\n## Déroulé\n\n**Reprendre son son à lui.** Il fait « ba » : on fait « ba ». Exactement le même, avec le même ton. Il refait, souvent plus fort — la boucle est lancée.\n\n**Attendre entre deux.** Le silence est ce qui lui donne la place de reprendre. Sans silence, ce n''est plus un échange, c''est un adulte qui vocalise.\n\n**Ajouter, une fois sur trois.** Il fait « ba », on fait « ba-ba ». On enrichit sans corriger, et on revient à l''imitation simple s''il décroche.\n\n**Les sons du quotidien.** Le chien, la voiture, la porte qui grince. Ils font le lien entre le son et le monde ; c''est par eux que passent souvent les premiers mots.\n\n## Ce qu''on observe\n- Attend-il la réponse de l''adulte ?\n- Y a-t-il alternance, ou parle-t-il en même temps ?\n- Regarde-t-il la bouche de l''adulte ? Il apprend à la lire, et c''est bon signe.\n\n## La distance\nTrès près — quarante centimètres, pas deux mètres. Il faut qu''il voie la bouche bouger. Un adulte debout qui parle de loin ne produit aucun de ces effets.\n\n## Quand l''enfant ne répond pas\nOn continue trois tours, puis on arrête sans insister, et on reprendra un autre jour. L''absence de réponse répétée sur plusieurs semaines se note et se dit en équipe — c''est une observation, pas un diagnostic.',
 'termine', now(), now()),

-- ══ Séance 9 — L'histoire qu'on redemande ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 9, 1, 76, 'activité de lecture', NULL,
 NULL, false, 'La même histoire, exactement pareil, pour la neuvième fois',
 'Langage', 'BMG_0-3', 'classique',
 'Fiche « Récit et invention d''histoires » du référentiel d''éveil 0-3 ans, et repères sur la répétition et l''anticipation.',
 E'# La même histoire, exactement pareil\n\n**Âge** : 18 à 36 mois · **Quatre enfants** · **8 minutes** · **Au coin lecture, au sol**\n\n## Pourquoi ne rien changer\nUn enfant qui réclame la même histoire pour la neuvième fois ne s''ennuie pas : il vérifie. Savoir ce qui va arriver, et que cela arrive vraiment, est une source de sécurité — et c''est ce qui lui permet de dire le mot avant l''adulte. Changer les mots d''une histoire connue, même pour l''améliorer, casse ce travail.\n\n## Déroulé\n\n**Les mêmes mots, les mêmes intonations.** L''adulte se lasse bien avant les enfants : c''est un fait, et ce n''est pas une raison.\n\n**La pause d''une seconde de trop.** Sur la page attendue, on s''arrête juste avant le mot. Quelqu''un le dira. C''est tout le but de la lecture.\n\n**On ne saute pas de page**, même celle qui n''intéresse personne : ils savent qu''elle existe.\n\n**On relit si on le demande.** Deux fois de suite est courant. Trois arrive.\n\n## Ce qu''on observe\n- Tourne-t-il les pages avant l''adulte ? Il connaît la suite.\n- Dit-il le mot manquant sur la pause ?\n- Réclame-t-il le livre à un autre moment de la journée ?\n\n## Le choix du livre\nCourt — six à huit pages. Une seule idée par page. Des personnages qui reviennent. Les albums qui « racontent une belle histoire » sont souvent écrits pour les adultes qui les achètent.\n\n## Ce qui casse le moment\nInterroger pendant la lecture. Expliquer les images. Lire debout. Lire à huit enfants — au-delà de quatre, les derniers ne voient plus les images et décrochent en deux pages.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 9, 2, 79, 'activité d''expression', NULL,
 NULL, false, 'Rejouer l''histoire avec trois objets',
 'Langage', 'BMG_0-3', 'ludique',
 'Fiches « Interprétation théâtrale d''une histoire » et « Créer ses propres livres de lecture » du référentiel d''éveil 0-3 ans.',
 E'# Rejouer l''histoire avec trois objets\n\n**Âge** : 24 à 36 mois · **Trois enfants** · **10 minutes** · **Après la lecture, jamais avant**\n\n## Le passage difficile\nL''histoire quitte le livre et passe dans les mains. C''est un vrai changement de registre : l''objet ne ressemble pas au personnage, il en **tient la place**. Certains enfants n''y entrent pas tout de suite, et cela n''a rien d''inquiétant.\n\n## Matériel\nTrois objets, un par personnage. Pas des figurines réalistes : un bouchon, une cuillère en bois, un foulard. Moins l''objet ressemble, plus il faut faire semblant — et c''est précisément le travail.\n\n## Déroulé\n\n**L''adulte commence.** Il refait l''histoire connue, en déplaçant les objets, avec les mêmes phrases que le livre.\n\n**Chaque enfant prend un objet.** Il le fait avancer quand c''est le tour de son personnage. L''adulte dit le texte ; les enfants font bouger.\n\n**On laisse dériver.** Au troisième passage, l''histoire part ailleurs : le bouchon s''envole, la cuillère mange tout le monde. On suit. L''invention est ce qu''on cherchait.\n\n## Ce qu''on observe\n- L''enfant fait-il bouger son objet au bon moment ?\n- Lui prête-t-il une voix, un mot ?\n- Accepte-t-il qu''un bouchon « soit » le personnage, ou réclame-t-il le livre ?\n\n## Prolongement — le livre du groupe\nOn colle des photos des enfants dans un album fabriqué, avec une phrase dictée par eux, et on le relit aussitôt. Se reconnaître dans un livre change le statut du livre : en quelques semaines, c''est le plus consulté de l''étagère, bien avant ceux du commerce.\n\n## Ce qu''il ne faut pas faire\nDistribuer les rôles autoritairement. Reprendre un enfant qui « se trompe » de moment. Rejouer une histoire qui n''a pas été lue et relue avant : sans le texte en tête, il n''y a rien à rejouer.',
 'termine', now(), now()),

-- ══ Séance 10 — La première trace ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 10, 1, 78, 'activité manuelle et artistique', NULL,
 NULL, false, 'Le kraft au sol : tracer avec tout le bras',
 'Créativité, imagination et expression', 'BMG_0-3', 'classique',
 'Fiche « Papier et crayons » du référentiel d''éveil 0-3 ans : papier, gros crayons cire pour les petits, crayons de couleur.',
 E'# Le kraft au sol\n\n**Âge** : 14 à 36 mois · **Trois ou quatre enfants** · **12 minutes** · **Blouses accessibles**\n\n## Le sol plutôt que la table\nÀ cet âge, le tracé part de l''épaule, pas du poignet. Il a besoin d''une grande surface et d''un appui stable. Une feuille A4 sur une table haute contraint un geste qui n''est pas encore contraignable — et produit un enfant qui abandonne au bout de trente secondes.\n\n## Matériel\nDu papier kraft en grand format, fixé au sol par les quatre coins. Des gros crayons de cire, en nombre suffisant pour éviter les conflits — quatre enfants, douze crayons. Une éponge humide à portée.\n\n## Déroulé\n\n**Dérouler ensemble (3 min).** On fixe les coins avec eux. Voir la surface apparaître prépare autant que la surface elle-même.\n\n**Tracer (12 min).** Aucune consigne de contenu. L''adulte trace lui aussi, dans un coin, **sans faire de modèle** : ni soleil, ni bonhomme, ni maison. Une seule forme reconnaissable dessinée par un adulte, et tout le monde essaie de la refaire.\n\n**Regarder (5 min).** Tous debout au-dessus de la feuille. L''adulte nomme ce qu''il voit : « là c''est très serré », « ici tu es allé jusqu''au bord ». Jamais à quoi cela ressemble.\n\n## La question à ne pas poser\n« Qu''est-ce que c''est ? » À cet âge, ce n''est rien : c''est un geste, pas une image. La question oblige l''enfant à inventer une réponse pour faire plaisir, et lui apprend que le tracé doit représenter quelque chose. Il y viendra tout seul, vers trois ans.\n\n## Ce qu''on observe\n- Regarde-t-il la trace pendant qu''il la fait, ou après ?\n- Change-t-il de couleur volontairement ?\n- Va-t-il jusqu''aux bords, ou reste-t-il devant lui ?\n\n## La règle d''équipe\nOn écrit le prénom **à côté** de la trace, jamais dessus. On ne retouche rien, on n''ajoute rien, on ne découpe pas pour faire joli avant d''afficher.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 10, 2, 82, 'activité psychosociale manuelle et artistique', 'empreinte de main',
 NULL, false, 'L''empreinte de main sur la feuille du groupe',
 'Créativité, imagination et expression', 'BMG_0-3', 'ludique',
 'Fiche « Notre cercle de mains » du référentiel d''éveil 0-3 ans : trace collective, place de chacun dans le groupe.',
 E'# L''empreinte de main\n\n**Âge** : 12 à 36 mois · **Six enfants** · **12 minutes** · **Peinture à doigts, bassine d''eau tiède**\n\n## Ce que ce n''est pas\nCe n''est pas un objet décoratif à rapporter aux parents. Si c''en devient un, l''adulte finit par tenir la main de l''enfant pour que l''empreinte soit nette — et l''activité a changé de propriétaire.\n\n## Ce que c''est\nUne trace de sa présence, posée à côté de celle des autres, sur la même feuille. Un enfant de deux ans ne coopère pas encore ; il peut en revanche **être là en même temps**, et le voir.\n\n## Déroulé\n\n**Une grande feuille ronde** au centre, posée au sol.\n\n**Chacun à son tour**, deux enfants d''attente au maximum : la main dans la peinture, la main sur la feuille, et on lève. Le cercle se forme empreinte après empreinte.\n\n**Celui qui refuse la peinture pose sa main sèche** : on trace le contour au crayon. Sa place est marquée comme les autres — c''est le point qui compte, pas la matière.\n\n**On lave ensemble**, dans une seule bassine d''eau tiède, tout le monde en même temps. C''est souvent le moment le plus joyeux, et le plus collectif.\n\n## Ce qu''on observe\n- L''enfant regarde-t-il l''empreinte de son voisin ?\n- Reconnaît-il la sienne après coup ?\n- Supporte-t-il la peinture sur les mains ? Certains ont besoin de plusieurs séances, et d''une éponge à portée.\n\n## Après\nLa feuille est affichée **à hauteur d''enfant**, prénoms écrits à côté des mains, jamais dessus. Des semaines durant, ils viendront poser leur main sur la leur pour vérifier qu''elle y est encore. C''est à cela qu''on voit que l''activité a fonctionné.',
 'termine', now(), now()),

-- ══ Séance 11 — La matière dans les mains ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 11, 1, 78, 'activité manuelle et artistique', NULL,
 NULL, false, 'La pâte à modeler sans outil ni modèle',
 'Créativité, imagination et expression', 'BMG_0-3', 'classique',
 'Fiche « Pâte à modeler » du référentiel d''éveil 0-3 ans : pâte à modeler, éléments naturels (coquillages, feuilles, brindilles) en prolongement.',
 E'# La pâte à modeler sans outil\n\n**Âge** : 18 à 36 mois · **Quatre enfants** · **15 minutes** · **Table basse, une boule par enfant**\n\n## Pourquoi sans outil\nEmporte-pièces et rouleaux transforment l''exploration en production : on obtient des étoiles, et on n''a rien appris de la matière. Le premier travail, c''est de découvrir ce que la pâte fait quand on la presse, l''arrache, la recolle.\n\n## Matériel\nUne boule par enfant, souple, tiède si possible — une pâte dure décourage des mains qui n''ont pas encore de force. Rien d''autre sur la table pendant les dix premières minutes.\n\n## Déroulé\n\n**Explorer (10 min).** Taper, pincer, arracher un morceau, le recoller, le mettre dans l''autre main. On ne montre rien. Un enfant qui malaxe quinze minutes sans rien produire a fait l''activité en entier.\n\n**L''empreinte (5 min).** On propose des coquillages, des brindilles, un bouchon. On appuie, on retire : la trace reste. C''est souvent le moment où le groupe devient silencieux — la surprise est réelle et elle mérite qu''on se taise aussi.\n\n## Ce qu''on observe\n- Transforme-t-il volontairement, ou subit-il la matière ?\n- Recommence-t-il un geste qui a produit un effet ? C''est le début de l''intention.\n- Nomme-t-il ce qu''il a fait — « un serpent », « un gâteau » — après coup ? Le nom vient après la forme, jamais avant, et c''est un grand pas.\n\n## Ce qui n''a pas sa place\nUn modèle affiché. Une consigne de forme. Un adulte qui fabrique un escargot « pour montrer » : après cela, plus personne n''explore, tout le monde tente l''escargot et échoue.\n\n## Hygiène\nMains lavées avant et après. Pâte jetée si elle est tombée au sol. Chaque enfant garde sa boule pendant toute la séance — la partager est un conflit gratuit à cet âge.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 11, 2, 78, 'activité manuelle et artistique', NULL,
 NULL, false, 'Déchirer, coller, superposer : la table de collage',
 'Créativité, imagination et expression', 'BMG_0-3', 'ludique',
 'Fiche « Collages et mosaïques » du référentiel d''éveil 0-3 ans.',
 E'# La table de collage\n\n**Âge** : 20 à 36 mois · **Quatre enfants** · **12 minutes** · **Supports cartonnés**\n\n## Ce qui intéresse vraiment\nLa colle. Pas le résultat. Un enfant de deux ans colle, décolle, recolle au même endroit, et met de la colle sur ses doigts pour voir. C''est l''activité réelle ; le collage est un prétexte.\n\n## Matériel\nDes papiers de textures franchement différentes : lisse, ondulé, crépon, papier de soie. Des supports cartonnés rigides — une feuille souple se plie et gâche tout. De la colle en bâton **et** de la colle liquide au pinceau, côte à côte.\n\n## Les deux colles\n\n| Colle | Geste | Ce qu''elle apprend |\n|---|---|---|\n| Bâton | Frotter, appuyer | Le contrôle de la pression |\n| Liquide au pinceau | Tremper, étaler, poser | Un geste lent, en deux temps |\n\nLa liquide est plus difficile et plus salissante. Elle vaut la peine : c''est elle qui fait entrer dans un geste en deux étapes.\n\n## Déroulé\n\n**Déchirer d''abord (4 min).** Le déchirage compte autant que le collage — deux mains qui tirent en sens contraire, c''est un vrai travail moteur.\n\n**Coller (8 min).** Aucune consigne de composition. On superpose, on recouvre tout, on colle un seul morceau au milieu.\n\n## Ce qu''on observe\n- Met-il de la colle avant de poser, ou pose-t-il puis cherche la colle ?\n- Supporte-t-il d''avoir les doigts collants ?\n- Regarde-t-il ce que fait son voisin, et l''imite-t-il ?\n\n## Ce qu''on en fait\nOn affiche tel quel, sans redresser les morceaux qui dépassent, sans recoller ceux qui tombent. Un collage retouché par un adulte n''est plus celui de l''enfant, et les enfants le voient très bien.',
 'termine', now(), now()),

-- ══ Séance 12 — Prêter sa voix ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 12, 1, 79, 'activité d''expression', NULL,
 NULL, false, 'La marionnette qui arrive et qui dit bonjour à chacun',
 'Créativité, imagination et expression', 'BMG_0-3', 'ludique',
 'Fiches « Marionnettes » et « Contes avec marionnettes » du référentiel d''éveil 0-3 ans : sécurité affective, imagination, expression.',
 E'# La marionnette qui arrive\n\n**Âge** : 12 à 36 mois · **Six enfants** · **10 minutes** · **Deux marionnettes à main**\n\n## Comment elle doit être\nUn peu maladroite. Elle se trompe de prénom, elle bafouille, elle ne trouve pas ses mots. Un personnage parfait impressionne ; un personnage qui rate rassure et donne envie de l''aider.\n\nElle ne gronde jamais. Une marionnette qui fait la leçon détruit le dispositif en une phrase : elle devient la voix de l''adulte, et plus personne ne lui parle.\n\n## Déroulé\n\n**Elle arrive** — lentement, en se montrant d''abord de loin. Elle salue chaque enfant par son prénom, lui pose une question, **et attend**.\n\n**Elle ne touche personne sans prévenir.** Elle demande, elle approche doucement, elle recule si l''enfant recule.\n\n**Certains ont peur.** C''est fréquent vers dix-huit mois. La marionnette reste alors à distance et parle à quelqu''un d''autre ; on n''insiste jamais, et la peur passe d''elle-même en deux ou trois séances.\n\n**Elle repart** en le disant, comme elle est arrivée.\n\n## Ce qu''on observe\n- L''enfant lui parle-t-il comme à quelqu''un ?\n- Lui tend-il un objet ? C''est la première forme d''échange avec un personnage.\n- La cherche-t-il du regard quand elle a disparu ?\n\n## Le passage aux marionnettes à doigts\nOn les distribue, et **l''adulte se tait complètement**. Ce silence est la partie difficile : à la première hésitation, on a envie de relancer, et cela referme le jeu. Certains manipulent l''objet sans le faire parler — c''est normal à cet âge, faire semblant s''installe progressivement.\n\n## Ce qu''il ne faut pas faire\nFaire dire à la marionnette ce qu''on n''ose pas dire soi-même. Les enfants ne s''y trompent pas, et ils cessent de jouer.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 12, 2, 79, 'activité d''expression', NULL,
 NULL, false, 'De la musique sans instrument : le corps et une boîte en carton',
 'Créativité, imagination et expression', 'BMG_0-3', 'ludique',
 'Fiche « Nous pouvons faire de la musique » du référentiel d''éveil 0-3 ans : imaginer des façons de produire des sons avec son corps, répétition de rythmes.',
 E'# De la musique sans instrument\n\n**Âge** : 12 à 36 mois · **Le groupe** · **8 minutes** · **Une boîte en carton, rien d''autre**\n\n## Pourquoi pas d''instruments\nUn tambourin fait du bruit tout seul : il n''y a rien à chercher. Sans instrument, l''enfant doit inventer d''où le son peut venir — des mains, des pieds, de la bouche, du sol, de la boîte. C''est la recherche qui a de la valeur.\n\n## Déroulé\n\n**Trouver des sons (3 min).** Taper des mains, des pieds, sur les cuisses, sur le sol, sur la boîte. Souffler. Claquer la langue. L''adulte propose puis se tait ; les enfants trouvent des choses auxquelles il n''avait pas pensé.\n\n**Fort et doux (3 min).** Le même geste, très fort, puis très doucement. Le contraste est immédiatement compris, bien avant les nuances intermédiaires.\n\n**Un rythme court (2 min).** Deux frappes, toujours les mêmes. On recommence dix fois. Voir qui le reprend, et quand.\n\n## Ce qu''on observe\n- Cherche-t-il d''autres sons de lui-même ?\n- Reprend-il le rythme à deux frappes ? Même décalé, c''est acquis.\n- Passe-t-il du fort au doux sur signal, ou reste-t-il dans le fort ?\n\n## La boîte en carton\nElle sonne différemment selon qu''on la frappe sur le dessus, sur le côté ou dessous. C''est un instrument entier, gratuit, et les enfants passent beaucoup de temps à en faire le tour.\n\n## La fin\nOn finit toujours par le son le plus doux, jamais par le plus fort. Cela évite de sortir de la séance en tapant sur tout ce qui traîne pendant l''heure suivante.',
 'termine', now(), now());
