-- ============================================================================
-- creche_demo — partie 3/3 (a) : les activités des séquences 1 et 2
--                                (motricité, puis réflexion et repérage)
--
-- `activite_type_id` pointe le type d'activité DU RÉFÉRENTIEL (table
-- `types_activite`, colonne `referentiel_id` = 2), et `sous_type` reprend, mot
-- pour mot, une précision de `referentiel_type_precisions` — ou reste vide
-- quand le type n'en a pas. Six types sur neuf n'ont pas de précision : le
-- professionnel choisit alors le type seul, et c'est un cas normal.
--
-- `nb` et `avec_correction` restent à NULL et false : il n'y a ni exercices
-- numérotés ni corrigé en crèche. `objet` est ce que le professionnel a
-- demandé, `texte_source` la fiche du référentiel dont il est parti, et
-- `resultat` ce que l'écran affiche.
-- ============================================================================

INSERT INTO activites (user_id, seance_id, position, activite_type_id, activite_label, sous_type,
                       nb, avec_correction, objet, matiere, niveau, ton, texte_source, resultat,
                       statut, created_at, updated_at) VALUES

-- ══ Séance 1 — Attraper, lâcher, viser ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 1, 1, 75, 'jeu avec un jouet', 'encastrement dans des trous',
 NULL, false, 'Le plateau du puzzle à encastrer, pour trois enfants de 14 à 24 mois',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 'classique',
 'Fiche « Puzzle à encastrer » du référentiel d''éveil 0-3 ans : activité avec matériel du kit, bébés (0-1 an) et 1-3 ans, puzzle à encastrer sans boutons.',
 E'# Le plateau du puzzle à encastrer\n\n**Âge** : 14 à 24 mois · **Trois enfants** · **10 à 15 minutes** · **Un adulte assis au sol**\n\n## Matériel\nUn puzzle à encastrer sans boutons, à trois ou quatre pièces de formes franchement différentes (un rond, un carré, un triangle). Un panier vide à côté. Rien d''autre sur le tapis — un second jeu à portée de main détourne immédiatement.\n\n## Installation\nLe puzzle est posé complet devant l''enfant, pièces en place. Il le videra lui-même : c''est le premier geste, et il ne faut pas le lui prendre.\n\n## Déroulé\n\n**Vider.** L''enfant retire les pièces, souvent toutes d''un coup, et parfois s''arrête là. Vider est une action complète à cet âge ; on ne relance pas vers le remplissage.\n\n**Essayer.** La pièce est présentée au creux. Si elle ne rentre pas, on attend. L''enfant tourne, ou force, ou abandonne et en prend une autre — les trois sont des solutions.\n\n**Ce que dit l''adulte.** Il décrit, il ne guide pas : « elle ne rentre pas de ce côté », « tu l''as tournée », « elle est tombée dedans ». Jamais « non », jamais « essaie l''autre », jamais la main sur la main de l''enfant.\n\n**Recommencer.** Un enfant qui réussit une fois recommencera dix fois. C''est la répétition qui installe, pas la première réussite.\n\n## Ce qu''on observe\n- Regarde-t-il le creux avant de présenter la pièce, ou présente-t-il d''abord ?\n- Tourne-t-il la pièce quand elle résiste ?\n- Lâche-t-il exactement au-dessus du creux, ou à côté ?\n\n## Sécurité\nPièces d''au moins 5 cm, sans bouton ni petite partie détachable. L''adulte reste assis à côté pendant toute la durée.\n\n## Si ça ne marche pas\nQuatre pièces, c''est déjà beaucoup. Retirer les formes trop proches (le carré et le rectangle ensemble sont un piège) et n''en laisser que deux, très différentes.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 1, 2, 75, 'jeu avec un jouet', NULL,
 NULL, false, 'Les perles à enfiler : deux mains qui font deux choses différentes',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 'classique',
 'Fiche « Perles à enfiler » du référentiel d''éveil 0-3 ans : perles et cordelettes, coordination œil-main, distinction des couleurs.',
 E'# Les perles à enfiler\n\n**Âge** : 22 à 36 mois · **Deux enfants au maximum** · **10 minutes** · **Surveillance directe obligatoire**\n\n## Pourquoi c''est difficile\nEnfiler demande que les deux mains fassent des choses différentes en même temps : l''une tient et oriente, l''autre présente et pousse. C''est l''une des premières dissociations manuelles, et elle arrive tard.\n\n## Matériel\nDes perles à gros trou et une cordelette **rigide** — un lacet mou rend la tâche presque impossible avant trois ans, et fait échouer des enfants qui en sont capables. Un récipient bas pour les perles.\n\n## Déroulé\n\n**1. Manipuler avant d''enfiler.** On laisse d''abord les perles se verser, se transvaser, rouler. Cette exploration n''est pas du temps perdu : elle fait connaître le poids et la taille.\n\n**2. Le premier enfilage.** L''adulte présente la cordelette tendue, verticale. L''enfant amène la perle. On ne tient pas la perle à sa place.\n\n**3. La suite.** Une fois la première passée, la deuxième vient plus vite. Certains enfilent puis retirent tout, immédiatement : c''est un aller-retour complet, pas un échec.\n\n## Ce qu''on observe\n- Les deux mains travaillent-elles ensemble, ou une seule agit-elle ?\n- L''enfant vise-t-il le trou du regard ?\n- Nomme-t-il ou choisit-il les couleurs ? Le tri arrive souvent tout seul, sans qu''on le demande.\n\n## Sécurité — la règle absolue\nJamais sans adulte à côté. Jamais de cordelette dépassant 25 cm. On range immédiatement après ; ce matériel ne reste pas en accès libre.\n\n## Prolongement\nLes plus grands enfilent en alternant deux couleurs, si — et seulement si — ils le proposent eux-mêmes.',
 'termine', now(), now()),

-- ══ Séance 2 — Ramper, grimper, redescendre ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 2, 1, 77, 'activité récréative', NULL,
 NULL, false, 'Le parcours des trois éléments, sens libre',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 'structure',
 'Fiches « Nous pouvons bouger » et « Balles en éponge » du référentiel d''éveil 0-3 ans : équilibre, ramper, se mettre à genoux, contrôle du mouvement.',
 E'# Le parcours des trois éléments\n\n**Âge** : 12 à 30 mois · **Six enfants** · **20 minutes** · **Deux adultes**\n\n## Le principe\nAucun sens obligatoire, aucun tour de rôle, aucune file d''attente. Un parcours qui s''emprunte dans les deux sens laisse chacun choisir sa difficulté — et les enfants la choisissent remarquablement bien.\n\n## Les trois éléments\n\n| Élément | Ce qu''il demande | Difficulté réelle |\n|---|---|---|\n| Tunnel en tissu | Se baisser, avancer à quatre pattes | Perdre l''adulte de vue |\n| Marche de mousse | Monter, se redresser, redescendre | La descente |\n| Plan incliné | Monter en pente, se retourner | Se retourner en hauteur |\n\n## Déroulé\n\n**Montrer une fois, en silence.** L''adulte fait le parcours entier sans un mot. L''imitation fait tout le travail ; les explications ne servent à rien à cet âge.\n\n**Laisser faire.** Vingt minutes de passages libres. Un enfant qui refait le tunnel quinze fois travaille exactement ce dont il a besoin.\n\n**Les balles, à la fin.** Quatre balles en éponge lâchées dans la zone : on court après, on se baisse, on lance. La dépense monte d''un cran — puis on arrête net, et on enchaîne sur le retour au calme.\n\n## La règle qui compte\nOn ne hisse jamais un enfant sur un module. Ce qu''il ne monte pas seul, il ne sait pas le redescendre : l''aider à monter, c''est le mettre en difficulté trente secondes plus tard.\n\n## Ce qu''on observe\n- S''engage-t-il seul, ou cherche-t-il un regard avant chaque élément ?\n- Comment redescend-il ? À reculons est une vraie trouvaille, pas une peur.\n- Refait-il le même élément en boucle ?\n\n## Sécurité\nTapis jointifs sous tous les modules, sans interstice. Un adulte fixe près du plan incliné, l''autre circule. Pieds nus ou chaussons antidérapants ; jamais de chaussettes seules.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 2, 2, 83, 'activité psychosociale de jeu, détente et confiance', NULL,
 NULL, false, 'Grimper avec quelqu''un qui regarde : la confiance qui porte le geste',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 'classique',
 'Fiche « Exercices de détente, de calme et de confort » et repères d''observation professionnelle du référentiel d''éveil 0-3 ans.',
 E'# Grimper avec quelqu''un qui regarde\n\n**Âge** : 14 à 30 mois · **En parallèle du parcours** · **Toute la durée** · **Un adulte immobile**\n\n## De quoi il s''agit\nCe n''est pas une activité de plus : c''est la façon dont l''adulte se tient pendant que les autres grimpent. Un enfant ose davantage quand il sait qu''on le voit — et il ose moins bien quand on le tient.\n\n## La position de l''adulte\n\n**Assis, à hauteur, immobile.** Debout au-dessus, on domine et on inquiète. En mouvement, on capte l''attention. Assis et stable, on devient un point de repère qu''on peut quitter et retrouver du regard.\n\n**À un mètre, pas à dix centimètres.** Trop près, l''adulte fait partie du module et l''enfant s''appuie sur lui. Un mètre laisse la place de faire seul, et permet d''intervenir si le corps part en arrière.\n\n**Les mains visibles et disponibles, jamais posées.** L''enfant doit voir qu''elles existent. Il ne doit pas les sentir tant qu''il tient.\n\n## Ce qu''on dit\nOn nomme ce qui se passe : « tu es monté », « tu regardes en bas », « tu descends doucement ». On ne dit ni « bravo », ni « attention », ni « fais pas ça ». « Attention » lancé au mauvais moment fait tomber plus d''enfants qu''il n''en rattrape.\n\n## Ce qu''on observe\n- L''enfant cherche-t-il le regard de l''adulte avant de s''engager, pendant, ou après ?\n- Recommence-t-il quand personne ne regarde ? C''est le signe que le geste est acquis pour lui-même.\n- Va-t-il chercher l''adulte quand il est bloqué en haut, ou reste-t-il figé ?\n\n## Le cas de l''enfant qui reste bloqué\nOn ne le descend pas immédiatement. On se rapproche, on nomme la situation, on montre l''appui possible avec la main sans le toucher. S''il ne trouve pas au bout d''une minute, on l''aide — en le guidant, pas en le portant.\n\n## Pourquoi ce type d''activité\nÉlément de confiance et de sécurité affective autant que de motricité : ce qui se joue ici, c''est la certitude qu''un adulte fiable est disponible, et cette certitude sert bien au-delà du parcours.',
 'termine', now(), now()),

-- ══ Séance 3 — Après l'élan, le calme ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 3, 1, 77, 'activité récréative', 'jeu chanté',
 NULL, false, 'La ronde qui ralentit : une comptine, deux tempos',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 'ludique',
 'Fiches « Déplacement en ronde » et « Nous pouvons faire de la musique » du référentiel d''éveil 0-3 ans.',
 E'# La ronde qui ralentit\n\n**Âge** : 12 à 36 mois · **Le groupe entier** · **10 minutes** · **Aucun matériel**\n\n## L''idée en une phrase\nOn ne demande pas à un groupe excité de se calmer : on lui donne un tempo, et on ralentit le tempo.\n\n## La comptine\nToujours la même, celle que le groupe connaît par cœur. Une comptine nouvelle demande de l''attention — exactement ce qu''on n''a pas au sortir de la motricité.\n\n## Les deux tempos\n\n**Premier tour — vif, debout, en tournant.** On accepte les cris, les mains qui se lâchent, les enfants qui tombent en riant. C''est le sommet et il faut y passer : sauter cette étape fait échouer la suivante.\n\n**Deuxième tour — assis, deux fois plus lent.** Même comptine, même mots, voix plus basse. **On n''annonce rien.** Le groupe suit le tempo sans qu''on le demande : c''est le chant qui commande, pas la consigne.\n\nEntre les deux, un troisième tour intermédiaire aide les groupes très agités.\n\n## Ce qu''on observe\n- Le groupe ralentit-il avec le chant, ou faut-il encore des mots ?\n- Qui reprend les paroles ? Qui reprend seulement les gestes ?\n- Combien de temps le calme tient-il après la fin ?\n\n## Ce qui ne marche pas\nDemander le silence. Taper dans les mains pour obtenir l''attention. Changer de comptine parce qu''on en a assez de celle-là — l''adulte se lasse bien avant les enfants, et c''est la répétition qui produit l''effet.\n\n## Prolongement\nLa même comptine devient le signal du rangement, puis celui du passage aux mains lavées. Un chant qui annonce toujours la même chose évite une consigne verbale par jour.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 3, 2, 83, 'activité psychosociale de jeu, détente et confiance', NULL,
 NULL, false, 'Le foulard qui passe : retrouver son corps au repos',
 'Motricité et coordination', 'Moyens-Grands (1-3 ans)', 'concis',
 'Fiche « Exercices de détente, de calme et de confort » du référentiel d''éveil 0-3 ans.',
 E'# Le foulard qui passe\n\n**Âge** : 10 à 36 mois · **Six enfants** · **5 à 8 minutes** · **Lumière baissée**\n\n## Déroulé\n\n**Allongés ou assis** — au choix de chacun. Personne n''est couché de force ; l''enfant assis participe autant.\n\n**Le foulard passe lentement** sur un bras, puis l''autre, puis les jambes. Jamais le visage, jamais le ventre. L''adulte nomme au passage : « ton bras », « ta main », « ton pied ».\n\n**Chaque enfant est touché à son tour**, dans le même ordre à chaque séance. Savoir quand vient son tour fait partie du calme.\n\n## Ce qu''on observe\n- L''enfant tend-il le bras vers le foulard ? Il demande.\n- Le retire-t-il ? Il refuse, et son refus est respecté sans commentaire.\n- Reste-t-il allongé après son tour, ou se relève-t-il aussitôt ?\n\n## Durée réelle\nTrente secondes d''immobilité chez un enfant de dix-huit mois est un résultat. On ne cherche pas cinq minutes de silence : on cherche un palier entre la course et le repas.\n\n## Variante quand le groupe est trop agité\nCommencer par les pieds plutôt que par les bras : c''est plus loin du visage, moins intrusif, et souvent mieux accepté par les enfants récemment arrivés.\n\n## Ce qu''il ne faut pas faire\nÉteindre brutalement. Parler à voix haute par-dessus. Toucher un enfant qui s''est écarté du groupe : s''il s''est mis à distance, c''est sa façon de se calmer.',
 'termine', now(), now()),

-- ══ Séance 4 — Un objet, une place ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 4, 1, 75, 'jeu avec un jouet', NULL,
 NULL, false, 'Trier les cubes par couleur, un critère et un seul',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 'ludique',
 'Fiches « Cubes de construction » et « Ensemble d''objets à trier et empiler » du référentiel d''éveil 0-3 ans.',
 E'# Trier les cubes par couleur\n\n**Âge** : 20 à 36 mois · **Trois ou quatre enfants** · **15 minutes** · **Table basse ou tapis**\n\n## Le principe\nUn seul critère. La couleur, ou la taille, jamais les deux le même jour. Tenir un critère du début à la fin d''une tâche est un effort mental considérable à deux ans ; en ajouter un second fait tout écrouler.\n\n## Matériel\nDes cubes de trois couleurs franches — rouge, bleu, jaune. Trois bacs, chacun avec un cube de sa couleur collé devant, en guise d''étiquette. Une dizaine de cubes par couleur, pas davantage : un grand tas décourage.\n\n## Déroulé\n\n**Le mélange.** On verse tout au centre. Le désordre volontaire fait rire et donne envie de s''y mettre.\n\n**Chacun cherche.** Un cube à la fois. L''adulte nomme : « un rouge avec les rouges », « celui-là est bleu ». Il ne dit jamais « non, pas là ».\n\n**On regarde ensemble.** Bac par bac. On constate les intrus à voix haute — « il y a un bleu chez les rouges » — **et on ne les déplace pas**. Le voir suffit. C''est la fois suivante qu''il bougera.\n\n## Ce qu''on observe\n- L''enfant tient-il son critère jusqu''au bout, ou change-t-il en cours de route ?\n- Utilise-t-il l''étiquette du bac, ou cherche-t-il l''adulte du regard ?\n- Va-t-il récupérer un cube tombé sous le meuble ? Il a l''ensemble en tête.\n\n## Ce qui arrive souvent\nUn enfant empile au lieu de trier. Il fait autre chose de très bien : on nomme l''empilement, on le laisse aller au bout, et on ne le ramène pas à la consigne.\n\n## Prolongement\nLe même dispositif devient le rangement de la salle. C''est là qu''il prend son sens : trier pour de vrai, pas pour l''exercice.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 4, 2, 81, 'rituel collectif', NULL,
 NULL, false, 'Le rangement de fin de matinée, tous les jours, dans le même ordre',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 'structure',
 'Fiche « Rituels et habitudes » du référentiel d''éveil 0-3 ans, et repères sur le cadre et les repères quotidiens.',
 E'# Le rangement de fin de matinée\n\n**Âge** : 14 à 36 mois · **Le groupe entier** · **8 minutes** · **Tous les jours, même horaire**\n\n## Pourquoi c''est un rituel et pas une corvée\nRanger, c''est trier en situation réelle : chaque objet a une place, la place est signalée par une photo, et le résultat se voit. Fait tous les jours au même moment, cela devient un repère temporel — les enfants savent que le repas suit.\n\n## Le déroulé, toujours identique\n\n**1. Le signal.** La même comptine, jamais une consigne criée. Elle annonce, elle ne commande pas.\n\n**2. Les bacs sortent.** Trois bacs photographiés, posés au centre de la pièce. Les photos sont ce qui rend le rangement possible sans adulte.\n\n**3. Chacun porte.** Un objet à la fois, jusqu''au bac. Le trajet compte autant que le tri : porter, viser le bac, lâcher.\n\n**4. Le tour de la pièce.** L''adulte fait le tour à voix haute : « sous la table, il reste un cube ». Il ne le ramasse pas.\n\n**5. La fin est dite.** « C''est rangé, on va se laver les mains. » La clôture explicite fait partie du rituel.\n\n## Ce qu''on observe\n- Qui démarre au signal, sans qu''on nomme personne ?\n- Un enfant range-t-il ce qu''il n''a pas sorti ? C''est une entrée dans le collectif.\n- Les objets retrouvent-ils le bon bac, ou n''importe lequel ?\n\n## Les erreurs qui vident le rituel de son sens\nRanger à leur place parce qu''on est pressé. Sauter le rituel un jour de retard — c''est précisément le jour où il sert le plus. Changer l''ordre des étapes.\n\n## Ce qu''on en retire au bout de trois semaines\nLes enfants rangent avant le signal. Non parce qu''ils obéissent mieux, mais parce qu''ils savent ce qui vient.',
 'termine', now(), now()),

-- ══ Séance 5 — Ce qui a disparu revient ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 5, 1, 75, 'jeu avec un jouet', NULL,
 NULL, false, 'Les trois cachettes, de la plus facile à la plus difficile',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 'structure',
 'Fiche « Jeux pour trouver des objets et des personnes » du référentiel d''éveil 0-3 ans.',
 E'# Les trois cachettes\n\n**Âge** : 8 à 30 mois · **Deux enfants** · **10 minutes** · **Assis face à face**\n\n## Ce qui se construit\nQu''un objet continue d''exister quand on ne le voit plus n''a rien d''évident. C''est une acquisition qui se fait par étapes, sur plusieurs mois. Cette activité les propose dans l''ordre — et s''arrête à l''étape où l''enfant en est.\n\n## Les trois étapes\n\n**1. Caché à vue.** L''objet est devant l''enfant ; on pose un foulard dessus pendant qu''il regarde. Il soulève. Presque tous réussissent : c''est le point de départ.\n\n**2. Caché hors de vue.** L''objet entre dans une boîte, la boîte se ferme. Puis il passe derrière le dos de l''adulte. Ici, certains abandonnent aussitôt — ils ne cherchent pas ce qu''ils n''ont pas vu partir.\n\n**3. Deux cachettes possibles.** Sous l''un des deux foulards. Il faut se souvenir, et, en cas d''erreur, chercher sous l''autre. C''est la vraie marche de l''activité.\n\n## L''objet à choisir\nCelui que l''enfant tient déjà, ou son doudou si le groupe est petit et le moment calme. Un objet indifférent ne donne aucune raison de chercher.\n\n## Ce qu''on observe\n- Cherche-t-il, ou se détourne-t-il dès la disparition ?\n- Après une erreur, cherche-t-il ailleurs, ou refait-il exactement le même geste ?\n- Cache-t-il à son tour, pour l''adulte ? C''est l''étape suivante, elle vient seule.\n\n## Le rythme\nLent. Très lent. On cache pendant qu''il regarde, jamais pendant qu''il a la tête tournée : ce n''est pas un tour de magie, c''est un problème qu''on lui donne à résoudre.\n\n## Si l''enfant s''énerve\nRevenir d''une étape en arrière, sans commentaire. Un enfant qui échoue trois fois de suite arrête de chercher pour longtemps.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 5, 2, 80, 'échange individuel', NULL,
 NULL, false, 'Coucou me voilà : le jeu de la disparition, à deux',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 'ludique',
 'Fiches « Jeux pour trouver des objets et des personnes » et « Je suis là. Qui est là ? » du référentiel d''éveil 0-3 ans.',
 E'# Coucou me voilà\n\n**Âge** : 6 à 20 mois · **Un enfant** · **5 minutes** · **Rien d''autre que les mains ou un foulard**\n\n## Pourquoi ce jeu ne lasse jamais\nCe n''est pas l''effet de surprise qui plaît : c''est le retour. L''enfant vérifie, encore et encore, que ce qui disparaît revient — et il n''y a pas d''apprentissage plus utile à cet âge.\n\n## Déroulé\n\n**L''adulte se cache**, derrière ses mains ou un foulard léger, une seconde, pas plus. Puis il réapparaît, avec la même formule à chaque fois.\n\n**Il laisse l''attente s''allonger** au fil des tours : une seconde, deux, trois. Le petit temps de suspense est ce qui donne sa saveur au retour, mais au-delà de trois secondes, l''inquiétude prend le dessus.\n\n**L''enfant prend la main.** Il tire le foulard, ou se cache lui-même — souvent mal, la tête seule, les jambes bien visibles. On fait mine de le chercher partout.\n\n## Pourquoi « échange individuel »\nC''est un jeu à deux, et il perd tout à trois. En groupe, il devient un spectacle ; en tête-à-tête, il devient une conversation.\n\n## Ce qu''on observe\n- L''enfant attend-il la réapparition, ou se détourne-t-il ?\n- Anticipe-t-il, en riant avant le retour ?\n- Prend-il l''initiative de se cacher lui-même ?\n\n## La variante qui compte\nLe même jeu avec les personnes, pas seulement les objets : l''adulte sort du champ de vision une seconde, en parlant, puis revient. C''est le lien direct avec la séparation du matin — et c''est pour cela que ce jeu est précieux chez les enfants qui viennent d''arriver.\n\n## Ce qu''il ne faut pas faire\nAllonger la disparition pour faire durer le plaisir. Se cacher pour de bon. Continuer quand l''enfant a détourné le regard : c''est lui qui décide de la fin.',
 'termine', now(), now()),

-- ══ Séance 6 — Combien il y en a ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 6, 1, 75, 'jeu avec un jouet', 'dénombrement des éléments',
 NULL, false, 'Les dominos à gros points : trouver le même, sans compter',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 'classique',
 'Fiche « Dominos » du référentiel d''éveil 0-3 ans : reproduire une forme, compter les points et retrouver le même nombre, nommer les couleurs.',
 E'# Les dominos à gros points\n\n**Âge** : 26 à 36 mois · **Deux ou trois enfants** · **12 minutes** · **Tapis uni**\n\n## Ce qu''on travaille vraiment\nPas le comptage : la **mise en correspondance**. Comprendre que deux ensembles « vont ensemble » parce qu''ils ont autant d''éléments — et cela se voit avant de se compter.\n\n## Matériel\nDes dominos à points gros et bien espacés, sur un tapis uni. Sur un tapis à motifs, les points se perdent et l''activité échoue pour une raison qui n''a rien à voir avec l''enfant.\n\n## Déroulé\n\n**1. Trouver le même (7 min).** L''adulte pose un domino bien en vue. L''enfant en cherche un pareil. On ne dit pas « trois » : on dit « pareil », « autant », « comme celui-là ».\n\n**2. Aligner les paires (5 min).** Chaque domino trouvé se pose contre son jumeau. La ligne qui s''allonge rend le résultat visible : elle vaut mieux que n''importe quelle félicitation.\n\n## Le dénombrement, quand il apparaît\nCertains pointent les points un à un en disant des mots-nombres. Souvent faux : « un, deux, cinq ». **On ne corrige pas.** L''essentiel est déjà là : un mot par point, une seule fois chacun. La suite exacte des nombres s''apprendra par les comptines, pas par la correction.\n\n## Ce qu''on observe\n- Compare-t-il les deux dominos du regard, ou prend-il au hasard ?\n- Pointe-t-il en disant un mot par point ?\n- Réussit-il jusqu''à trois ? Au-delà, à cet âge, la comparaison se fait à l''œil, pas au compte.\n\n## Adaptation\nCommencer par les dominos à un et deux points seulement. Ajouter le trois quand les deux premiers sont sûrs. Le double-six n''a rien à faire sur ce tapis.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 6, 2, 76, 'activité de lecture', NULL,
 NULL, false, 'Le livre où l''on montre : un, deux, beaucoup',
 'Réflexion, raisonnement et repérage de l''environnement', 'Moyens-Grands (1-3 ans)', 'classique',
 'Fiches « Imagier » et « Cubes puzzle » du référentiel d''éveil 0-3 ans : éveil du langage, reconstituer une image, concentration.',
 E'# Le livre où l''on montre\n\n**Âge** : 24 à 36 mois · **Deux enfants** · **10 minutes** · **Assis contre l''adulte**\n\n## Le livre\nUn album cartonné où chaque page montre une quantité simple : un chat, deux chats, beaucoup de chats. Pas de chiffres écrits — ils ne servent à rien avant longtemps. Des images grandes, sur fond uni.\n\n## Déroulé\n\n**On montre du doigt en nommant.** L''adulte pointe chaque élément l''un après l''autre, à voix lente : « un... deux... ». Le geste compte autant que le mot : c''est lui qui installe l''idée qu''on ne compte pas deux fois le même.\n\n**On laisse l''enfant pointer.** Il le fera trop vite, ou en pointant deux fois le même. On ne reprend pas : on refait à côté, à son rythme à soi.\n\n**« Beaucoup » a sa page.** C''est un mot très utile et très tôt compris — bien avant quatre ou cinq. Il vaut mieux le donner que de forcer le comptage exact.\n\n## Ce qu''on observe\n- L''enfant pointe-t-il en même temps qu''il dit un mot ?\n- Passe-t-il d''un élément à l''autre sans en oublier ?\n- Réclame-t-il la page où il y en a beaucoup ? C''est presque toujours celle-là.\n\n## Ce qui n''a pas sa place\nDemander « combien il y en a ? » et attendre la bonne réponse. Le livre est une lecture, pas une interrogation. Si l''enfant compte de lui-même, on écoute ; sinon, on lit.\n\n## Après\nLes cubes-puzzle prolongent bien ce moment : reconstituer une image sur quatre faces demande de tenir en tête un ensemble et ses parties — le même travail, avec les mains.',
 'termine', now(), now());
