-- ============================================================================
-- creche_demo — partie 3/3 (c) : les activités de la séquence 5
--                                (aptitudes sociales, confiance, sécurité affective)
--
-- Avec ce dernier lot, les NEUF types d'activité du référentiel sont représentés
-- au moins une fois dans la démonstration, et les quatre précisions existantes
-- ont chacune servi : « encastrement dans des trous » et « dénombrement des
-- éléments » (jeu avec un jouet), « jeu chanté » (activité récréative) et
-- « empreinte de main » (activité psychosociale manuelle et artistique).
-- ============================================================================

INSERT INTO activites (user_id, seance_id, position, activite_type_id, activite_label, sous_type,
                       nb, avec_correction, objet, matiere, niveau, ton, texte_source, resultat,
                       statut, created_at, updated_at) VALUES

-- ══ Séance 13 — Bonjour, le rituel qui ouvre la journée ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 13, 1, 81, 'rituel collectif', NULL,
 NULL, false, 'Le regroupement du matin : qui est là, qui n''est pas là',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 'structure',
 'Fiches « Je suis là. Qui est là ? » et « Rituels et habitudes » du référentiel d''éveil 0-3 ans.',
 E'# Le regroupement du matin\n\n**Âge** : 12 à 36 mois · **Le groupe entier** · **10 minutes** · **Tous les jours, même heure, même ordre**\n\n## Ce que le rituel donne à l''enfant\nUn tout-petit ne sait pas ce qui va lui arriver dans la journée. Le regroupement lui donne cette information, tous les matins, sous la même forme. C''est un dispositif de sécurité affective — pas une politesse, pas un moment scolaire.\n\n## Le déroulé, invariable\n\n**1. La comptine d''appel.** Toujours la même, toujours dans le même ordre. Chaque enfant est nommé ; celui qui ne répond pas est nommé quand même. L''entendre suffit.\n\n**2. Les photos.** Une par enfant, posées une à une au centre. On dit qui est là.\n\n**3. Les absents.** « Naïm n''est pas là aujourd''hui, il revient demain. » On ne les escamote jamais : un enfant qui manque et dont personne ne parle apprend qu''on peut disparaître sans que ça se remarque.\n\n**4. Ce qui va se passer.** Trois étapes, pas plus, dans l''ordre, avec les mêmes mots : « on va jouer, puis on se lave les mains, puis on mange. »\n\n## Ce qu''on observe\n- Répond-il à son prénom, d''une façon ou d''une autre — un regard suffit ?\n- Regarde-t-il la photo de l''absent ? Va-t-il la chercher ?\n- Anticipe-t-il l''étape suivante avant qu''on la nomme ?\n\n## Ce qui abîme le rituel\nLe raccourcir un jour de retard — c''est précisément le jour où il sert le plus. Changer l''ordre. Le confier chaque jour à quelqu''un d''autre : la répétition inclut la voix.\n\n## Au bout de trois semaines\nLes enfants réclament la photo de celui qui manque. C''est le signe que le groupe existe pour eux comme un ensemble, et pas seulement comme un lieu.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 13, 2, 77, 'activité récréative', 'jeu chanté',
 NULL, false, 'La comptine d''appel, celle qui ne change jamais',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 'ludique',
 'Fiches « Nous allons… » et « Je suis là. Qui est là ? » du référentiel d''éveil 0-3 ans : anticipation, aptitudes sociales, estime de soi.',
 E'# La comptine d''appel\n\n**Âge** : 10 à 36 mois · **Le groupe** · **5 minutes** · **Aucun matériel**\n\n## Pourquoi une comptine et pas un appel\nLe chant porte mieux que la parole dans un groupe de tout-petits, il se mémorise sans effort, et il permet à l''enfant de savoir **quand vient son tour** : la mélodie annonce le prénom avant qu''il soit dit.\n\n## La forme\nQuatre mesures, une phrase, le prénom à la fin. Toujours la même mélodie, toujours le même ordre des enfants — celui du tour de cercle, pas une liste. L''enfant sait qu''il vient après son voisin.\n\n## Déroulé\n\n**On chante pour chacun**, son prénom à la fin, en le regardant. On attend une seconde après le prénom : certains répondent d''un geste, d''un son, d''un sourire.\n\n**On n''insiste jamais** sur celui qui ne répond pas. On chante, on regarde, on passe.\n\n**Les absents ont leur couplet** aussi : « et Naïm, il n''est pas là. » Cela dure trois secondes et cela change tout pour les enfants qui commencent à se compter.\n\n**On termine par le groupe entier** : une phrase où tout le monde est nommé ensemble.\n\n## Ce qu''on observe\n- Anticipe-t-il son tour ? Se redresse-t-il quand vient le voisin ?\n- Chante-t-il le prénom d''un autre ?\n- Réclame-t-il un couplet supplémentaire pour quelqu''un — souvent l''absent, souvent l''adulte ?\n\n## Le piège\nAccélérer parce que le repas attend. La comptine expédiée ne remplit plus sa fonction : ce n''est plus un rituel, c''est un appel. Mieux vaut la chanter à quatre enfants qu''à douze en vitesse.\n\n## Variante\nLa même comptine sert au départ du soir. La journée est alors bornée par deux fois le même chant, ce qui aide beaucoup les enfants qui ont du mal à se séparer.',
 'termine', now(), now()),

-- ══ Séance 14 — Le doudou, la référente, la séparation ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 14, 1, 80, 'échange individuel', NULL,
 NULL, false, 'L''accueil du matin, enfant par enfant',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 'classique',
 'Fiches « La familiarisation », « Les doudous et les tétines » et « La référence » du référentiel d''éveil 0-3 ans.',
 E'# L''accueil du matin, enfant par enfant\n\n**Âge** : 8 à 36 mois · **Un enfant et son parent** · **7 minutes** · **Toujours la même professionnelle**\n\n## Les trois appuis de la séparation\n\n**L''objet.** Le doudou est accessible à tout moment, dans un bac ouvert à hauteur d''enfant. Il n''est confisqué ni au repas, ni au jeu, ni parce qu''il est grand maintenant. C''est lui qui fait le lien entre la maison et ici.\n\n**La personne.** La même professionnelle accueille le même enfant, et l''accompagne au change, au repas et à l''endormissement. Ce n''est pas une préférence affective : c''est ce qui rend le lieu prévisible.\n\n**Le dire.** Le parent annonce son départ et part. Une sortie en cachette économise trois minutes de pleurs et coûte trois semaines de vigilance : l''enfant qui a vu son parent disparaître sans prévenir surveille la porte au lieu de jouer.\n\n## Déroulé\n\n**Le temps convenu (7 min).** Le parent reste la durée dont on a convenu ensemble, toujours la même — ni deux minutes, ni vingt selon l''humeur du jour.\n\n**Les transmissions se font devant l''enfant**, pas au-dessus de lui. Il entend qu''on parle de lui, et qu''il n''y a pas deux mondes séparés.\n\n**Le départ est annoncé et fait**, sans revenir sur ses pas. La professionnelle prend le relais physiquement : elle porte, ou elle tend la main.\n\n## Ce qu''on observe\n- Va-t-il chercher son doudou seul ?\n- Se laisse-t-il consoler par sa référente, ou par n''importe qui ?\n- Combien de temps entre le départ et le retour au jeu ? C''est l''indicateur qui compte, bien plus que l''intensité des pleurs.\n\n## Ce qu''on ne dit pas\n« Ce n''est rien. » « Tu es grand. » « Regarde, tes copains jouent. » On dit ce qui est : « maman est partie, elle revient après la sieste. » Les pleurs ont le droit de durer.\n\n## Aux retrouvailles\nOn raconte la journée en deux phrases, devant lui. Ce qui a été difficile est dit aussi — un accueil qui ne rapporte que du positif finit par ne plus être écouté.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 14, 2, 83, 'activité psychosociale de jeu, détente et confiance', NULL,
 NULL, false, 'Le coin refuge : un endroit pour se retirer sans partir',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 'concis',
 'Fiches « Objets transitionnels » et « Exercices de détente, de calme et de confort » du référentiel d''éveil 0-3 ans.',
 E'# Le coin refuge\n\n**Âge** : 8 à 36 mois · **Un ou deux enfants** · **Disponible toute la journée** · **Aucun adulte dedans**\n\n## À quoi il sert\nEn collectivité, un enfant ne peut jamais être seul. Le coin refuge lui rend cette possibilité **sans l''éloigner** : il voit le groupe, on le voit, mais il n''est plus dedans.\n\n## Comment il est fait\n\n- Bas, fermé sur deux ou trois côtés, ouvert sur le reste de la pièce.\n- Un coussin, une couverture, le bac à doudous à portée.\n- Les photos de famille plastifiées, à hauteur d''enfant, fixées à la paroi.\n- **Aucun jouet sonore, aucun jeu attirant** : ce n''est pas un coin de jeu, c''est un coin de retrait.\n\n## La règle des adultes\n\n**On n''y entre pas.** On s''accroupit devant, on parle de l''extérieur.\n\n**On n''y envoie personne.** Un coin refuge utilisé comme punition est perdu définitivement.\n\n**On n''en sort personne** tant qu''il n''y a pas de raison — repas, change, départ. Et alors on prévient et on attend.\n\n## Ce qu''on observe\n- Y va-t-il seul, et à quels moments de la journée ?\n- Emporte-t-il son doudou, ou le laisse-t-il ?\n- Regarde-t-il les photos de famille ? Certains les manipulent longuement en fin de matinée.\n- Combien de temps y reste-t-il avant de revenir de lui-même ?\n\n## Ce que cela évite\nBeaucoup de morsures et de conflits de fin de matinée : ce sont souvent des enfants saturés qui n''avaient nulle part où se retirer.\n\n## Ce qui se note en équipe\nUn enfant qui y passe la moitié de la journée n''utilise plus un refuge : il s''isole. Cela se dit, cela s''observe sur plusieurs jours, et cela peut se transmettre aux parents — comme une observation, jamais comme un diagnostic.',
 'termine', now(), now()),

-- ══ Séance 15 — Faire une place à l'autre ══
((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 15, 1, 82, 'activité psychosociale manuelle et artistique', NULL,
 NULL, false, 'Le dessin de groupe : côte à côte sur la même feuille',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 'ludique',
 'Fiches « Dessin de groupe » et « Dessin libre » du référentiel d''éveil 0-3 ans.',
 E'# Le dessin de groupe\n\n**Âge** : 20 à 36 mois · **Quatre enfants** · **12 minutes** · **Une seule feuille pour tous**\n\n## Ce qu''on ne demande pas\nDe faire un dessin ensemble. Avant trois ans, les enfants jouent **côte à côte**, pas ensemble — c''est l''âge du jeu parallèle, et vouloir le brusquer produit des conflits, pas de la coopération.\n\n## Ce qu''on demande\nD''être là en même temps, sur la même feuille, chacun dans sa zone. La rencontre se fait toute seule quand deux tracés se croisent — et c''est ce moment-là qu''on nomme.\n\n## Installation\nUne grande feuille au sol, quatre coins, un enfant par coin. Des crayons en nombre suffisant : quatre enfants, seize crayons. Le manque de matériel ne crée pas du partage, il crée de l''arrachage.\n\n## Déroulé\n\n**Chacun chez soi (6 min).** Ils tracent dans leur coin. L''adulte nomme les zones : « toi tu es là, et Lina est de ce côté. »\n\n**Les tracés se croisent (4 min).** Quelqu''un déborde. On ne l''arrête pas ; on le dit : « ton trait est allé jusque chez Sofia. » Souvent, l''autre répond en traçant par-dessus. C''est le premier échange graphique, et il vaut d''être vu.\n\n**On regarde ensemble (2 min).** Debout au-dessus. On montre où chacun était, et où ça s''est rencontré.\n\n## Ce qu''on observe\n- Regarde-t-il ce que fait son voisin ? Reprend-il son geste ?\n- Accepte-t-il qu''un autre trace près de lui ?\n- Réagit-il quand on trace sur son tracé — retrait, protestation, réponse ?\n\n## Le conflit qui arrive\nUn enfant recouvre la production d''un autre. On ne gronde pas, on nomme : « il a mis du bleu sur ton trait, ça ne te va pas. » Puis on propose une feuille séparée si c''est trop dur aujourd''hui. Ce sera possible dans un mois.\n\n## Après\nLa feuille est affichée entière, avec les quatre prénoms écrits à côté de leurs zones respectives. On ne la découpe pas en quatre.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.creche@aschool.fr'), 15, 2, 83, 'activité psychosociale de jeu, détente et confiance', NULL,
 NULL, false, 'Le massage des mains, sur accord de chacun',
 'Aptitudes sociales, confiance et sécurité affective', 'Moyens-Grands (1-3 ans)', 'classique',
 'Fiches « Exercices de détente, de calme et de confort » et « Réseau de liens » du référentiel d''éveil 0-3 ans.',
 E'# Le massage des mains\n\n**Âge** : 14 à 36 mois · **Quatre enfants** · **8 minutes** · **Assis en cercle, lumière baissée**\n\n## Ce qui s''apprend ici\nDemander avant de toucher, et accepter un refus. C''est l''apprentissage social le plus important de cette séquence, et il passe par un geste très concret, répété chaque semaine.\n\n## Déroulé\n\n**1. Ses propres mains (3 min).** Chacun masse ses mains à lui : la paume, chaque doigt, le dos de la main. L''adulte fait en même temps et nomme les parties. Personne ne touche personne — c''est le point d''entrée, et pour certains enfants ce sera toute la séance.\n\n**2. La demande (1 min).** « Est-ce que je peux prendre ta main ? » L''adulte demande à un enfant, attend, et **s''arrête si la réponse est non** — sans commentaire, sans « mais si », sans insister une seconde fois.\n\n**3. À deux (4 min).** Ceux qui veulent se mettent par deux. Chacun demande avant. L''adulte reste disponible pour ceux qui restent seuls : rester seul est une option, pas un échec.\n\n## Ce qu''on observe\n- L''enfant demande-t-il avant de toucher, même maladroitement — un regard, une main tendue ?\n- Accepte-t-il un refus, ou insiste-t-il ?\n- Refuse-t-il lui-même ? Savoir dire non est un acquis, pas une opposition.\n\n## Pourquoi l''adulte demande à voix haute\nParce que c''est le modèle. Un adulte qui prend la main d''un enfant sans prévenir, cent fois par jour, enseigne exactement le contraire de ce que la séance vise.\n\n## Ce qui se transpose ailleurs\nLa même formule au change, au mouchage, à l''habillage : « je vais te prendre dans les bras, d''accord ? » On ne demande pas la permission d''un soin nécessaire, mais on l''annonce et on attend une seconde. Cette seconde-là est le cœur du métier.',
 'termine', now(), now());
