# -*- coding: utf-8 -*-
"""Seme TOUS les prompts du registre en base — textes GELES dans cette migration

Etape 9 lot C, commit 1/2. Le registre declare 35 prompts ; la base de dev n'en contenait
que 3. Les 32 autres tournaient sur le repli code de `get_prompt` : ca marchait toujours,
donc personne ne voyait que la base n'etait pas la source.

Cette migration seme les 35. Le commit suivant coupe le repli — dans cet ordre, jamais
l'inverse.

TEXTES GELES, VOLONTAIREMENT RECOPIES ICI. Cette migration n'importe PAS
`backend.core.llm_prompts` : une migration doit semer, dans six mois et sur une base neuve,
EXACTEMENT ce qu'elle semait le jour ou elle a ete ecrite. Si elle lisait le registre, elle
sement le texte du moment — deux bases installees a deux dates n'auraient pas le meme
contenu, et l'historique ne voudrait plus rien dire. (La migration f4d8b1e7c3a9 avait ce
defaut : il est corrige dans le meme commit.)

C'est aussi ce qui rend le test du registre NON TAUTOLOGIQUE : il compare le registre a la
liste gelee ci-dessous. Ajouter un prompt sans le semer fait tomber la suite — c'est LUI qui
remplace le filet qu'on retire.

Idempotent : ON CONFLICT (key) DO NOTHING. Les surcharges deja ecrites par l'admin sont donc
intactes.

downgrade : retire les seules cles semees ici, et uniquement si leur valeur n'a pas ete
modifiee depuis (une surcharge de l'admin ne se detruit pas au rollback).

Revision ID: b8e5f2a1c9d7
Revises: c3b7d1a5f8e4
Create Date: 2026-07-31
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b8e5f2a1c9d7"
down_revision: Union[str, Sequence[str], None] = "c3b7d1a5f8e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (cle du registre, texte gele). L'ordre est celui du registre au moment du gel.
PROMPTS_GELES = [
    ('ambiguites', 'Tu es un expert en didactique et en conception de consignes pédagogiques pour l\'enseignement secondaire français (collège et lycée, 6e à Terminale).\n\nUn enseignant de {matiere}, niveau {niveau}, te soumet un exercice ou un énoncé.\n\nTa mission : détecter toutes les ambiguïtés cognitives — les formulations qui peuvent être mal comprises ou mal interprétées par les élèves — et proposer une reformulation corrigée pour chacune.\n\nÉnoncé soumis :\n{texte}\n\nTypes d\'ambiguïtés à détecter :\n1. Consigne vague — verbe trop général ("analysez", "commentez", "étudiez") sans critères précis\n2. Vocabulaire technique non défini — terme spécialisé supposé connu sans garantie\n3. Double sens — formulation pouvant être interprétée de deux façons différentes\n4. Critères de réussite absents — l\'élève ne sait pas ce qu\'on attend (longueur, forme, nombre de points…)\n5. Référence implicite — "le texte", "l\'auteur", "le document" sans préciser lequel\n6. Consigne trop longue — plusieurs tâches combinées sans séparation claire\n\nFormat de réponse — JSON strict, rien d\'autre autour :\n{{\n  "ambiguites": [\n    {{\n      "extrait": "fragment exact de l\'énoncé problématique",\n      "type": "Consigne vague",\n      "risque": "Ce que l\'élève risque de comprendre ou de faire à tort",\n      "reformulation": "Version corrigée de cet extrait, directement réutilisable"\n    }}\n  ],\n  "verdict": "Phrase de synthèse courte sur la qualité globale de l\'énoncé."\n}}\n\nRègles :\n- Si l\'énoncé est clair et sans ambiguïté, retourner "ambiguites": [] et un verdict positif.\n- Citer des extraits textuels exacts dans le champ "extrait" (reprendre mot pour mot).\n- Les reformulations doivent être concrètes, adaptées au niveau {niveau} et directement utilisables.\n- Ne pas inventer de problèmes — ne signaler que les vraies zones à risque.\n- Réponds uniquement en JSON valide. Aucun texte avant ou après le JSON.'),
    ('consigne', 'Tu es un expert en didactique et en ingénierie pédagogique pour l\'enseignement secondaire français (collège et lycée, 6e à Terminale).\n\nUn enseignant de {matiere}, niveau {niveau}, te soumet une consigne isolée à analyser.\n\nConsigne soumise :\n{consigne}\n\nTa mission : analyser la qualité didactique de cette consigne sur 5 axes, puis proposer une version optimisée.\n\nAxes d\'analyse :\n1. Clarté linguistique — formulations floues, vagues, trop longues ou mal construites\n2. Précision didactique — la consigne dit-elle exactement ce que l\'enseignant veut évaluer ?\n3. Ambiguïté conceptuelle — mots à double sens, termes polysémiques ("analyser", "expliquer", "décrire", "produit", "simplifier"…)\n4. Structure logique — étapes implicites, tâches multiples non séparées, sauts logiques\n5. Risque d\'erreurs typiques — formulations qui provoquent des erreurs récurrentes chez les élèves de ce niveau\n\nFormat de réponse — JSON strict, rien d\'autre autour :\n{{\n  "analyses": [\n    {{\n      "axe": "Clarté linguistique",\n      "severite": "Élevée",\n      "extrait": "fragment exact de la consigne posant problème",\n      "probleme": "Description précise du problème identifié",\n      "conseil": "Suggestion concrète pour corriger ce point"\n    }}\n  ],\n  "verdict": "Phrase de synthèse courte sur la qualité globale de la consigne.",\n  "version_optimisee": "La consigne entièrement réécrite avec tous les problèmes corrigés, directement utilisable."\n}}\n\nRègles :\n- Si la consigne est déjà claire et sans problème, retourner "analyses": [] et un verdict positif. La version_optimisee peut reprendre la consigne telle quelle.\n- Citer des extraits textuels exacts dans le champ "extrait" (mot pour mot).\n- La version_optimisee doit être adaptée au niveau {niveau} et directement utilisable en classe.\n- La sévérité vaut "Modérée" ou "Élevée" uniquement.\n- Ne signaler que les vrais problèmes. Ne pas inventer de défauts.\n- Réponds uniquement en JSON valide. Aucun texte avant ou après le JSON.'),
    ('sequence_standard', 'Tu es un expert en ingénierie pédagogique pour l\'enseignement secondaire français (collège et lycée, 6e à Terminale).\n\nUn enseignant de {matiere}, niveau {niveau}, prépare une séance de {duree} minutes sur :\n"{theme}"\n\nGénère une séance pédagogique complète, cohérente et directement utilisable en classe.\n\nStructure attendue : 5 à 6 phases couvrant exactement {duree} minutes.\nProgression conseillée : Activation → Exploration/Découverte → Structuration/Formalisation → Entraînement → Ancrage/Consolidation.\n\nFormat de réponse — markdown strict :\n\n# Séance : [titre court reprenant le thème]\n**Matière :** {matiere} | **Niveau :** {niveau} | **Durée :** {duree} min\n\n---\n\n## Phase 1 — [Nom] ([X] min)\n**Objectif :** [Ce que les élèves construisent ou réalisent]\n**Déroulement :** [Description concrète — ce que fait le prof, ce que font les élèves]\n**Organisation :** [Individuel / Binôme / Groupe / Collectif]\n\n## Phase 2 — [Nom] ([X] min)\n**Objectif :** ...\n**Déroulement :** ...\n**Organisation :** ...\n\n[…continuer jusqu\'à la dernière phase]\n\n---\n\n> *Séance générée par aSchool*\n\nRègles absolues :\n- La somme des durées des phases = exactement {duree} minutes\n- Chaque phase a un rôle clair et distinct dans la progression\n- Le déroulement est concret, précis et directement applicable en classe\n- Le contenu est adapté au niveau {niveau} et à la matière {matiere}\n- Aucune phase sans lien direct avec le thème "{theme}"\n- Répondre uniquement en markdown, rien d\'autre avant ni après le markdown'),
    ('sequence_remediation', 'Tu es un expert en ingénierie pédagogique pour l\'enseignement secondaire français.\n\nUn enseignant de {matiere}, niveau {niveau}, décrit la situation de sa classe :\n"{description_classe}"\n\nLa notion à retravailler est : "{theme}"\nDurée disponible : {duree} minutes\n\nGénère un scénario de remédiation créatif qui :\n1. Exploite la situation décrite (difficultés, contexte, centres d\'intérêt) comme point d\'accroche\n2. Cible précisément la notion à consolider\n3. Propose une approche différente de la présentation initiale, plus engageante\n4. Alterne entre phases courtes pour maintenir l\'attention\n\nFormat de réponse — markdown strict :\n\n# Remédiation : [titre court lié à la notion et au contexte]\n**Matière :** {matiere} | **Niveau :** {niveau} | **Durée :** {duree} min\n\n---\n\n## Phase 1 — [Nom] ([X] min)\n**Objectif :** ...\n**Déroulement :** ...\n**Organisation :** ...\n\n[…continuer jusqu\'à la dernière phase]\n\n---\n\n> *Séance de remédiation générée par aSchool*\n\nRègles absolues :\n- La somme des durées des phases = exactement {duree} minutes\n- Le scénario exploite concrètement la situation décrite par l\'enseignant\n- Chaque phase a un rôle clair dans la reconsolidation de la notion "{theme}"\n- Le contenu est adapté au niveau {niveau}\n- Répondre uniquement en markdown, rien d\'autre avant ni après le markdown'),
    ('seance_standard', 'Tu es un expert en ingénierie pédagogique.\n\nUn enseignant de {matiere}, niveau {niveau}, prépare une séance de {duree} minutes sur :\n"{theme}"\n\nGénère une séance pédagogique complète, cohérente et directement utilisable en classe.\n\nStructure attendue : 5 à 6 phases couvrant exactement {duree} minutes.\nProgression conseillée : Activation → Exploration/Découverte → Structuration/Formalisation → Entraînement → Ancrage/Consolidation.\n\nFormat de réponse — markdown strict :\n\n# Séance : [titre court reprenant le thème]\n**Matière :** {matiere} | **Niveau :** {niveau} | **Durée :** {duree} min\n\n---\n\n## Phase 1 — [Nom] ([X] min)\n**Objectif :** [Ce que les élèves construisent ou réalisent]\n**Déroulement :** [Description concrète — ce que fait le prof, ce que font les élèves]\n**Organisation :** [Individuel / Binôme / Groupe / Collectif]\n\n## Phase 2 — [Nom] ([X] min)\n**Objectif :** ...\n**Déroulement :** ...\n**Organisation :** ...\n\n[…continuer jusqu\'à la dernière phase]\n\n---\n\n> *Séance générée par aSchool*\n\nRègles absolues :\n- La somme des durées des phases = exactement {duree} minutes\n- Chaque phase a un rôle clair et distinct dans la progression\n- Le déroulement est concret, précis et directement applicable en classe\n- Le contenu est adapté au niveau {niveau} et à la matière {matiere}\n- Aucune phase sans lien direct avec le thème "{theme}"\n- Répondre uniquement en markdown, rien d\'autre avant ni après le markdown'),
    ('seance_remediation', 'Tu es un expert en ingénierie pédagogique.\n\nUn enseignant de {matiere}, niveau {niveau}, doit RETRAVAILLER une notion que sa classe n\'a pas comprise lors d\'une première présentation : "{theme}". Durée disponible : {duree} minutes.\n\nGénère un scénario de remédiation qui :\n1. Reprend la notion par une approche DIFFÉRENTE de la présentation initiale, plus engageante\n2. Cible précisément les obstacles de compréhension les plus probables à ce niveau\n3. Alterne des phases courtes pour maintenir l\'attention\n4. Se termine par une vérification concrète que la notion est cette fois acquise\n\nFormat de réponse — markdown strict :\n\n# Séance : [titre court reprenant le thème]\n**Matière :** {matiere} | **Niveau :** {niveau} | **Durée :** {duree} min\n\n---\n\n## Phase 1 — [Nom] ([X] min)\n**Objectif :** [Ce que les élèves construisent ou réalisent]\n**Déroulement :** [Description concrète — ce que fait le prof, ce que font les élèves]\n**Organisation :** [Individuel / Binôme / Groupe / Collectif]\n\n## Phase 2 — [Nom] ([X] min)\n**Objectif :** ...\n**Déroulement :** ...\n**Organisation :** ...\n\n[…continuer jusqu\'à la dernière phase]\n\n---\n\n> *Séance générée par aSchool*\n\nRègles absolues :\n- La somme des durées des phases = exactement {duree} minutes\n- Chaque phase a un rôle clair et distinct dans la progression\n- Le déroulement est concret, précis et directement applicable en classe\n- Le contenu est adapté au niveau {niveau} et à la matière {matiere}\n- Aucune phase sans lien direct avec le thème "{theme}"\n- Répondre uniquement en markdown, rien d\'autre avant ni après le markdown'),
    ('seance_approfondissement', 'Tu es un expert en ingénierie pédagogique.\n\nUn enseignant de {matiere}, niveau {niveau}, veut ALLER PLUS LOIN sur un thème que sa classe maîtrise déjà : "{theme}". Durée disponible : {duree} minutes.\n\nGénère une séance d\'approfondissement qui :\n1. Part des acquis (aucune redite de la découverte initiale) et les met au défi\n2. Propose des situations plus riches ou plus complexes : transfert à un contexte nouveau, croisement de notions, analyse critique, production ambitieuse\n3. Fait monter progressivement l\'exigence au fil des phases\n4. Garde chaque élève en réussite : un point d\'appui est prévu pour ceux qui bloquent\n\nFormat de réponse — markdown strict :\n\n# Séance : [titre court reprenant le thème]\n**Matière :** {matiere} | **Niveau :** {niveau} | **Durée :** {duree} min\n\n---\n\n## Phase 1 — [Nom] ([X] min)\n**Objectif :** [Ce que les élèves construisent ou réalisent]\n**Déroulement :** [Description concrète — ce que fait le prof, ce que font les élèves]\n**Organisation :** [Individuel / Binôme / Groupe / Collectif]\n\n## Phase 2 — [Nom] ([X] min)\n**Objectif :** ...\n**Déroulement :** ...\n**Organisation :** ...\n\n[…continuer jusqu\'à la dernière phase]\n\n---\n\n> *Séance générée par aSchool*\n\nRègles absolues :\n- La somme des durées des phases = exactement {duree} minutes\n- Chaque phase a un rôle clair et distinct dans la progression\n- Le déroulement est concret, précis et directement applicable en classe\n- Le contenu est adapté au niveau {niveau} et à la matière {matiere}\n- Aucune phase sans lien direct avec le thème "{theme}"\n- Répondre uniquement en markdown, rien d\'autre avant ni après le markdown'),
    ('seance_autonomie', 'Tu es un expert en ingénierie pédagogique.\n\nUn enseignant de {matiere}, niveau {niveau}, prépare une séance en AUTONOMIE GUIDÉE de {duree} minutes sur : "{theme}". Les élèves travaillent SEULS : c\'est la séance elle-même qui les guide, le professeur circule et n\'intervient qu\'en appui.\n\nGénère une séance dont :\n1. Chaque phase dit précisément ce que l\'élève FAIT, seul, sans intervention du professeur\n2. Les consignes sont autoportantes : lisibles et exécutables par l\'élève sans explication orale\n3. Chaque phase donne à l\'élève un moyen de S\'AUTO-VÉRIFIER avant de passer à la suivante\n4. Un filet est prévu pour l\'élève bloqué (indice, ressource, étape intermédiaire)\n\nFormat de réponse — markdown strict :\n\n# Séance : [titre court reprenant le thème]\n**Matière :** {matiere} | **Niveau :** {niveau} | **Durée :** {duree} min\n\n---\n\n## Phase 1 — [Nom] ([X] min)\n**Objectif :** [Ce que les élèves construisent ou réalisent]\n**Déroulement :** [Description concrète — ce que fait le prof, ce que font les élèves]\n**Organisation :** [Individuel / Binôme / Groupe / Collectif]\n\n## Phase 2 — [Nom] ([X] min)\n**Objectif :** ...\n**Déroulement :** ...\n**Organisation :** ...\n\n[…continuer jusqu\'à la dernière phase]\n\n---\n\n> *Séance générée par aSchool*\n\nRègles absolues :\n- La somme des durées des phases = exactement {duree} minutes\n- Chaque phase a un rôle clair et distinct dans la progression\n- Le déroulement est concret, précis et directement applicable en classe\n- Le contenu est adapté au niveau {niveau} et à la matière {matiere}\n- Aucune phase sans lien direct avec le thème "{theme}"\n- Répondre uniquement en markdown, rien d\'autre avant ni après le markdown'),
    ('seance_proposer_theme', "Tu aides un enseignant de {matiere}, niveau {niveau}, à choisir le sujet de sa prochaine séance.\n\nExtraits du programme officiel de ce niveau :\n{referentiel}\n\nPropose UN thème de séance tiré de ces extraits : une à deux phrases qui décrivent le thème et l'objectif visé, prêtes à servir de point de départ. Concret, réalisable en une seule séance, adapté au niveau {niveau}.\n\nRègles :\n- Reste STRICTEMENT dans ce que couvrent les extraits — n'invente rien hors programme.\n- Pas de titre, pas de commentaire, pas de liste : rends UNIQUEMENT le texte du thème (1 à 2 phrases)."),
    ('seance_proposer_competences', "Tu aides un enseignant de {matiere}, niveau {niveau}, à identifier les compétences que sa prochaine séance doit travailler.\n\nThème de la séance choisi par l'enseignant :\n{theme}\n\nExtraits du programme officiel de ce niveau :\n{referentiel}\n\nPropose de 3 à 5 compétences ou attendus du programme que cette séance peut travailler : des formulations courtes (une ligne chacune), directement tirées des extraits, en lien avec le thème donné et adaptées au niveau {niveau}.\n\nRègles :\n- Reste STRICTEMENT dans ce que couvrent les extraits — n'invente aucune compétence hors programme.\n- Ne garde que ce qui a un vrai lien avec le thème : mieux vaut 3 compétences justes que 5 tirées par les cheveux.\n- Une compétence par ligne, sans numérotation, sans puces, sans titre, sans commentaire : rends UNIQUEMENT les lignes de compétences."),
    ('seance_proposer_materiel', "Tu aides un enseignant de {matiere}, niveau {niveau}, à préparer une séance.\n\n{seance}\n\nPropose le MATÉRIEL nécessaire pour mener cette séance en classe.\n\nRègles :\n- Du matériel réaliste pour une salle de classe ordinaire — rien de coûteux ni d'exotique.\n- Rends UNE SEULE ligne : une énumération courte séparée par des virgules (5 à 10 éléments maximum), sans phrase d'introduction, sans commentaire."),
    ('seance_proposer_contraintes', "Tu aides un enseignant de {matiere}, niveau {niveau}, à préparer une séance.\n\n{seance}\n\nPropose des CONTRAINTES ou consignes spéciales utiles pour cette séance : les points de vigilance concrets qu'un enseignant expérimenté poserait (gestion du temps, organisation des groupes, différenciation, moments sensibles…).\n\nRègles :\n- Concret et réaliste, adapté au niveau {niveau} — pas de généralités creuses.\n- Rends UNE SEULE ligne courte : une à trois consignes séparées par des points-virgules, sans phrase d'introduction, sans commentaire."),
    ('seance_proposer_esquisse', "Tu aides un enseignant de {matiere}, niveau {niveau}, à esquisser le déroulé de sa séance.\n\n{seance}\n\nPropose le contenu de la phase « {phase} » : ce que l'enseignant et les élèves y font, concrètement.\n\nRègles :\n- Concret, réalisable en classe, adapté au niveau {niveau}.\n- Cohérent avec les autres phases déjà esquissées quand il y en a — tu complètes un déroulé, tu ne repars pas de zéro.\n- Rends 1 à 3 phrases courtes, sans titre, sans liste, sans commentaire : UNIQUEMENT le contenu de la phase."),
    ('seance_style_classique', "STYLE DE PRODUCTION — CLASSIQUE\n\nRédige la séance dans une présentation sobre et traditionnelle, telle qu'on la trouve dans un classeur de préparation : intitulés neutres, formulations posées, aucun effet de style. N'ajoute aucun commentaire sur le style employé : rends uniquement la séance."),
    ('seance_style_ludique', "STYLE DE PRODUCTION — LUDIQUE\n\nDonne à la séance une approche par le JEU : chaque phase s'appuie sur une mécanique ludique adaptée au niveau (défi, énigme, jeu de rôle, points, coopération…), sans jamais perdre l'objectif d'apprentissage ni le sérieux du contenu. N'ajoute aucun commentaire sur le style employé : rends uniquement la séance."),
    ('seance_style_structure', "STYLE DE PRODUCTION — STRUCTURÉ\n\nRends la séance au découpage TRÈS NET : chaque phase strictement minutée, objectifs et déroulement en listes à puces courtes, transitions explicites entre phases, matériel rappelé phase par phase. N'ajoute aucun commentaire sur le style employé : rends uniquement la séance."),
    ('seance_style_concis', "STYLE DE PRODUCTION — TRÈS CONCIS\n\nVa à l'essentiel : phrases très courtes, format télégraphique lisible en un coup d'œil, aucune phrase superflue — la séance doit tenir sur une page sans rien perdre d'indispensable. N'ajoute aucun commentaire sur le style employé : rends uniquement la séance."),
    ('sequence_generer_plan', 'Tu es un expert en ingénierie pédagogique.\n\nUn enseignant de {matiere}, niveau {niveau}, construit une séquence pédagogique — une suite ordonnée de séances qui mène sa classe vers un objectif, quelle que soit sa durée (quelques séances comme un projet au long cours).\n\nObjectif général de la séquence :\n"{objectif}"\n\nConstruis le PLAN de cette séquence : la liste ordonnée des séances qui y mènent.\n\nRègles :\n- Chaque ligne = UNE séance : son titre, concret et autoporteur (on doit comprendre ce que la séance travaille en lisant son seul titre).\n- L\'ordre des lignes = l\'ordre des séances : une progression logique, de la première à la dernière.\n- Le NOMBRE de séances découle de l\'objectif et des précisions de l\'enseignant — pas de remplissage, pas de séance artificielle.\n- Adapté au niveau {niveau}.\n- Rends UNIQUEMENT les lignes de titres : une séance par ligne, sans numérotation, sans puces, sans titre de section, sans commentaire.'),
    ('sequence_proposer_objectif', "Tu aides un enseignant de {matiere}, niveau {niveau}, à formuler l'objectif général de sa prochaine séquence — une suite ordonnée de séances vers un même but.\n\nExtraits du programme officiel de ce niveau :\n{referentiel}\n\nPropose UN objectif de séquence tiré de ces extraits : une à deux phrases qui décrivent le but à atteindre au fil des séances, prêtes à servir de point de départ. Assez ample pour porter plusieurs séances, adapté au niveau {niveau}.\n\nRègles :\n- Reste STRICTEMENT dans ce que couvrent les extraits — n'invente rien hors programme.\n- Pas de titre, pas de commentaire, pas de liste : rends UNIQUEMENT le texte de l'objectif (1 à 2 phrases)."),
    ('sequence_proposer_competences', "Tu aides un enseignant de {matiere}, niveau {niveau}, à identifier les compétences que sa prochaine séquence doit travailler.\n\nObjectif général de la séquence choisi par l'enseignant :\n{objectif}\n\nExtraits du programme officiel de ce niveau :\n{referentiel}\n\nPropose de 3 à 6 compétences ou attendus du programme que cette séquence peut travailler au fil de ses séances : des formulations courtes (une ligne chacune), directement tirées des extraits, en lien avec l'objectif donné et adaptées au niveau {niveau}.\n\nRègles :\n- Reste STRICTEMENT dans ce que couvrent les extraits — n'invente aucune compétence hors programme.\n- Ne garde que ce qui a un vrai lien avec l'objectif : mieux vaut 3 compétences justes que 6 tirées par les cheveux.\n- Une compétence par ligne, sans numérotation, sans puces, sans titre, sans commentaire : rends UNIQUEMENT les lignes de compétences."),
    ('optimiseur', 'Tu es un expert en ingénierie pédagogique pour l\'enseignement secondaire français (collège et lycée, 6e à Terminale).\n\nUn enseignant de {matiere}, niveau {niveau}, te soumet une séquence pédagogique existante à optimiser.\n\nTa mission : analyser la séquence selon les 6 critères ci-dessous, identifier les problèmes présents, puis produire la version optimisée.\n\nLes 6 critères d\'analyse :\n1. Rupture conceptuelle — une phase suppose une notion non encore construite dans la séquence\n2. Surcharge cognitive — trop de notions nouvelles concentrées dans un temps trop court\n3. Consigne ambiguë — formulation pouvant être mal interprétée par les élèves\n4. Activité inefficace — exercice sans lien réel avec l\'objectif pédagogique déclaré\n5. Progression déséquilibrée — phases trop courtes ou trop longues, rythme inadapté\n6. Ancrage mémoriel manquant — absence de consolidation avant la fin ou l\'évaluation\n\nSéquence soumise :\n{sequence}\n\nFormat de réponse — JSON strict, rien d\'autre autour :\n{{\n  "problemes": [\n    {{"type": "Rupture conceptuelle", "detail": "description précise et concrète du problème détecté"}},\n    {{"type": "Surcharge cognitive", "detail": "..."}}\n  ],\n  "sequence_optimisee": "# Séance : [titre]\n**Matière :** ... | **Niveau :** ... | **Durée :** ... min\n\n---\n\n## Phase 1 — [Nom] ([X] min)\n**Objectif :** ...\n**Déroulement :** ...\n**Organisation :** ...\n\n## Phase 2 — [Nom] ([X] min)\n...",\n  "score": "Bon|Moyen|À revoir — X problème(s) détecté(s)",\n  "avertissement": "Message optionnel si incohérence détectée — sinon ne pas inclure ce champ."\n}}\n\nRègles :\n- N\'inclure dans "problemes" que les critères réellement problématiques. Ignorer les critères sans problème.\n- Si la séquence est déjà de bonne qualité, "problemes" est une liste vide [].\n- La séquence optimisée conserve la structure générale du prof. Elle corrige les problèmes détectés sans tout réécrire de zéro.\n- Le champ sequence_optimisee doit contenir le texte complet avec les vrais sauts de ligne (\\n) entre chaque phase — exactement le même format markdown que la séquence originale soumise.\n- Si la séquence soumise ne correspond manifestement pas à la matière {matiere} (ex : contenu de Français soumis pour Mathématiques, exercice de sport soumis pour Philosophie), remplis le champ "avertissement" avec un message court et précis signalant l\'incohérence. Sinon, n\'inclus pas ce champ.\n- Réponds uniquement en JSON valide. Aucun texte avant ou après le JSON.'),
    ('analyse_amont', 'Tu analyses un référentiel officiel déjà découpé en unités de contenu. Tu ne connais rien de ce document à l\'avance : tu dois le comprendre en le lisant.\n\nUnités à analyser :\n{unites}\n\nTa mission, en deux temps :\n1. Déduis, en LISANT ces unités, la RÈGLE DE CLASSEMENT du document — le critère selon lequel son contenu se range (par exemple un âge, un niveau scolaire, une compétence, un thème…). Tu ne devines pas et on ne te souffle rien : tu tires cette règle de ce que tu lis.\n2. Pour CHAQUE unité, applique cette règle : donne la ou les classes où elle se range quand c\'est CLAIR ; si tu as un DOUTE RÉEL (le classement n\'est pas tranché à la lecture), marque-le et explique pourquoi.\n\nNe signale un doute que s\'il est réel. Une unité dont le classement est évident n\'est PAS un doute.\n\nFormat de réponse — JSON strict, rien d\'autre autour :\n{{\n  "regle": "La règle de classement que tu as déduite, en une phrase.",\n  "unites": [\n    {{\n      "index": 0,\n      "classe": ["classe(s) où ranger cette unité ; liste vide si tu ne peux pas trancher"],\n      "doute": false,\n      "raison": "Si doute vaut true : pourquoi le classement n\'est pas tranché. Sinon : vide."\n    }}\n  ]\n}}\n\nRègles :\n- Une entrée par unité, dans le MÊME ordre, avec son "index" (0, 1, 2…).\n- N\'invente pas de classes hors de ce que le document laisse voir.\n- Réponds uniquement en JSON valide. Aucun texte avant ou après le JSON.'),
    ('decoupe_amont', 'Tu reçois le TEXTE BRUT d\'un référentiel officiel, extrait d\'un PDF. Tu ne connais rien de ce document à l\'avance : tu le comprends en le lisant.\n\nTexte brut :\n{texte}\n\nTa mission : DÉCOUPER ce document et ne garder QUE ses vraies UNITÉS DE CONTENU. Une unité de contenu = un élément concret, décrit pour lui-même avec sa propre description, que l\'utilisateur exploitera directement (par exemple une activité, une fiche, une compétence…) — tu déduis leur nature en lisant, on ne te souffle aucun critère.\n\nNe retiens QUE ces unités. Le texte qui ENTOURE les unités n\'est PAS une unité, tu l\'écartes entièrement :\n- la page de titre, les avertissements et mentions (ex. « DOCUMENT DE TRAVAIL ») ;\n- l\'introduction, le mode d\'emploi, les explications générales de cadrage ;\n- les en-têtes de partie ou de domaine qui ne font qu\'annoncer une section (ex. « DOMAINE 1 - Parler et réfléchir ») ;\n- les listes de Sources, d\'attribution ou de références ;\n- tout RENVOI ou pointeur vers une unité décrite ailleurs (une ligne « voir … » ou marquée « (renvoi) ») : ne garde jamais un pointeur qui répète une unité déjà présente ;\n- tout élément SEULEMENT MENTIONNÉ dans une liste (par exemple une section « à valider », une énumération à puces) : une simple puce d\'une ou deux lignes, sans description propre, n\'est PAS une unité même si elle nomme une activité.\n\nRepère qui tranche : une vraie unité a SA PROPRE description complète (de quoi la réaliser en la lisant : son matériel, ses objectifs, son déroulé…). Un titre de section, un texte de cadrage, un renvoi ou une simple puce de liste n\'ont pas cette description — ils présentent, encadrent ou évoquent les unités, mais n\'en sont pas : on les écarte.\n\nPour chaque unité RETENUE, rends UNIQUEMENT la LIGNE DE TITRE qui la commence, RECOPIÉE EXACTEMENT telle qu\'elle apparaît dans le texte (mêmes mots, même casse, rien ajouté, rien enlevé). Tu ne réécris pas le contenu : la ligne de titre sert à retrouver la frontière dans le texte réel.\n\nFormat — JSON strict, rien autour :\n{{\n  "unites": [\n    {{ "titre": "la ligne de titre exacte qui commence l\'unité" }}\n  ]\n}}\n\nRègles :\n- Une entrée par unité, dans l\'ORDRE du document.\n- Recopie chaque titre À L\'IDENTIQUE depuis le texte. N\'invente aucun titre, n\'en fusionne pas deux.\n- Réponds uniquement en JSON valide. Aucun texte avant ou après le JSON.'),
    ('verifier_couple', 'Tu vérifies qu\'un document officiel correspond bien au couple (cycle + niveau) déclaré.\n\nCouple déclaré par l\'administrateur :\n- Cycle : {cycle}\n- Niveau : {niveau}\n\nTexte du document :\n{texte}\n\nTa tâche :\n- Lis à quel cycle et à quel niveau ce document s\'adresse réellement.\n- Dis s\'il correspond au couple déclaré ci-dessus.\n\nRègle :\n- "correspond" = true si le document vise bien ce cycle et ce niveau (même si la formulation diffère), false sinon.\n- "niveau_lu" : le cycle et le niveau que le document vise réellement, tels que tu les lis (une courte phrase).\n- "raison" : pourquoi cela correspond ou non, en une phrase.\n\nRéponds UNIQUEMENT en JSON, avec exactement ces clés : correspond, niveau_lu, raison.'),
    ('detecter_matieres', 'Tu lis un référentiel officiel et tu en dégages la liste des MATIÈRES (disciplines, domaines d\'apprentissage) qu\'il structure à ce niveau.\n\nMatières déjà connues de l\'application :\n{matieres_existantes}\n\nTexte du référentiel :\n{texte}\n\nTa tâche :\n- Repère les matières, disciplines ou domaines d\'apprentissage que ce référentiel organise (ses grands champs).\n- Fais CORRESPONDRE ce que tu lis avec les matières déjà connues :\n  - Si un intitulé du document correspond à une matière déjà connue, reprends EXACTEMENT le nom de la liste (même orthographe, mêmes majuscules), pas celui du document.\n  - Si un intitulé du document REGROUPE plusieurs matières déjà connues (par exemple « Mathématiques et physique-chimie »), sépare-le : donne chacune de ces matières comme une entrée à part, avec le nom exact de la liste.\n  - Si un intitulé du document ne correspond à aucune matière connue, donne son nom tel qu\'il apparaît dans le document, court et lisible (le nom de la matière, pas une phrase).\n- Ne sépare jamais un intitulé qui désigne UNE seule discipline, même si son nom est composé (par exemple « Prévention-santé-environnement » ou « Éducation physique et sportive » restent entières).\n\nRègle :\n- "matieres" : la liste des noms de matières, sans doublon.\n- N\'invente aucune matière absente du document : la liste des matières connues sert à faire correspondre et à séparer, jamais à ajouter une matière que le document ne couvre pas. Si aucune n\'apparaît clairement, renvoie une liste vide.\n\nRéponds UNIQUEMENT en JSON, avec exactement cette clé : matieres (un tableau de chaînes).'),
    ('detecter_types_activite', 'Tu lis un référentiel officiel et tu en dégages la liste des TYPES D\'ACTIVITÉ (formats ou modalités d\'activité pédagogique) qu\'il met en œuvre à ce niveau.\n\nTypes d\'activité déjà connus de l\'application :\n{types_existants}\n\nTexte du référentiel :\n{texte}\n\nTa tâche :\n- Repère les types d\'activité, formats ou modalités de travail que ce référentiel met réellement en œuvre (par exemple : atelier, mise en situation, travaux pratiques, projet, évaluation — selon ce qui apparaît réellement).\n- Fais CORRESPONDRE ce que tu lis avec les types déjà connus :\n  - Si ce que tu lis correspond à un type déjà connu, reprends EXACTEMENT le libellé de la liste (même orthographe, mêmes majuscules), pas la formulation du document.\n  - Si ce que tu lis ne correspond à aucun type connu, donne son nom tel qu\'il ressort du document, court et lisible (le nom du type, pas une phrase).\n\nRègle :\n- "types" : la liste des libellés de types d\'activité, sans doublon.\n- N\'invente aucun type absent du document : la liste des types connus sert à faire correspondre, jamais à ajouter un type que le document ne met pas en œuvre. Si aucun n\'apparaît clairement, renvoie une liste vide.\n\nRéponds UNIQUEMENT en JSON, avec exactement cette clé : types (un tableau de chaînes).'),
    ('detecter_couple', 'Tu lis le début d\'un référentiel officiel et tu identifies à quel CYCLE et à quel NIVEAU (diplôme, spécialité ou tranche d\'âge) il s\'adresse.\n\nCycles et niveaux déjà connus de l\'application (un cycle par ligne, suivi de ses niveaux) :\n{cycles_existants}\n\nTexte du document :\n{texte}\n\nTa tâche :\n- Lis à quel cycle et à quel niveau ce document s\'adresse réellement.\n- Fais CORRESPONDRE ce que tu lis avec la liste ci-dessus :\n  - Si le cycle visé correspond à un cycle de la liste, reprends EXACTEMENT son nom (même orthographe, mêmes majuscules).\n  - Si le niveau visé correspond à un niveau de ce cycle dans la liste, reprends EXACTEMENT son nom.\n  - Sinon, donne le nom tel qu\'il ressort du document, court et lisible (le nom exact du diplôme ou du niveau, pas une phrase).\n\nRègle :\n- "cycle_lu" : le cycle visé par le document (nom de la liste si correspondance, sinon nom lu). Chaîne vide si le document ne permet pas de le dire.\n- "niveau_lu" : le niveau, diplôme ou spécialité visé (nom de la liste si correspondance, sinon nom lu). Chaîne vide si le document ne permet pas de le dire.\n- N\'invente rien : la liste sert à faire correspondre, jamais à choisir un cycle que le document ne vise pas.\n\nRéponds UNIQUEMENT en JSON, avec exactement ces clés : cycle_lu, niveau_lu.'),
    ('correction', "Ajoute ensuite, après l'activité, une section « Correction » : le corrigé complet et ordonné de chaque question ou exercice de l'activité — la réponse attendue, avec une courte explication quand elle éclaire — directement utilisable par le professeur.\nNe corrige que ce que l'activité demande : n'ajoute aucun nouvel exercice, aucune variante."),
    ('controle_qualite', "CONTRÔLE QUALITÉ — À APPLIQUER AVANT DE RENDRE\n\nAvant de considérer l'activité comme terminée, relis-la et vérifie qu'elle respecte TOUS les points ci-dessous. Corrige silencieusement le moindre écart, puis rends UNIQUEMENT l'activité finale.\n\n1. Fidélité à la demande — l'activité correspond exactement au type d'activité demandé, au niveau visé et à l'intention du texte source ; rien hors sujet, rien d'oublié.\n2. Corrigé juste — si l'activité comporte un corrigé, chaque question ou exercice y a sa réponse, correcte et complète, sans décalage de numérotation ni oubli.\n3. Conformité au format — la forme respecte réellement le type demandé (un QCM reste un QCM, une dictée reste une dictée, etc.).\n4. Consignes sans flou — aucune consigne ambiguë, vague ou à double sens ; une seule tâche claire à la fois ; critères de réussite explicites ; vocabulaire adapté au niveau et défini quand un mot difficile est indispensable.\n5. Mise en forme propre — titre clair, numérotation cohérente, structure lisible et régulière.\n\nNe laisse apparaître aucune trace de cette vérification (pas de commentaire, pas de « j'ai vérifié », pas de liste de contrôle) : le professeur ne doit voir que l'activité, prête à l'emploi."),
    ('ton_academique', "TON DE RÉDACTION — ACADÉMIQUE\n\nRédige toute l'activité (titre, consignes, énoncés, et le corrigé s'il y en a un) dans un registre ACADÉMIQUE : formel et institutionnel, à la manière des documents et programmes officiels. Phrases construites et complètes, vocabulaire soutenu et précis, tournures impersonnelles. Reste rigoureux et exact, et garde un niveau réellement adapté aux élèves visés. N'ajoute aucun commentaire sur le ton employé : rends uniquement l'activité."),
    ('ton_operationnel', "TON DE RÉDACTION — OPÉRATIONNEL\n\nRédige toute l'activité (titre, consignes, énoncés, et le corrigé s'il y en a un) dans un registre OPÉRATIONNEL : clair, net et direct, à la manière d'un professeur qui parle à sa classe. Phrases courtes, consignes directes (verbe d'action en tête), vocabulaire simple et concret. Va droit à l'essentiel sans appauvrir le contenu ni sauter d'étape. N'ajoute aucun commentaire sur le ton employé : rends uniquement l'activité."),
    ('few_shot', "LA MANIÈRE DE CE PROFESSEUR\n\nVoici des activités que ce professeur a déjà produites et gardées. Elles montrent SA façon de faire : ton employé, formulation des consignes, longueur des énoncés, mise en page, niveau de langue, habitudes de présentation.\n\n{exemples}\n\nInspire-toi de ces exemples pour la MANIÈRE, jamais pour le CONTENU. L'activité à produire porte sur le texte source donné plus haut, et sur lui seul : ne reprends aucune question, aucun énoncé, aucun extrait de ces exemples. N'ajoute aucun commentaire sur ces exemples : rends uniquement l'activité demandée."),
    ('exemple_referentiel', "Tu es enseignant·e en {matiere} pour le niveau « {niveau} ».\n\nÀ partir des EXTRAITS du référentiel officiel ci-dessous, rédige un TEXTE SOURCE court et concret (énoncé, situation professionnelle, document de travail) directement exploitable comme point de départ d'une activité pour ce niveau.\nContraintes : reste dans le périmètre du référentiel ; ne recopie PAS la liste de compétences ; produis un vrai contenu (contexte, données, consigne), pas un sommaire.\n\n## Extraits du référentiel officiel — {matiere}, {niveau}\n\n{referentiel}\n\n## Texte source à rédiger\n"),
    ('proposer_idee', "Tu es enseignant·e pour le niveau « {niveau} ».\n\nUn professeur a choisi le type d'activité {quoi} et cherche une idée de départ.\nÀ partir des EXTRAITS du référentiel officiel ci-dessous, propose UNE idée d'activité pour ce type d'activité, écrite comme la demande que le professeur taperait lui-même : 2 à 4 phrases concrètes (thème, support ou matériel, intention pédagogique), à la première personne ou à l'infinitif.\nPrésentation : commence par UNE première ligne « Objet : » suivie d'un titre très court (3 à 8 mots) pour retrouver l'activité facilement, puis une ligne vide, puis la demande aérée en 2 ou 3 petits paragraphes séparés par une ligne vide — d'abord le matériel ou le support, puis le déroulement, puis l'objectif pédagogique.\nContraintes : reste dans le périmètre du référentiel ; ne rédige PAS l'activité complète ; AUCUN titre, AUCUNE liste, AUCUNE autre mise en forme que ces lignes vides — uniquement le texte de la demande.\n\n## Extraits du référentiel officiel — {niveau}\n\n{referentiel}\n\n## Idée d'activité à proposer\n"),
    ('entete_cahier', "Cahier des charges de l'établissement (à respecter par-dessus le programme officiel) :"),
]


def upgrade() -> None:
    conn = op.get_bind()
    ins = sa.text("INSERT INTO settings (key, value) VALUES (:key, :value) "
                  "ON CONFLICT (key) DO NOTHING")
    for cle, texte in PROMPTS_GELES:
        conn.execute(ins, {"key": f"prompt_{cle}", "value": texte})


def downgrade() -> None:
    # On ne retire que ce qui est reste IDENTIQUE au texte seme : si l'admin a personnalise un
    # prompt depuis, sa version lui appartient et survit au rollback.
    conn = op.get_bind()
    sup = sa.text("DELETE FROM settings WHERE key = :key AND value = :value")
    for cle, texte in PROMPTS_GELES:
        conn.execute(sup, {"key": f"prompt_{cle}", "value": texte})
