# -*- coding: utf-8 -*-
"""seed cycles / niveaux / matieres / matiere_niveaux (donnees de reference structurelles)

Ces 4 tables portent le referentiel (cycles, niveaux, matieres, paires matiere-niveau).
AUCUNE migration ne les recreait -> trou de deploiement (elles n'existaient que sur le
miroir). Cette migration comble le trou : les lignes voyagent donc jusqu'a la vraie base.

Contenu EXTRAIT du dump nettoye (aschool_referentiel_4tables_20260711_CLEAN.sql) : rien
tape a la main. IDs explicites preserves. Idempotent : ON CONFLICT DO NOTHING sur chaque
INSERT (rejouable sans doublon, sur PK id comme sur les uniques). Ordre FK-safe :
cycles -> niveaux -> matieres -> matiere_niveaux.

Les 4 sequences sont recalees en fin d'upgrade avec GREATEST(valeur_en_base, valeur_dump)
-> une sequence deja plus haute ne redescend jamais (pas de collision de PK a la 1re
creation admin en prod).

downgrade : pass volontaire (non destructif). 7 FK RESTRICT pointent vers ces tables ;
un DELETE echouerait ou orphelinerait des referentiels vivants.

Revision ID: c6d7e8f9a0b1
Revises: b5c6d7e8f9a0
Create Date: 2026-07-11
"""
from typing import Sequence, Union

from alembic import op


revision: str = "c6d7e8f9a0b1"
down_revision: Union[str, Sequence[str], None] = "b5c6d7e8f9a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_CYCLES = [
    "INSERT INTO cycles (id, nom, ordre) VALUES (1, 'École élémentaire', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (2, 'Collège', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (3, 'École maternelle', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (5, 'Licence', 5) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (6, 'Lycée professionnel', 6) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (7, 'Crèche', 7) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (8, 'BTS', 8) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (9, 'Master', 9) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (10, 'BUT', 10) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (11, 'Doctorat', 11) ON CONFLICT DO NOTHING",
    "INSERT INTO cycles (id, nom, ordre) VALUES (4, 'Lycée', 4) ON CONFLICT DO NOTHING",
]

_NIVEAUX = [
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (1, 1, 'CP', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (2, 1, 'CE1', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (3, 1, 'CE2', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (4, 1, 'CM1', 4) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (5, 1, 'CM2', 5) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (6, 2, '6e', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (7, 2, '5e', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (8, 2, '4e', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (9, 2, '3e', 4) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (10, 3, 'Petite section (PS)', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (11, 3, 'Moyenne section (MS)', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (12, 3, 'Grande section (GS)', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (16, 5, 'L1', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (17, 5, 'L2', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (18, 5, 'L3', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (19, 6, 'Seconde Pro', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (20, 6, 'Première Pro', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (21, 6, 'Terminale Pro', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (22, 6, 'CAP 1re année', 4) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (23, 6, 'CAP 2e année', 5) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (24, 7, 'Grands (2-3 ans)', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (25, 7, 'Moyens (1-2 ans)', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (26, 7, 'Bébés (0-1 an)', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (27, 8, 'BTS SIO', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (28, 8, 'BTS Commerce International', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (29, 8, 'BTS NDRC', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (30, 8, 'BTS MCO', 4) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (31, 8, 'BTS Comptabilité & Gestion (CG)', 5) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (32, 8, 'BTS SAM', 6) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (33, 8, 'BTS Électrotechnique', 7) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (34, 8, 'BTS Génie Civil', 8) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (35, 8, 'BTS Bâtiment', 9) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (36, 8, 'BTS Professions Immobilières', 10) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (37, 8, 'BTS Banque', 11) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (38, 8, 'BTS Assurance', 12) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (39, 8, 'BTS Tourisme', 13) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (40, 8, 'BTS Audiovisuel', 14) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (41, 8, 'BTS Design / Arts appliqués', 15) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (42, 8, 'BTS CIEL Option A', 16) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (43, 8, 'BTS CIEL Option B', 17) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (44, 9, 'Master Droit', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (45, 9, 'Master Psychologie', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (46, 9, 'Master STAPS', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (47, 9, 'Master Informatique', 4) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (48, 9, 'Master Management / Gestion (IAE)', 5) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (49, 9, 'Master Finance', 6) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (50, 9, 'Master Marketing', 7) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (51, 9, 'Master Ressources Humaines', 8) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (52, 9, 'Master Économie', 9) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (53, 9, 'Master Sciences de l''Éducation', 10) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (54, 9, 'Master AES / Administration publique', 11) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (55, 9, 'Master Biologie', 12) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (56, 9, 'Master Chimie', 13) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (57, 9, 'Master Physique', 14) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (58, 9, 'Master Mathématiques', 15) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (59, 10, 'BUT Informatique', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (60, 10, 'BUT GEA', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (61, 10, 'BUT TC', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (62, 10, 'BUT GMP', 4) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (63, 10, 'BUT GEII', 5) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (64, 10, 'BUT MMI', 6) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (65, 10, 'BUT R&T', 7) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (66, 10, 'BUT GCCD', 8) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (67, 10, 'BUT QLIO', 9) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (68, 10, 'BUT Chimie', 10) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (69, 10, 'BUT Biologie (ex-GB)', 11) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (70, 10, 'BUT Carrières Juridiques', 12) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (71, 10, 'BUT Carrières Sociales', 13) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (72, 10, 'BUT STID', 14) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (73, 10, 'BUT IIA', 15) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (74, 11, 'Doctorat Sciences de l''ingénieur', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (75, 11, 'Doctorat Sciences de la vie / Biologie', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (76, 11, 'Doctorat Physique', 3) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (77, 11, 'Doctorat Chimie', 4) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (78, 11, 'Doctorat Mathématiques', 5) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (79, 11, 'Doctorat Informatique', 6) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (80, 11, 'Doctorat Environnement / Géosciences', 7) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (81, 11, 'Doctorat Droit', 8) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (82, 11, 'Doctorat Économie', 9) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (83, 11, 'Doctorat Sciences de gestion', 10) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (84, 11, 'Doctorat Lettres / Langues', 11) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (85, 11, 'Doctorat Histoire', 12) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (86, 11, 'Doctorat Sociologie', 13) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (87, 11, 'Doctorat Psychologie', 14) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (88, 11, 'Doctorat Philosophie', 15) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (13, 4, 'Seconde', 1) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (14, 4, 'Première', 2) ON CONFLICT DO NOTHING",
    "INSERT INTO niveaux (id, cycle_id, nom, ordre) VALUES (15, 4, 'Terminale', 3) ON CONFLICT DO NOTHING",
]

_MATIERES = [
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (1, 'Français', 1, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (2, 'Mathématiques', 2, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (3, 'Histoire-Géographie', 3, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (5, 'Physique-Chimie', 5, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (6, 'SVT', 6, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (7, 'Technologie', 7, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (9, 'EPS', 12, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (10, 'Développement sensoriel', 13, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (11, 'Motricité globale', 14, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (12, 'Motricité fine', 15, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (13, 'Éveil sonore et musical', 16, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (14, 'Éveil visuel', 17, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (15, 'Éveil corporel', 18, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (16, 'Langage pré-verbal', 19, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (17, 'Socialisation primaire', 20, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (18, 'Développement affectif', 21, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (20, 'Hygiène et premiers gestes d''autonomie', 23, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (21, 'Langage émergent', 24, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (22, 'Exploration sensorielle', 25, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (23, 'Jeux d''imitation', 26, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (24, 'Socialisation', 27, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (25, 'Premiers gestes d''autonomie', 28, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (26, 'Langage structuré', 29, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (27, 'Découverte du monde', 30, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (28, 'Jeux symboliques', 31, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (29, 'Socialisation avancée', 32, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (30, 'Autonomie', 33, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (31, 'Langage oral', 34, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (32, 'Découverte sensorielle', 35, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (33, 'Premiers repères dans le temps et l''espace', 36, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (34, 'Activités artistiques', 37, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (35, 'Langage oral enrichi', 38, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (36, 'Premiers gestes d''écriture', 39, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (37, 'Motricité globale et fine', 40, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (38, 'Découverte des formes et couleurs', 41, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (39, 'Socialisation et règles de vie', 42, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (40, 'Pré-lecture', 43, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (41, 'Pré-écriture', 44, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (42, 'Premiers outils mathématiques', 45, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (43, 'Motricité', 46, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (44, 'Socialisation structurée', 47, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (45, 'Lecture', 48, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (46, 'Écriture', 49, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (47, 'Arts plastiques', 50, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (48, 'Éducation musicale', 51, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (49, 'Lecture approfondie', 52, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (50, 'Histoire / Géographie', 53, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (51, 'Sciences', 54, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (52, 'Rédaction', 55, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (53, 'Histoire', 56, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (54, 'Géographie', 57, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (55, 'Sciences et technologie', 58, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (56, 'EMC', 59, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (57, 'Langue vivante', 60, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (58, 'Histoire-Géo', 61, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (59, 'Enseignements d''exploration', 62, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (60, 'SES', 63, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (61, 'NSI', 64, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (62, 'Philosophie', 65, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (63, 'Enseignement scientifique', 66, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (64, 'Droit civil', 67, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (65, 'Informatique', 68, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (66, 'Économie', 69, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (67, 'Droit constitutionnel', 70, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (68, 'Méthodologie', 71, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (69, 'Approfondissement disciplinaire', 72, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (70, 'Méthodologie avancée', 73, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (71, 'Options', 74, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (72, 'Spécialisation', 75, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (73, 'Préparation Master', 76, true) ON CONFLICT DO NOTHING",
    "INSERT INTO matieres (id, nom, ordre, actif) VALUES (74, 'Projet / mémoire', 77, true) ON CONFLICT DO NOTHING",
]

_MATIERE_NIVEAUX = [
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (1, 1, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (2, 1, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (3, 1, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (4, 1, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (5, 2, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (6, 2, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (7, 2, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (8, 2, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (9, 3, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (10, 3, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (11, 3, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (12, 3, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (17, 5, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (18, 5, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (19, 5, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (20, 6, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (21, 6, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (22, 6, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (23, 6, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (24, 7, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (25, 7, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (26, 7, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (27, 7, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (32, 9, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (33, 9, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (34, 9, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (35, 9, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (36, 10, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (37, 11, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (38, 12, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (39, 13, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (40, 14, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (41, 15, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (42, 16, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (43, 17, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (44, 18, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (46, 20, 26, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (47, 11, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (48, 12, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (49, 21, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (50, 22, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (51, 23, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (52, 24, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (53, 18, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (54, 25, 25, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (55, 11, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (56, 12, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (57, 26, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (58, 27, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (59, 28, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (60, 29, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (61, 18, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (62, 30, 24, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (63, 31, 10, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (64, 11, 10, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (65, 12, 10, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (66, 32, 10, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (67, 33, 10, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (68, 24, 10, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (69, 34, 10, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (70, 35, 11, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (71, 36, 11, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (72, 37, 11, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (73, 38, 11, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (74, 34, 11, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (75, 39, 11, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (76, 40, 12, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (77, 41, 12, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (78, 42, 12, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (79, 34, 12, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (80, 43, 12, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (81, 27, 12, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (82, 44, 12, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (83, 45, 1, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (84, 46, 1, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (85, 2, 1, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (86, 27, 1, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (87, 47, 1, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (88, 48, 1, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (89, 9, 1, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (90, 49, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (91, 46, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (92, 2, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (93, 50, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (94, 51, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (95, 47, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (96, 48, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (97, 9, 2, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (98, 45, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (99, 52, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (100, 2, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (101, 50, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (102, 51, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (103, 47, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (104, 48, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (105, 9, 3, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (106, 1, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (107, 2, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (108, 53, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (109, 54, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (110, 51, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (111, 47, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (112, 48, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (113, 9, 4, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (114, 1, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (115, 2, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (116, 53, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (117, 54, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (118, 55, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (119, 56, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (120, 57, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (121, 47, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (122, 48, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (123, 9, 5, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (124, 5, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (125, 57, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (126, 47, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (127, 48, 6, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (128, 57, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (129, 47, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (130, 48, 7, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (131, 57, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (132, 47, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (133, 48, 8, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (134, 56, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (135, 57, 9, true, 'A') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (136, 57, 9, true, 'B') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (137, 47, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (138, 48, 9, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (139, 1, 13, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (140, 58, 13, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (141, 2, 13, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (142, 51, 13, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (143, 57, 13, true, 'A') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (144, 57, 13, true, 'B') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (145, 9, 13, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (146, 59, 13, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (147, 1, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (148, 58, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (149, 57, 14, true, 'A') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (150, 57, 14, true, 'B') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (151, 9, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (152, 2, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (153, 5, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (154, 6, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (155, 60, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (156, 61, 14, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (157, 62, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (158, 58, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (159, 57, 15, true, 'A') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (160, 57, 15, true, 'B') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (161, 63, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (162, 9, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (163, 2, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (164, 5, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (165, 6, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (166, 60, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (167, 61, 15, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (168, 64, 16, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (169, 65, 16, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (170, 66, 16, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (171, 67, 16, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (172, 68, 16, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (173, 57, 16, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (174, 69, 17, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (175, 70, 17, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (176, 71, 17, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (177, 57, 17, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (178, 72, 18, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (179, 73, 18, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (180, 74, 18, true, '') ON CONFLICT DO NOTHING",
    "INSERT INTO matiere_niveaux (id, matiere_id, niveau_id, actif, variante) VALUES (181, 57, 18, true, '') ON CONFLICT DO NOTHING",
]

# Recalage des sequences : jamais de descente (GREATEST).
_SETVALS = [
    "SELECT setval('cycles_id_seq', GREATEST((SELECT last_value FROM cycles_id_seq), 13), true)",
    "SELECT setval('niveaux_id_seq', GREATEST((SELECT last_value FROM niveaux_id_seq), 88), true)",
    "SELECT setval('matieres_id_seq', GREATEST((SELECT last_value FROM matieres_id_seq), 79), true)",
    "SELECT setval('matiere_niveaux_id_seq', GREATEST((SELECT last_value FROM matiere_niveaux_id_seq), 189), true)",
]


def upgrade() -> None:
    for stmt in _CYCLES + _NIVEAUX + _MATIERES + _MATIERE_NIVEAUX:
        op.execute(stmt)
    for stmt in _SETVALS:
        op.execute(stmt)


def downgrade() -> None:
    # Seed de donnees de reference structurelles. Pas de downgrade destructif :
    # 7 FK RESTRICT pointent vers ces tables -> un DELETE echouerait ou detruirait
    # de la donnee de reference vivante. Rollback = restauration depuis sauvegarde.
    pass
