"""baseline schema postgresql

Revision ID: c9ffe00af0fd
Revises: 
Create Date: 2026-06-27 16:57:02.763164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ffe00af0fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_by', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connexion_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connexion_logs_email'), 'connexion_logs', ['email'], unique=False)
    op.create_index(op.f('ix_connexion_logs_user_id'), 'connexion_logs', ['user_id'], unique=False)
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('email_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=86), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_table('failed_login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('attempt_at', sa.DateTime(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiches_matieres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matiere_key', sa.String(length=64), nullable=False),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('accroche', sa.Text(), nullable=True),
    sa.Column('pour_qui', sa.Text(), nullable=True),
    sa.Column('ameliorations', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiches_matieres_matiere_key'), 'fiches_matieres', ['matiere_key'], unique=True)
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cle', sa.String(length=64), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('prenom', sa.String(length=64), nullable=True),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('niveau', sa.String(length=16), nullable=True),
    sa.Column('langue_lv', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('activites_sauvegardees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activite_key', sa.String(length=64), nullable=False),
    sa.Column('activite_label', sa.String(length=128), nullable=False),
    sa.Column('niveau', sa.String(length=32), nullable=False),
    sa.Column('sous_type', sa.String(length=64), nullable=True),
    sa.Column('nb', sa.Integer(), nullable=True),
    sa.Column('avec_correction', sa.Boolean(), nullable=False),
    sa.Column('matiere', sa.String(length=64), nullable=True),
    sa.Column('objet', sa.String(length=150), nullable=True),
    sa.Column('partagee', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('anonyme', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('texte_source', sa.Text(), nullable=False),
    sa.Column('resultat', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activites_sauvegardees_user_id'), 'activites_sauvegardees', ['user_id'], unique=False)
    op.create_table('feature_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_votes_unique', 'feature_votes', ['user_id', 'feature_key'], unique=True)
    op.create_index(op.f('ix_feature_votes_user_id'), 'feature_votes', ['user_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_table('few_shot_milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activite_key', sa.String(length=64), nullable=False),
    sa.Column('reached_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_few_shot_milestones_unique', 'few_shot_milestones', ['user_id', 'activite_key'], unique=True)
    op.create_index(op.f('ix_few_shot_milestones_user_id'), 'few_shot_milestones', ['user_id'], unique=False)
    op.create_table('niveaux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('traite', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niveaux_cycle_id'), 'niveaux', ['cycle_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sequences_sauvegardees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matiere', sa.String(length=64), nullable=False),
    sa.Column('niveau', sa.String(length=32), nullable=False),
    sa.Column('theme', sa.String(length=300), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('description_classe', sa.Text(), nullable=False),
    sa.Column('resultat', sa.Text(), nullable=False),
    sa.Column('partagee', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('anonyme', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequences_sauvegardees_user_id'), 'sequences_sauvegardees', ['user_id'], unique=False)
    op.create_table('tool_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=32), nullable=False),
    sa.Column('score_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_usage_logs_user_id'), 'tool_usage_logs', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('matiere_niveaux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matiere_niveaux_matiere_id'), 'matiere_niveaux', ['matiere_id'], unique=False)
    op.create_index(op.f('ix_matiere_niveaux_niveau_id'), 'matiere_niveaux', ['niveau_id'], unique=False)
    op.create_index('ix_matiere_niveaux_unique', 'matiere_niveaux', ['matiere_id', 'niveau_id'], unique=True)
    op.create_table('referentiels',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('nom_fixe', sa.Text(), nullable=False),
    sa.Column('collection', sa.Text(), nullable=False),
    sa.Column('filtres', sa.Text(), nullable=True),
    sa.Column('fichier', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('date_doc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('niveau_id', 'matiere_id'),
    sa.UniqueConstraint('nom_fixe')
    )
    op.create_table('user_enseignements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matiere_niveau_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matiere_niveau_id'], ['matiere_niveaux.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'matiere_niveau_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_enseignements')
    op.drop_table('referentiels')
    op.drop_index('ix_matiere_niveaux_unique', table_name='matiere_niveaux')
    op.drop_index(op.f('ix_matiere_niveaux_niveau_id'), table_name='matiere_niveaux')
    op.drop_index(op.f('ix_matiere_niveaux_matiere_id'), table_name='matiere_niveaux')
    op.drop_table('matiere_niveaux')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_tool_usage_logs_user_id'), table_name='tool_usage_logs')
    op.drop_table('tool_usage_logs')
    op.drop_index(op.f('ix_sequences_sauvegardees_user_id'), table_name='sequences_sauvegardees')
    op.drop_table('sequences_sauvegardees')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_niveaux_cycle_id'), table_name='niveaux')
    op.drop_table('niveaux')
    op.drop_index(op.f('ix_few_shot_milestones_user_id'), table_name='few_shot_milestones')
    op.drop_index('ix_few_shot_milestones_unique', table_name='few_shot_milestones')
    op.drop_table('few_shot_milestones')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_feature_votes_user_id'), table_name='feature_votes')
    op.drop_index('ix_feature_votes_unique', table_name='feature_votes')
    op.drop_table('feature_votes')
    op.drop_index(op.f('ix_activites_sauvegardees_user_id'), table_name='activites_sauvegardees')
    op.drop_table('activites_sauvegardees')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('matieres')
    op.drop_index(op.f('ix_fiches_matieres_matiere_key'), table_name='fiches_matieres')
    op.drop_table('fiches_matieres')
    op.drop_table('failed_login_attempts')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_connexion_logs_user_id'), table_name='connexion_logs')
    op.drop_index(op.f('ix_connexion_logs_email'), table_name='connexion_logs')
    op.drop_table('connexion_logs')
    op.drop_table('admin_audit_log')
    op.drop_table('admin_alerts')
    # ### end Alembic commands ###
