-- ============================================================================
-- college4e — partie 3/6 : les séances 17 à 28 (séquences 8 à 13)
--
-- Histoire-géographie, physique-chimie, SVT, technologie, mathématiques et
-- éducation aux médias — deux séances chacune.
--
-- LES CONTENUS DISCIPLINAIRES SONT CEUX DE LA 4e, pas ceux du cycle entier :
-- la traite atlantique et le XVIIIe siècle en histoire, les changements d'état
-- en physique-chimie, la tectonique en SVT, Pythagore en mathématiques. Un
-- programme de cycle laisse le choix de l'année ; une démonstration de niveau
-- doit le trancher, sinon le prof de 4e ne se reconnaît pas dans ce qu'il voit.
-- ============================================================================

INSERT INTO seances (user_id, sequence_id, position, titre, description, matiere, niveau,
                     duree_minutes, mode, competences, materiel, esquisse, contraintes, style,
                     resultat, created_at, updated_at) VALUES

-- ── Séquence 8 — Histoire et géographie ─────────────────────────────────────
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 8, 1,
 'Le commerce triangulaire : ce que les archives d''un port disent et ne disent pas',
 'Étude de cas sur un navire négrier nantais, à partir de son registre d''armement. Les élèves construisent le croquis des flux, puis mesurent l''écart entre la comptabilité et ce qu''elle recouvre.',
 'Histoire et géographie', '4e', 55, 'standard',
 '["Lire un document d''archive et en extraire des informations","Réaliser un croquis de flux à partir d''un texte","Distinguer ce qu''un document dit de ce qu''il tait"]',
 'Reproduction du registre d''armement d''un navire nantais (1741), planisphère muet A3, crayons de couleur.',
 '{"a":"Lecture guidée du registre : que transporte le navire, dans quel ordre, pour quel bénéfice (20 min).","b":"Construction du croquis de flux sur planisphère muet, avec légende (20 min).","c":"Retour sur le document : qu''est-ce qui n''y figure pas ? (15 min)"}',
 'Le croquis doit porter une légende construite par l''élève, pas recopiée du tableau.',
 'structure',
 E'# Ce que le registre dit, et ce qu''il compte\n\n## Le document\n\nLe registre d''armement d''un navire parti de Nantes en 1741. Un document comptable ordinaire : marchandises embarquées, escales, cargaison au retour, bénéfice net.\n\nIl est choisi précisément parce qu''il est ordinaire. Un document révolté aurait fait le travail à la place des élèves.\n\n## 1. Lecture guidée (20 min)\n\nTrois colonnes à remplir, dans l''ordre du voyage :\n\n| Étape | Ce qu''on embarque | Ce qu''on débarque |\n|---|---|---|\n| Nantes → côte africaine | Textiles, fusils, eau-de-vie, barres de fer | — |\n| Côte africaine → Saint-Domingue | « 312 captifs » | 289 (le registre note la différence sans un mot) |\n| Saint-Domingue → Nantes | Sucre, café, indigo | Bénéfice net : 187 000 livres |\n\nLa ligne du milieu arrête toujours la classe. Elle est écrite dans la même colonne, avec la même encre, entre les fusils et le sucre.\n\n## 2. Le croquis de flux (20 min)\n\nSur planisphère muet, trois flèches, trois couleurs, une légende construite par l''élève.\n\nContraintes annoncées :\n- l''épaisseur des flèches ne doit pas être identique — elle dit quelque chose de la valeur transportée ;\n- la légende nomme ce qui circule, sans euphémisme ;\n- le titre du croquis est une phrase, pas un mot.\n\nLe titre est le meilleur indicateur de ce que l''élève a compris. « Le commerce triangulaire » est un titre de manuel ; « Un commerce où le profit d''une étape repose sur des êtres humains » est un titre d''élève qui a lu le registre.\n\n## 3. Ce qui n''y figure pas (15 min)\n\nUne seule question, posée à la fin : **qu''est-ce que ce document ne dit pas ?**\n\nCe que la classe trouve :\n\n- Aucun nom. Les marchandises ont des références, les captifs ont un nombre.\n- Aucune durée de traversée du point de vue de ceux qui la subissent — seulement les dates de départ et d''arrivée.\n- Aucune mention de ce qui se passe après la vente.\n- Aucune trace de contestation, alors qu''elle existait déjà à cette date.\n\n**Le point de méthode, à formuler explicitement** : un document ne ment pas nécessairement pour être insuffisant. Ce registre est exact. Il est tenu par un comptable qui fait son travail. Et il ne permet pas, à lui seul, de comprendre ce qu''il enregistre.\n\nC''est pourquoi la séance suivante ajoute un récit de captif : non pour corriger le registre, mais pour montrer ce qu''une source seule ne peut pas porter.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 8, 2,
 'Deux sources, un même voyage : exposés et carte mentale du chapitre',
 'Confrontation du registre d''armement et du récit d''Olaudah Equiano. Trois exposés courts préparés par des groupes, puis construction collective de la carte mentale du chapitre.',
 'Histoire et géographie', '4e', 55, 'standard',
 '["Confronter deux documents de nature différente sur un même fait","Présenter un exposé court et structuré","Organiser les connaissances d''un chapitre en carte mentale"]',
 'Extraits du récit d''Olaudah Equiano (1789), le registre de la séance précédente, grande feuille A2 pour la carte mentale collective.',
 '{"a":"Trois exposés de cinq minutes préparés en amont : le port, la traversée, la plantation (25 min).","b":"Confrontation registre / récit sur un point précis : la traversée (15 min).","c":"Construction collective de la carte mentale du chapitre au tableau (15 min)."}',
 'Les exposés sont chronométrés à cinq minutes et coupés à cinq minutes trente.',
 'classique',
 E'# Deux sources, un même voyage\n\n## 1. Les trois exposés (25 min)\n\nPréparés en amont par trois groupes, cinq minutes chacun, chronométrés et coupés à cinq minutes trente. La coupe est annoncée d''avance : elle oblige à choisir, ce qui est l''objet même de l''exercice.\n\n| Groupe | Sujet | Ce qu''on attend en particulier |\n|---|---|---|\n| 1 | Le port de Nantes au XVIIIe | Le lien entre l''enrichissement visible (hôtels particuliers) et son origine |\n| 2 | La traversée | La confrontation des deux sources, pas le récit d''horreur seul |\n| 3 | La plantation sucrière | Le Code noir comme texte juridique, daté et signé |\n\n## 2. La confrontation (15 min)\n\nSur un seul point : **la traversée**.\n\n| | Le registre (1741) | Le récit d''Equiano (1789) |\n|---|---|---|\n| Nature | Document comptable, tenu pour l''armateur | Récit autobiographique, publié pour convaincre |\n| Ce qu''il donne | Des nombres, des dates, un bénéfice | Une expérience, des sensations, des noms |\n| Ce qu''il tait | Tout ce qui n''est pas comptable | Les chiffres, les mécanismes économiques |\n| Ce dont il faut se méfier | De croire que l''exactitude vaut vérité | Du recul de trente ans et du but militant |\n\nLa dernière ligne est celle qui fait de la séance un cours d''histoire et non un cours de morale. Le récit d''Equiano est **aussi** une source à critiquer : écrit longtemps après, publié dans un but précis, destiné à un public britannique abolitionniste.\n\nDire cela ne diminue pas son témoignage. Cela apprend qu''une source ne se juge pas à la sympathie qu''on éprouve pour son auteur.\n\n## 3. La carte mentale (15 min)\n\nConstruite au tableau avec la classe, recopiée par chacun. Un seul centre : **le commerce atlantique au XVIIIe siècle**.\n\nQuatre branches, pas davantage :\n\n- **Qui** — armateurs, capitaines, captifs, planteurs, consommateurs européens\n- **Quoi** — les trois cargaisons, dans l''ordre\n- **Où** — les trois continents, les ports nommés\n- **Avec quelles traces** — registres, récits, architecture des ports, Code noir\n\nLa quatrième branche n''est pas dans les manuels. Elle est celle qui reste : elle rappelle que ce chapitre a été reconstitué à partir de documents, dont certains ont été écrits par ceux qui organisaient le commerce et d''autres par ceux qui l''ont subi.',
 now(), now()),

-- ── Séquence 9 — Physique-Chimie ────────────────────────────────────────────
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 9, 1,
 'L''eau qui disparaît : peser avant, peser après',
 'Expérience en demi-groupe. L''eau s''évapore d''un récipient fermé et d''un récipient ouvert ; on pèse dans les deux cas. Le résultat contredit ce que la moitié de la classe attendait.',
 'Physique-Chimie', '4e', 90, 'standard',
 '["Formuler une hypothèse avant de manipuler","Mesurer une masse au centigramme","Rédiger un compte rendu qui permette de refaire l''expérience"]',
 'Balances au centigramme, erlenmeyers avec et sans bouchon, plaques chauffantes, thermomètres, gants.',
 '{"a":"Recueil des hypothèses écrites de chacun, avant toute manipulation (15 min).","b":"Manipulation en binômes : deux montages, quatre pesées, relevé des températures (45 min).","c":"Rédaction du compte rendu d''expérience individuel (30 min)."}',
 'Les hypothèses sont écrites et ramassées AVANT la manipulation. Aucune ne sera notée.',
 'structure',
 E'# L''eau qui disparaît\n\n## La conception à faire tomber\n\nPour une bonne moitié de la classe, ce qui s''évapore **disparaît**. Ce n''est pas de l''ignorance : c''est une conception cohérente, construite sur l''expérience quotidienne — la flaque sèche, le linge sèche, il ne reste rien.\n\nUne conception cohérente ne tombe pas parce qu''on affirme le contraire. Elle tombe si l''élève l''a écrite, puis mise à l''épreuve lui-même.\n\n## 1. Les hypothèses, écrites et ramassées (15 min)\n\nDeux questions, réponses écrites, feuilles ramassées avant de toucher au matériel :\n\n> **A.** Un erlenmeyer BOUCHÉ contenant de l''eau est chauffé, puis refroidi. Sa masse aura-t-elle augmenté, diminué, ou sera-t-elle identique ?\n> **B.** Même question avec un erlenmeyer OUVERT.\n\nAucune hypothèse n''est notée, et c''est dit. Sans cette garantie, les élèves écrivent ce qu''ils croient que le professeur attend, et l''expérience ne réfute plus rien.\n\nRépartition observée d''ordinaire : sur A, un tiers annonce une diminution ; sur B, la quasi-totalité annonce une diminution — cette fois à juste titre, mais pour la mauvaise raison.\n\n## 2. La manipulation (45 min)\n\nEn binômes, deux montages, quatre pesées :\n\n| | Masse avant | Masse après |\n|---|---|---|\n| Erlenmeyer bouché | m₁ | m₂ |\n| Erlenmeyer ouvert | m₃ | m₄ |\n\nConsignes de sécurité rappelées et écrites : gants pour manipuler le verre chaud, refroidissement complet avant la seconde pesée — **une pesée à chaud fausse tout**, l''air chaud autour du récipient modifie la mesure.\n\nRésultat obtenu : m₂ = m₁ à quelques centigrammes près. m₄ < m₃, nettement.\n\n## 3. L''exploitation, au tableau\n\nLa question qui fait basculer : **où est passée l''eau du récipient bouché ?**\n\nElle est là. On la voit sur les parois, en gouttelettes. Elle a changé d''état, pas de quantité.\n\nEt dans le récipient ouvert ? Elle est partie **dans la pièce**. Elle n''a pas disparu : elle est sortie du système qu''on pesait. La masse manquante est quelque part dans la salle.\n\n**La formulation à obtenir des élèves** : la masse se conserve ; ce qui change, c''est ce qu''on a décidé de peser.\n\n## 4. Le compte rendu (30 min)\n\nCritère unique, annoncé avant : **un élève d''une autre classe doit pouvoir refaire l''expérience avec votre compte rendu, sans vous poser de question.**\n\nCe critère remplace avantageusement le plan imposé en cinq parties. Il fait apparaître de lui-même ce qui manque : la quantité d''eau, la température atteinte, la durée du chauffage, le temps de refroidissement.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 9, 2,
 'Un désaccord scientifique : la masse de l''air, débat et synthèse visuelle',
 'La classe débat d''une affirmation scientifique contestée, avec l''expérience pour arbitre. La séance s''achève sur un diaporama de synthèse et une carte mentale du chapitre.',
 'Physique-Chimie', '4e', 90, 'approfondissement',
 '["Soutenir une position scientifique par un argument expérimental","Concevoir l''expérience qui trancherait un désaccord","Organiser un chapitre en carte mentale"]',
 'Ballon de baudruche, balance de précision, pompe, seringue de 60 mL, vidéoprojecteur, six ordinateurs.',
 '{"a":"Affirmation posée au tableau, positionnement écrit de chacun, puis débat argumenté (30 min).","b":"Conception collective de l''expérience qui tranche, et réalisation (30 min).","c":"Diaporama de synthèse par binômes et carte mentale du chapitre (30 min)."}',
 'Le professeur ne dit pas qui a raison avant que l''expérience ait été faite.',
 'classique',
 E'# Un désaccord scientifique\n\n## L''affirmation posée au tableau\n\n> **« L''air n''a pas de masse. »**\n\nElle est écrite sans guillemets d''ironie, sans sourire. Le professeur ne dit pas qu''elle est fausse — et il ne le dira pas avant que l''expérience ait tranché.\n\n## 1. Le débat argumenté (30 min)\n\nPositionnement écrit d''abord : *d''accord / pas d''accord / je ne sais pas*, avec une raison en une phrase. Puis débat en cercle.\n\nLes arguments qui reviennent, des deux côtés :\n\n| « L''air n''a pas de masse » | « L''air a une masse » |\n|---|---|\n| « On ne le sent pas quand on porte quelque chose » | « Il y a une pression atmosphérique, donc quelque chose pèse » |\n| « Un ballon gonflé ne pèse pas plus lourd » | « Les nuages contiennent de l''eau et ils tiennent dans l''air » |\n| « Le vide et l''air, sur une balance, c''est pareil » | « Une bouteille de plongée pleine est plus lourde que vide » |\n\nL''argument de la bouteille de plongée est celui qui débloque presque toujours la discussion — il vient d''un élève, jamais du professeur, et il est décisif parce qu''il est concret.\n\n**Le rôle du professeur pendant le débat** : noter, reformuler, demander « comment le sais-tu ? ». Jamais trancher. Un désaccord tranché par autorité n''apprend rien sur la manière dont les sciences tranchent réellement.\n\n## 2. L''expérience qui tranche (30 min)\n\nConçue avec la classe, à partir de la question : **quelle mesure mettrait tout le monde d''accord ?**\n\nLe protocole retenu, ordinairement proposé par les élèves eux-mêmes :\n\n1. Peser un ballon de baudruche dégonflé : m₁.\n2. Le gonfler à la pompe, en comptant les coups.\n3. Le repeser : m₂.\n\nDifficulté réelle, et il faut la nommer : la poussée d''Archimède. Le ballon gonflé déplace de l''air, ce qui masque une partie de la différence. Avec une balance ordinaire, l''écart obtenu est faible.\n\nLa variante qui fonctionne mieux en classe : une **bouteille rigide** dans laquelle on injecte de l''air à la seringue, vingt fois 60 mL. Le volume extérieur ne change pas, la poussée d''Archimède non plus, et la balance affiche une augmentation nette.\n\nC''est un moment de méthode important : la première expérience proposée n''était pas fausse, elle était mal contrôlée. On ne l''abandonne pas par découragement, on la corrige.\n\n## 3. Synthèse (30 min)\n\n**Le diaporama** — par binômes, cinq écrans maximum : l''affirmation, les deux positions, le protocole, le résultat, la conclusion. Contrainte : pas plus de quinze mots par écran. Ce qui reste doit être dit à l''oral.\n\n**La carte mentale du chapitre** — centre : *la matière et ses états*. Branches : les trois états, ce qui se conserve, ce qui change, les expériences faites, le vocabulaire. La branche « les expériences faites » n''existe dans aucun manuel et c''est celle que les élèves retrouvent le mieux six mois après.',
 now(), now()),

-- ── Séquence 10 — Sciences de la vie et de la Terre ─────────────────────────
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 10, 1,
 'Où la Terre tremble : cartographier avant d''expliquer',
 'À partir des données sismiques publiques, les élèves placent les séismes des trente derniers jours sur un planisphère. La carte obtenue impose la question à laquelle le cours répondra.',
 'Sciences de la vie et de la Terre', '4e', 90, 'standard',
 '["Exploiter un jeu de données réelles","Représenter une répartition sur une carte","Formuler une question à partir d''une observation"]',
 'Salle informatique, accès au catalogue sismique en ligne, planisphères A3, gommettes de trois couleurs selon la magnitude.',
 '{"a":"Prise en main du catalogue : filtrer par date et par magnitude, exporter la liste (25 min).","b":"Report des séismes sur le planisphère, une gommette par séisme (35 min).","c":"Observation collective : la carte affichée au mur, et la question qu''elle pose (30 min)."}',
 'Aucune explication n''est donnée avant que la carte soit finie. La question doit venir de la carte.',
 'structure',
 E'# Où la Terre tremble\n\n## Le principe : la carte avant le cours\n\nLe chapitre ne commence pas par les plaques. Il commence par une carte que les élèves fabriquent eux-mêmes, avec les données des trente derniers jours — pas une carte de manuel, la carte du mois qui vient de s''écouler.\n\nAucune explication n''est donnée avant qu''elle soit finie. La consigne est tenue même quand les élèves réclament : c''est la carte qui doit poser la question, pas le professeur.\n\n## 1. Le catalogue (25 min)\n\nPrise en main guidée : filtrer sur les trente derniers jours, magnitude supérieure à 4,5, exporter la liste — latitude, longitude, magnitude, profondeur.\n\nLes élèves découvrent d''ordinaire deux choses à ce moment :\n\n- il y a eu **plusieurs centaines** de séismes de magnitude supérieure à 4,5 en un mois, alors qu''ils en ont entendu parler de zéro ou d''un ;\n- une donnée scientifique publique est accessible à n''importe qui, gratuitement, en trois clics.\n\nLa seconde découverte compte autant que la première.\n\n## 2. Le report (35 min)\n\nUne gommette par séisme, sur planisphère A3, en binômes qui se partagent la liste.\n\n| Couleur | Magnitude |\n|---|---|\n| Jaune | 4,5 à 5,5 |\n| Orange | 5,5 à 6,5 |\n| Rouge | supérieure à 6,5 |\n\nLe travail est fastidieux et il faut l''assumer : c''est en plaçant la centième gommette que l''élève voit la ligne se dessiner. Un report automatique par ordinateur donnerait la même carte et n''apprendrait rien.\n\n## 3. Ce que la carte impose (30 min)\n\nLes planisphères sont affichés côte à côte au mur. La classe circule, puis on formule ensemble ce qu''on voit.\n\nCe qui sort, dans cet ordre :\n\n1. Les gommettes ne sont pas réparties au hasard. Elles forment des **lignes**.\n2. Il existe d''immenses zones sans aucune gommette — le centre des océans, le centre des continents.\n3. Les lignes suivent parfois des côtes, parfois passent au milieu d''un océan.\n4. Les rouges ne sont pas ailleurs que les jaunes : elles sont sur les mêmes lignes.\n\n**La question de la classe, écrite au tableau et gardée pour tout le chapitre** :\n\n> *Pourquoi les séismes se produisent-ils sur des lignes, et toujours les mêmes ?*\n\nC''est cette question, formulée par eux, qui rend la notion de plaque nécessaire — au lieu d''être un mot à retenir parce qu''il est dans le cours.\n\n## Prolongement immédiat\n\nSur un second planisphère, en cinq minutes, on place les volcans actifs. Les élèves n''ont pas besoin qu''on commente : ils voient que les deux cartes se superposent presque. La séance suivante partira de là.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 10, 2,
 'Le cas de Kobe : modéliser, expliquer, et en tirer une consigne de sécurité',
 'Étude d''un séisme précis, du phénomène jusqu''aux règles de prévention. Modélisation en classe, croquis explicatif, puis diaporama destiné aux élèves de 6e.',
 'Sciences de la vie et de la Terre', '4e', 90, 'approfondissement',
 '["Distinguer un modèle de la réalité qu''il représente","Réaliser un croquis explicatif légendé","Expliquer une consigne de sécurité par le phénomène qui la justifie"]',
 'Deux plaques de mousse rigide, sable, règle, dossier documentaire sur le séisme de Kobe (1995), ordinateurs.',
 '{"a":"Étude du dossier : le séisme, ses effets, les bâtiments touchés et ceux qui ont tenu (30 min).","b":"Modélisation avec les plaques de mousse, et critique du modèle (25 min).","c":"Croquis explicatif légendé puis diaporama de prévention pour les 6e (35 min)."}',
 'Le diaporama est destiné à de vrais élèves de 6e : le vocabulaire doit leur être accessible.',
 'classique',
 E'# Le cas de Kobe\n\n## Pourquoi un cas précis\n\nLa carte de la séance précédente a posé la question générale. Un cas unique, documenté, daté, donne à la réponse un poids que la généralité n''a pas : 17 janvier 1995, 5 h 46, magnitude 6,9, 6 434 morts.\n\n## 1. Le dossier (30 min)\n\nQuatre documents, exploités en groupes :\n\n| Document | Ce qu''il apporte |\n|---|---|\n| Carte de la faille de Nojima | La rupture est localisée, visible en surface |\n| Photographies de l''autoroute Hanshin | Un ouvrage moderne s''est effondré, et pas les plus vieux bâtiments de bois |\n| Sismogramme | Le phénomène a duré vingt secondes |\n| Réglementation japonaise avant / après | Les normes ont changé à cause de ce séisme |\n\nLe deuxième document est celui qui surprend : les élèves attendent que le moderne résiste et que l''ancien tombe. La réponse — les structures rigides des années 1960 n''absorbaient pas les oscillations — ouvre directement sur la prévention.\n\n## 2. La modélisation, et sa critique (25 min)\n\nDeux plaques de mousse rigide poussées l''une contre l''autre sous une couche de sable. On pousse lentement, la contrainte s''accumule, puis la rupture se fait d''un coup et le sable se déforme en surface.\n\n**Ce que le modèle montre bien** : l''accumulation lente puis la libération brutale, et le fait que la déformation de surface est la conséquence, pas la cause.\n\n**Ce que le modèle trahit — et c''est le cœur de la séance** :\n\n- il va mille fois trop vite ; la contrainte réelle s''accumule pendant des dizaines d''années ;\n- la mousse n''a rien à voir avec la roche ; on ne peut rien conclure sur les matériaux ;\n- il n''y a ni profondeur, ni température, ni eau ;\n- on voit la faille en entier, alors que sur le terrain elle est presque toujours invisible.\n\nLa question posée à la classe : **est-ce que ce modèle prouve quelque chose ?**\n\nNon. Il **illustre** un mécanisme et permet de le manipuler. La preuve, elle, vient des données : la carte des séismes, les mesures GPS de déplacement des plaques, les sismogrammes. Confondre les deux est l''erreur la plus fréquente en sciences au collège, et elle se corrige ici, sur un cas concret.\n\n## 3. Croquis et diaporama (35 min)\n\n**Le croquis** — en coupe, légendé : les deux blocs, la faille, le foyer, l''épicentre, les ondes. Une légende par élément, écrite par l''élève.\n\n**Le diaporama** — destiné aux 6e, et réellement présenté chez eux la semaine suivante. Cinq écrans : ce qu''est un séisme, pourquoi ici, ce qu''on fait pendant, ce qu''on fait après, ce qu''on ne fait surtout pas.\n\nLa contrainte du destinataire réel fait tout le travail de reformulation. Un élève de 4e qui écrit « les ondes sismiques se propagent depuis le foyer » se reprend tout seul quand on lui rappelle qui va lire.',
 now(), now()),

-- ── Séquence 11 — Technologie ───────────────────────────────────────────────
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 11, 1,
 'Du besoin au croquis : trois solutions pour un local à vélos',
 'Les équipes formulent le besoin en fonctions, proposent trois solutions concurrentes et les comparent sur des critères annoncés. La séance se termine sur une revue de projet.',
 'Technologie', '4e', 90, 'standard',
 '["Formuler un besoin sous forme de fonctions à assurer","Comparer des solutions sur des critères annoncés","Rendre compte de l''avancement d''un projet devant un tiers"]',
 'Relevé de mesures du local à vélos, papier à croquis, six ordinateurs de CAO, grille de comparaison vierge.',
 '{"a":"Reformulation du besoin en fonctions, par équipe de quatre (25 min).","b":"Trois esquisses de solution par équipe, avec estimation de coût et de faisabilité (40 min).","c":"Revue de projet : chaque équipe présente et répond aux questions d''une autre équipe (25 min)."}',
 'Aucune solution n''est retenue à cette séance. Les trois esquisses partent en revue, y compris celles qu''on croit mauvaises.',
 'structure',
 E'# Du besoin au croquis\n\n## Le besoin, tel qu''il est apparu\n\nLe local à vélos du collège est inutilisable les jours de pluie : la toiture s''arrête à un mètre du râtelier, et les vélos garés en bout de rangée sont trempés. Les élèves le savent mieux que l''administration — c''est eux qui y garent leur vélo.\n\nUn besoin réel, dans un lieu qu''ils traversent tous les jours, change complètement le rapport au projet. Le cahier des charges n''est pas une fiction pédagogique.\n\n## 1. Du besoin aux fonctions (25 min)\n\nL''erreur systématique : les équipes proposent une solution avant d''avoir formulé le besoin. « On met une bâche » arrive dans les deux premières minutes.\n\nLa parade est mécanique : **on écrit les fonctions avant de dessiner quoi que ce soit**, sous la forme « permettre de… » ou « empêcher que… ».\n\n| Type | Fonction |\n|---|---|\n| Principale | Permettre de garer 24 vélos à l''abri de la pluie |\n| Contrainte | Ne pas gêner le passage des piétons sur l''allée |\n| Contrainte | Résister au vent (le local est exposé plein ouest) |\n| Contrainte | Se monter sans intervention sur le bâtiment existant |\n| Contrainte | Coûter moins de 400 € en matériaux |\n| Complémentaire | Rester utilisable si un vélo est mal garé |\n\nLa dernière ligne vient toujours d''une équipe qui a observé la réalité : dans les faits, il y a toujours un vélo en travers.\n\n## 2. Trois esquisses (40 min)\n\n**Trois par équipe, obligatoirement.** Une équipe qui n''en produit qu''une a déjà choisi sans comparer, ce qui est précisément le réflexe à casser.\n\nChaque esquisse porte : un croquis coté à main levée, une estimation de coût, une estimation de temps de montage, et la liste des fonctions qu''elle assure et de celles qu''elle sacrifie.\n\nCette dernière colonne est la plus formatrice. Elle oblige à reconnaître qu''aucune solution ne coche tout — ce qui est le fond du métier.\n\n## 3. La revue de projet (25 min)\n\nChaque équipe présente ses trois esquisses à **une autre équipe**, pas au professeur. L''équipe qui écoute a une grille et trois questions obligatoires :\n\n1. Quelle fonction cette solution n''assure pas ?\n2. Qu''est-ce qui se casse en premier ?\n3. Combien de temps pour la monter, et avec qui ?\n\nLa troisième question est celle que les élèves oublient toujours de se poser à eux-mêmes.\n\n**Règle de la revue** : on ne défend pas, on note. Une équipe qui passe la revue à argumenter contre les objections n''en retire rien. Elle écoute, elle écrit, elle décidera après.\n\nAucune solution n''est retenue à cette séance. Le choix se fait à la séance suivante, à froid, avec la grille remplie sous les yeux.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 11, 2,
 'Prototyper vite pour se tromper tôt, et filmer le montage',
 'Réalisation d''un prototype à l''échelle de la solution retenue, mise à l''épreuve immédiate, puis montage vidéo court documentant le projet pour la classe suivante.',
 'Technologie', '4e', 90, 'approfondissement',
 '["Réaliser un prototype rapide et en tirer des conséquences","Éprouver une solution avant de l''industrialiser","Documenter un projet par un montage vidéo court"]',
 'Carton plume, baguettes de bois, pistolet à colle, ventilateur pour l''essai au vent, arrosoir, tablettes pour la captation.',
 '{"a":"Prototype à l''échelle 1/10 de la solution retenue, une heure maximum (40 min).","b":"Mise à l''épreuve : essai au ventilateur et essai à l''arrosoir, relevé des défaillances (20 min).","c":"Montage vidéo de deux minutes documentant le projet (30 min)."}',
 'Le prototype doit être fini en quarante minutes, même imparfait. Un prototype non éprouvé ne sert à rien.',
 'concis',
 E'# Prototyper vite pour se tromper tôt\n\n## La règle qui gouverne la séance\n\n**Quarante minutes, et on éprouve — fini ou non.**\n\nLes élèves veulent soigner. C''est justement ce qu''un prototype ne doit pas être : il ne sert pas à montrer, il sert à **échouer tôt**, pendant que la correction coûte encore trois bouts de carton.\n\nCette phrase est écrite au tableau et rappelée à la trentième minute.\n\n## 1. Le prototype (40 min)\n\nÉchelle 1/10, carton plume et baguettes. Une équipe, une solution — celle retenue à la revue de projet précédente, grille en main.\n\nContraintes de fabrication : les cotes du croquis sont respectées au dixième près, et le râtelier existant est reproduit lui aussi. Un abri prototypé sans ce qu''il doit abriter ne prouve rien.\n\n## 2. La mise à l''épreuve (20 min)\n\nDeux essais, identiques pour toutes les équipes.\n\n**L''essai au vent.** Ventilateur à 1 mètre, pleine puissance, trente secondes, de face puis de trois quarts. On note le moment et l''endroit de la défaillance.\n\n**L''essai à la pluie.** Arrosoir à pomme fine tenu à 50 cm, en oblique — la pluie tombe rarement à la verticale, et c''est exactement ce que les toitures trop courtes oublient.\n\nCe qu''on observe, presque à chaque fois :\n\n| Défaillance | Ce qu''elle enseigne |\n|---|---|\n| L''abri décolle de trois quarts, pas de face | La prise au vent maximale n''est pas dans l''axe |\n| L''eau atteint le dernier vélo malgré la toiture | Le débord calculé à la verticale est insuffisant en oblique |\n| La structure tient, le râtelier bouge | On avait dimensionné l''abri, pas l''ensemble |\n\nAucune de ces trois découvertes n''aurait été faite sur plan. Toutes coûtent cinq minutes à corriger sur un prototype, et plusieurs centaines d''euros sur un ouvrage réel.\n\n## 3. Le montage vidéo (30 min)\n\nDeux minutes, destinées à la classe de 4e de l''an prochain, qui reprendra le projet.\n\nStructure imposée, quatre plans :\n\n1. Le problème, filmé sur place — le local, un jour de pluie si possible.\n2. La solution retenue, croquis à l''écran, dix secondes.\n3. **L''essai qui a échoué.** Obligatoire.\n4. Ce qu''on changerait.\n\nLe troisième plan est celui que toutes les équipes veulent couper. Il est le plus utile : une vidéo de projet où tout fonctionne n''apprend rien à ceux qui reprendront le travail.\n\nOn le dit clairement : **le film sert à transmettre, pas à valoriser.** Un projet documenté avec ses échecs vaut mieux qu''un projet présenté comme une réussite lisse.',
 now(), now()),

-- ── Séquence 12 — Mathématiques ─────────────────────────────────────────────
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 12, 1,
 'Constater n''est pas démontrer : la conjecture mise en discussion',
 'Une affirmation vraie sur les figures mesurées, fausse en général. Les élèves la discutent, cherchent un contre-exemple, et découvrent ce qu''un dessin ne peut pas garantir.',
 'Mathématiques', '4e', 55, 'standard',
 '["Distinguer constater sur une figure et démontrer","Chercher un contre-exemple pour réfuter une affirmation","Formuler une objection mathématique devant la classe"]',
 'Logiciel de géométrie dynamique projeté, règles et équerres, fiche de quatre figures imprimées.',
 '{"a":"Mesure sur les quatre figures imprimées, relevé des résultats au tableau (15 min).","b":"Discussion réglée : l''affirmation est-elle vraie ? peut-on en être sûr ? (25 min).","c":"Recherche d''un contre-exemple avec le logiciel, en déplaçant un point (15 min)."}',
 'Le logiciel n''est ouvert qu''au troisième temps. La discussion se fait sur les figures papier.',
 'classique',
 E'# Constater n''est pas démontrer\n\n## L''affirmation posée\n\n> **« Si un triangle a deux côtés de 6 cm et 8 cm, alors le troisième mesure 10 cm. »**\n\nElle est écrite au tableau sans commentaire. Les quatre figures distribuées la vérifient toutes les quatre — elles ont été construites pour cela.\n\n## 1. Les mesures (15 min)\n\nChacun mesure, les résultats vont au tableau. Quatre figures, quatre fois 10 cm, à un demi-millimètre près.\n\nLa classe conclut d''une seule voix que l''affirmation est vraie. C''est le moment que la séance attendait.\n\n## 2. La discussion (25 min)\n\nUne seule question, et elle est difficile : **peut-on en être sûr ?**\n\nLes positions qui apparaissent :\n\n| Position | Ce qu''elle vaut |\n|---|---|\n| « On l''a mesuré quatre fois, c''est vrai » | Quatre cas ne font pas une règle — mais l''élève a raison de faire confiance à la mesure |\n| « Ma règle affiche 10, donc c''est 10 » | La mesure a une précision ; 9,98 et 10 sont indiscernables à la règle |\n| « Ça marche parce que 6, 8, 10 c''est comme 3, 4, 5 » | Vrai, et c''est la piste — mais pourquoi cela marcherait-il toujours ? |\n| « Il faudrait essayer un triangle différent » | C''est exactement la bonne idée |\n\nLa quatrième position est celle qu''il faut faire émerger sans la donner. La relance : *qu''est-ce qui n''a pas changé entre les quatre figures ?*\n\nRéponse, quand elle vient : l''angle. Les quatre figures ont un angle droit entre les côtés de 6 et 8. L''affirmation, telle qu''elle est écrite au tableau, ne le dit pas.\n\n## 3. Le contre-exemple (15 min)\n\nAu logiciel, projeté : un triangle avec deux côtés de 6 et 8, et un point libre. On déplace. Le troisième côté passe de 2 à 14 sans effort.\n\n**Un seul contre-exemple suffit à réfuter.** C''est la première fois de l''année que les élèves le voient s''appliquer pour de bon, et c''est une des idées les plus solides des mathématiques : mille exemples ne prouvent pas, un contre-exemple réfute.\n\n## Ce qu''on écrit à la fin\n\nDeux lignes, au cahier :\n\n> Une figure permet de **conjecturer**. Elle ne permet pas de conclure : elle est dessinée dans un cas particulier, et mesurée avec une précision limitée.\n> Pour conclure, il faut une propriété qui vaille dans **tous** les cas — et l''écrire.\n\nL''affirmation corrigée est alors posée, avec sa condition manquante : *si l''angle entre les côtés de 6 et 8 est droit, alors le troisième côté mesure 10*. Elle est vraie, et elle porte le nom d''un théorème que la séance suivante démontrera.\n\n## Le bénéfice inattendu\n\nLes élèves les plus en difficulté sont souvent les plus à l''aise dans cette séance : elle ne demande aucune technique, seulement de dire ce qu''on voit et ce qu''on ne peut pas garantir. Plusieurs y prennent la parole pour la première fois du trimestre.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 12, 2,
 'Rédiger une démonstration, et repérer où un raisonnement se casse',
 'Étude de cas sur trois copies anonymes : l''une est juste, les deux autres sont fausses à des endroits différents. Les élèves localisent la rupture, puis rédigent leur propre démonstration.',
 'Mathématiques', '4e', 55, 'remediation',
 '["Rédiger une démonstration en citant la propriété utilisée","Repérer l''endroit exact où un raisonnement se casse","Employer la réciproque du théorème de Pythagore à bon escient"]',
 'Trois copies anonymisées reproduites en A4, fiche méthode « énoncé / propriété / conclusion », carte mentale du chapitre en construction.',
 '{"a":"Lecture des trois copies et repérage individuel de l''erreur, sans correction (20 min).","b":"Mise en commun : où exactement se casse chaque raisonnement (15 min).","c":"Rédaction individuelle d''une démonstration sur un nouvel énoncé (20 min)."}',
 'On ne dit pas « c''est faux ». On dit à quelle ligne ça se casse, et pourquoi.',
 'structure',
 E'# Où le raisonnement se casse\n\n## Le dispositif\n\nTrois copies, anonymisées, reproduites telles quelles — fautes d''orthographe comprises. Elles viennent de vraies classes des années précédentes, avec l''accord des élèves.\n\nUne est juste. Les deux autres sont fausses **à des endroits différents**, et c''est là tout l''intérêt : les élèves apprennent que « faux » n''est pas un état de la copie mais un point précis du raisonnement.\n\n## L''énoncé commun\n\n> Un triangle ABC vérifie AB = 5 cm, AC = 12 cm, BC = 13 cm. Est-il rectangle ?\n\n## Copie 1\n\n> *J''ai mesuré l''angle en A avec mon rapporteur, il fait 90°. Donc le triangle est rectangle en A.*\n\n**Où ça se casse : dès la première ligne.** Pas à la conclusion, qui est vraie. La copie mesure au lieu de démontrer — et la mesure d''un rapporteur ne distingue pas 90° de 89,7°.\n\nCe cas est le plus utile parce que **la conclusion est juste**. Il oblige à comprendre qu''on n''évalue pas le résultat mais le chemin.\n\n## Copie 2\n\n> *5² + 12² = 25 + 144 = 169. Et 13² = 169. Donc d''après le théorème de Pythagore, le triangle est rectangle en A.*\n\n**Où ça se casse : à la citation.** Tous les calculs sont exacts, la conclusion est exacte. Mais le théorème de Pythagore dit : *si le triangle est rectangle, alors…* Il part du triangle rectangle, il n''y arrive pas.\n\nC''est **la réciproque** qui permet de conclure ici. La copie a utilisé le bon calcul en citant le mauvais théorème.\n\nBeaucoup d''élèves trouvent cette distinction excessive. La réponse est concrète : si l''on avait AB = 5, AC = 12, BC = 14, le calcul serait le même et la conclusion serait fausse. Ce qu''on cite décide de ce qu''on a le droit de conclure.\n\n## Copie 3\n\n> *Le plus grand côté est 13. 5² + 12² = 169 = 13². D''après la réciproque du théorème de Pythagore, le triangle est rectangle en A.*\n\n**Elle est juste**, et elle est la plus courte des trois. On la fait remarquer : une démonstration correcte n''est pas une démonstration longue.\n\nUn seul point manque, qu''on ajoute ensemble : dire pourquoi on part du plus grand côté.\n\n## La mise en commun (15 min)\n\nAu tableau, une seule ligne par copie :\n\n| Copie | Ligne où ça se casse | Nature de la rupture |\n|---|---|---|\n| 1 | Ligne 1 | Constate au lieu de démontrer |\n| 2 | Ligne 3 | Cite le théorème au lieu de sa réciproque |\n| 3 | — | Juste |\n\n**La formule à retenir, dictée** : *une démonstration se casse à un endroit précis. Trouver cet endroit vaut mieux que barrer la copie.*\n\n## La rédaction (20 min)\n\nNouvel énoncé, rédaction individuelle, avec la fiche méthode en trois colonnes sous les yeux : **ce que je sais** / **la propriété que j''utilise** / **ce que j''en conclus**.\n\nLa colonne du milieu est celle qui est vide dans neuf copies faibles sur dix. Elle est la seule qui compte vraiment.',
 now(), now()),

-- ── Séquence 13 — Éducation aux médias et à l'information ───────────────────
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 13, 1,
 'Remonter à la source : d''où vient l''image qui a circulé cette semaine',
 'Une image réellement partagée dans le collège la semaine précédente est prise comme objet d''enquête. Les élèves remontent à sa source, à sa date, à son contexte d''origine.',
 'Éducation aux médias et à l’information', '4e', 55, 'standard',
 '["Retrouver la source première d''une information reprise","Vérifier une image par sa provenance et par sa date","Distinguer un fait d''une opinion"]',
 'Postes du CDI, moteur de recherche par image, fiche d''enquête en quatre étapes. La professeure documentaliste co-anime.',
 '{"a":"Présentation de l''image et recueil de ce que la classe croit savoir (10 min).","b":"Enquête par groupes : recherche par image, datation, contexte d''origine (30 min).","c":"Mise en commun et reconstitution du trajet de l''image (15 min)."}',
 'L''image choisie ne met en cause aucun élève et n''a pas circulé de façon malveillante.',
 'classique',
 E'# Remonter à la source\n\n## L''objet d''enquête\n\nUne image qui a réellement circulé dans le collège la semaine précédente : une photographie d''un couloir inondé, accompagnée du texte « c''est chez nous, cours annulés demain ».\n\nElle a été choisie pour trois raisons : elle a vraiment circulé, elle ne met personne en cause, et elle est fausse — le couloir n''est pas celui du collège.\n\n## 1. Ce que la classe croit savoir (10 min)\n\nAvant toute recherche, on relève les certitudes à main levée :\n\n- Combien l''ont vue passer ? Presque toute la classe.\n- Combien l''ont crue ? Une bonne moitié.\n- Combien l''ont transmise ? Un tiers.\n- Qui l''a envoyée en premier ? **Personne ne sait.**\n\nLa dernière ligne est le point de départ de la séance. On la garde au tableau.\n\n## 2. L''enquête (30 min)\n\nQuatre étapes, dans l''ordre, sur la fiche :\n\n**Étape 1 — La recherche par image.** On dépose l''image dans un moteur de recherche par image. Le geste est nouveau pour la quasi-totalité de la classe, et c''est celui qui restera.\n\n**Étape 2 — La date.** Le moteur rend des occurrences antérieures. La plus ancienne remonte à trois ans, sur un site d''information régional — et à mille kilomètres d''ici.\n\n**Étape 3 — Le contexte d''origine.** L''article d''origine parle d''un lycée inondé après un orage, dans un département précis, avec le nom de l''établissement.\n\n**Étape 4 — Ce qui a changé en route.** L''image est identique. Seul le texte qui l''accompagne a changé. Personne n''a truqué la photo : on a truqué **ce qu''on en dit**.\n\n## 3. La reconstitution (15 min)\n\nAu tableau, le trajet complet :\n\n| Étape | Ce qui est vrai | Ce qui est ajouté |\n|---|---|---|\n| Article d''origine, il y a trois ans | Un lycée inondé, nommé, daté | — |\n| Reprise sur un compte de mèmes | L''image | Le lieu disparaît |\n| Partage local, la semaine dernière | L''image | « C''est chez nous », « cours annulés » |\n\n**La conclusion, formulée par les élèves** : l''image n''a jamais menti. Ce sont les phrases posées autour qui ont menti, et elles n''ont coûté aucun effort à écrire.\n\n## Le point délicat, et comment on le tient\n\nUn tiers de la classe a transmis l''image. Il ne s''agit pas de les mettre en cause : la séance n''a aucune valeur si elle se termine en tribunal.\n\nLa question posée est autre : **qu''est-ce qui aurait pu vous arrêter ?** Les réponses des élèves sont plus efficaces que n''importe quelle recommandation :\n\n- « Que quelqu''un demande où c''était exactement. »\n- « Que le message dise qui l''avait vu. »\n- « Qu''on se demande pourquoi personne d''autre n''en parlait. »\n\nLa troisième est la meilleure, et elle est de méthode : une nouvelle importante qui ne circule que par un canal est suspecte pour cette raison seule.',
 now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 13, 2,
 'Publier à son tour : une vidéo courte qui cite ses sources',
 'Les élèves produisent à leur tour un contenu bref sur un sujet du collège, avec l''obligation de citer et de dater chaque élément. La production est montée puis affichée avec son mode d''emploi.',
 'Éducation aux médias et à l’information', '4e', 55, 'approfondissement',
 '["Produire un contenu qui cite ses sources","Monter une vidéo courte à partir d''éléments hétérogènes","Expliquer pourquoi un contenu apparaît dans un fil"]',
 'Tablettes, logiciel de montage simple, banque d''images libres de droits, fiche de sources à remplir obligatoirement.',
 '{"a":"Choix du sujet et collecte des éléments, fiche de sources remplie au fur et à mesure (20 min).","b":"Montage de la vidéo, 60 secondes maximum (25 min).","c":"Diffusion en classe : chaque vidéo est suivie de la lecture de sa fiche de sources (10 min)."}',
 'Un élément sans source datée ne peut pas entrer dans le montage. Sans exception.',
 'structure',
 E'# Publier à son tour\n\n## La règle unique\n\n**Un élément sans source datée n''entre pas dans le montage.** Aucune exception, y compris pour une image « trouvée sur internet » qui ferait bien.\n\nC''est contraignant, et c''est le seul moyen de faire éprouver de l''intérieur ce qui a été analysé la séance précédente : produire honnêtement coûte du temps, mentir n''en coûte aucun. Les élèves le découvrent en le vivant, pas en l''entendant.\n\n## 1. Le sujet et la collecte (20 min)\n\nSujets possibles, tous internes au collège et vérifiables :\n\n- Le nouveau tri des déchets au réfectoire : ce qui change réellement.\n- Le CDI : ce qu''on peut y faire et que personne ne sait.\n- Le trajet des cars : pourquoi le 12 arrive toujours en retard.\n\nLa fiche de sources se remplit **pendant** la collecte, jamais après :\n\n| Élément | D''où il vient | Date | Qui l''a produit |\n|---|---|---|---|\n| Photo du réfectoire | Prise par nous | 14/05 | Groupe 3 |\n| Chiffre des déchets | Affiche de l''intendance | mars, affichée au hall | Service intendance |\n| Citation | Entretien avec le gestionnaire | 14/05, 12 h 30 | Lui-même, accord donné |\n\nLa dernière colonne fait toujours apparaître un cas : un chiffre entendu, que personne ne peut attribuer. Il sort du montage, et le groupe le vit mal. C''est exactement l''expérience visée.\n\n## 2. Le montage (25 min)\n\n60 secondes maximum. Structure libre, mais une contrainte de forme : **les sources apparaissent à l''écran**, en bas, au moment où l''élément est montré. Pas dans un générique de fin que personne ne lit.\n\nLes élèves objectent que « ça fait moche ». La réponse est de leur montrer deux versions de leur propre vidéo, avec et sans. Ils constatent que la version sourcée est plus convaincante — et c''est un argument plus solide qu''une obligation morale.\n\n## 3. La diffusion (10 min)\n\nChaque vidéo est projetée, puis **la fiche de sources est lue à voix haute**. Le contraste entre les soixante secondes et la liste qui a été nécessaire pour les produire est le vrai contenu de la séance.\n\n## Le dernier temps : pourquoi ça apparaît dans ton fil\n\nCinq minutes, en clôture de séquence, sur une question que les élèves posent d''eux-mêmes : *pourquoi je vois ça et pas autre chose ?*\n\nTrois mécanismes, sans jargon :\n\n1. **Ce que tu as regardé longtemps** compte plus que ce que tu as aimé. Le temps d''arrêt est mesuré, le pouce ne l''est pas.\n2. **Ce que regardent les gens qui te ressemblent** t''est proposé, même si tu ne les connais pas.\n3. **Ce qui fait réagir** circule plus que ce qui informe — la colère et le rire se partagent, la nuance ne se partage pas.\n\nLa conclusion se formule alors seule : une information vraie et nuancée part avec un handicap. Le savoir ne suffit pas à le corriger, mais cela explique pourquoi le vrai circule moins vite que le faux.',
 now(), now());
