-- ============================================================================
-- college4e — 3e, partie 3/3 (a) : les activités des séances 57 à 66
--
-- Français, langues vivantes, arts plastiques, éducation musicale.
-- Trois précisions se posent ici : compte rendu de lecture, débats
-- interprétatifs, débats littéraires.
-- ============================================================================

INSERT INTO activites (user_id, seance_id, position, activite_type_id, activite_label, sous_type,
                       nb, avec_correction, objet, matiere, niveau, ton, texte_source, resultat,
                       statut, created_at, updated_at) VALUES

-- ══ Séance 57 — Français : deux voix ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 57, 1, 130, 'compte rendu', 'compte rendu de lecture',
 NULL, true, 'Rendre compte d''un texte autobiographique sans raconter l''enfance de l''auteur',
 'Français', '3e', 'academique',
 'Les extraits des « Mots » de Sartre et d''« Enfance » de Nathalie Sarraute étudiés en classe.',
 E'# Compte rendu de lecture — un texte sur soi\n\n**Une page. La consigne interdit de raconter l''enfance de l''auteur.**\n\n---\n\n## La consigne\n\nRendre compte de l''extrait **sans raconter ce qui est arrivé à l''auteur enfant**.\n\nCe qui reste : la manière dont il s''y prend pour parler de lui. C''est ce que la séquence travaille, et c''est ce qu''un compte rendu de lecture doit savoir isoler.\n\n## Les quatre parties\n\n**1. De quoi parle le texte, en deux lignes.** Pas l''épisode : le sujet. « Un homme adulte revient sur la façon dont il a appris à lire » n''est pas un résumé de l''épisode.\n\n**2. La solution d''écriture retenue.** Comment l''auteur fait tenir ensemble l''enfant et l''adulte ? Deux voix, ironie continue, troisième personne, images ?\n\n**3. Un passage où l''adulte se manifeste.** Cité, et commenté en trois lignes.\n\n**4. Ce que le texte fait au lecteur.** Pas « c''est bien » : ce qu''on comprend en le lisant qu''on ne comprendrait pas autrement.\n\n---\n\n# Corrigé — un compte rendu attendu\n\n## 1. De quoi parle le texte\n\nUn homme d''une cinquantaine d''années revient sur les années où, enfant, il a construit son rapport aux livres — et sur ce que les adultes autour de lui en ont fait.\n\n## 2. La solution d''écriture\n\nL''adulte ne quitte jamais la scène. Il raconte l''enfant **et il le juge en même temps**, avec une ironie qui ne s''interrompt pas. Le lecteur n''est jamais seul avec l''enfant : quelqu''un est toujours là pour commenter.\n\nCe choix a un effet précis : on ne s''attendrit pas. L''auteur s''interdit l''émotion en s''interdisant le silence.\n\n## 3. Un passage où l''adulte se manifeste\n\n> *« Je ne savais pas encore que je jouais la comédie ; je croyais lire. »*\n\nDeux propositions, deux temps, deux personnes. L''enfant croyait ; l''adulte sait. La phrase contient à elle seule tout le dispositif du texte.\n\n## 4. Ce que le texte fait au lecteur\n\nIl rend impossible de croire à un souvenir pur. En lisant, on voit un homme reconstruire son enfance sous nos yeux, et le dire — ce qui est plus honnête, et plus déstabilisant, qu''un récit qui prétendrait restituer.\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Raconte l''épisode malgré la consigne |\n| Fragile | Évite le récit, ne dit rien de la manière d''écrire |\n| Satisfaisante | Identifie la solution d''écriture, la cite |\n| Très bonne | Relie le choix d''écriture à l''effet produit sur le lecteur |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 57, 2, 135, 'rituel d''écriture', NULL,
 5, false, 'Cinq minutes : un souvenir dont je ne suis pas sûr',
 'Français', '3e', 'operationnel',
 'Rituel hebdomadaire de début de séance, cinq minutes chronométrées, cahier jamais noté.',
 E'# Rituel d''écriture — un souvenir dont je ne suis pas sûr\n\n**Tous les lundis, cinq minutes. Le cahier n''est jamais noté.**\n\n---\n\n## La consigne du trimestre\n\n> **Racontez un souvenir dont vous n''êtes pas sûr — et dites à quel endroit vous n''êtes pas sûr.**\n\nElle est plus difficile qu''elle n''en a l''air, et elle est exactement au cœur de la séquence : un souvenir se reconstruit, et le savoir change la façon de l''écrire.\n\n## Les cinq amorces du trimestre\n\n| Semaine | L''amorce | Ce qu''elle fait travailler |\n|---|---|---|\n| 1 | Une première fois dont on ne sait plus la date | La chronologie reconstruite après coup |\n| 2 | Un souvenir qu''on vous a raconté et que vous croyez avoir vécu | La mémoire empruntée |\n| 3 | Un lieu que vous avez revu et qui avait changé de taille | L''échelle de l''enfance |\n| 4 | Une phrase entendue dont vous ne savez plus qui l''a dite | L''attribution, qui se perd la première |\n| 5 | Un souvenir que quelqu''un raconte autrement que vous | Deux versions, aucune fausse |\n\nLa deuxième est celle qui produit le plus d''effet. Presque tous les élèves en ont un — un souvenir de petite enfance qui vient en réalité d''une photographie ou d''un récit familial — et beaucoup le découvrent en écrivant.\n\n## Trois débuts écrits par des élèves\n\n> *Je me souviens du jour où j''ai appris à faire du vélo. Sauf que sur la photo je suis avec mon oncle, et dans mon souvenir c''est mon père.*\n\n> *La cour de l''école maternelle était immense. J''y suis retourné l''an dernier : elle fait la moitié du gymnase. Je ne sais pas laquelle des deux est vraie.*\n\n> *Quelqu''un a dit cette phrase, et pendant dix ans j''ai cru que c''était ma grand-mère. Ce n''était pas possible : elle était déjà morte.*\n\nAucun ne se contente de raconter. Tous les trois portent le doute dans le texte, et c''est ce qui les rend justes.\n\n## Pourquoi le rituel n''est pas noté\n\nLa règle est rappelée chaque semaine. Sur ce sujet-là plus que sur tout autre : demander à un élève d''écrire sur sa mémoire et le noter serait une confusion de rôles.\n\nCe qui est ramassé une fois par trimestre est **la régularité**, pas le contenu. Le cahier se feuillette, il ne se corrige pas.\n\n## Ce que le rituel produit\n\nÀ la fin du trimestre, la moitié de la classe dispose de cinq amorces réutilisables pour le texte long de la séquence — et surtout, l''écriture de soi n''est plus un exercice intimidant : ils l''ont pratiquée cinq fois, cinq minutes.',
 'termine', now(), now()),

-- ══ Séance 58 — Français : le souvenir est-il fidèle ? ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 58, 1, 127, 'débat argumenté', 'débats interprétatifs',
 NULL, false, 'Que fait l''auteur quand il se moque de l''enfant qu''il était ?',
 'Français', '3e', 'academique',
 'Le passage ironique des « Mots », relu à voix haute deux fois.',
 E'# Débat interprétatif — l''ironie du narrateur\n\n**Vingt-cinq minutes, en cercle. Un tour complet avant toute discussion.**\n\n---\n\n## La question\n\n> **Quand l''auteur se moque de l''enfant qu''il était, de qui se moque-t-il exactement ?**\n\nElle paraît close et ne l''est pas. Le texte le permet de plusieurs façons, et aucune ne s''impose.\n\n## Les trois lectures\n\n**A — Il se moque de lui-même.** Un adulte lucide règle ses comptes avec l''enfant qu''il a été, et cette lucidité est une forme d''honnêteté.\n\n**B — Il se moque des adultes.** L''enfant jouait la comédie parce que les adultes attendaient ce spectacle. C''est eux que l''ironie vise, à travers lui.\n\n**C — Il se protège.** L''ironie l''empêche d''être ému, donc d''être vulnérable devant son lecteur. Elle n''est pas un jugement mais une défense.\n\n## Ce que le texte permet d''opposer\n\n| Lecture | L''indice le plus solide | Sa limite |\n|---|---|---|\n| A | Le « je » est le sujet de toutes les phrases moqueuses | On peut se moquer de soi pour viser autre chose |\n| B | Les adultes sont décrits comme un public qui applaudit | Le texte ne les attaque jamais directement |\n| C | L''ironie ne s''interrompt **jamais**, pas une ligne | Une constance peut être un style, pas une peur |\n\nLa lecture C est la plus difficile à formuler et c''est celle qui apparaît en dernier — souvent grâce à un élève qui remarque que l''ironie ne s''arrête pas, même sur les passages qui pourraient toucher.\n\n## Le déroulement\n\n1. **Tour complet (8 min)** : A, B ou C, avec un indice. Personne ne répond.\n2. **Discussion (12 min)** : on commence par citer, on conclut par interpréter.\n3. **Trace écrite (5 min)** : l''interprétation retenue et l''objection adverse la plus forte.\n\n## Ce que le débat installe pour l''écrit de la séquence\n\nChaque élève devra choisir, pour son propre texte, une **distance** vis-à-vis de l''enfant qu''il était. Ce débat lui montre qu''il y en a plusieurs, et qu''aucune n''est neutre.\n\nC''est la meilleure préparation possible à l''écriture : on ne discute pas d''un texte pour le commenter, on en discute pour savoir comment écrire le sien.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Donne un avis sans revenir au texte |\n| Satisfaisante | Appuie son interprétation sur un passage précis |\n| Très bonne | Formule l''objection adverse mieux que celui qui la portait |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 58, 2, 127, 'débat argumenté', 'débats littéraires',
 NULL, false, 'Un auteur a-t-il le droit de raconter les autres en racontant sa vie ?',
 'Français', '3e', 'academique',
 'Le corpus de la séquence, où plusieurs auteurs décrivent des membres de leur famille sans leur accord.',
 E'# Débat littéraire — écrire sur les autres\n\n**Vingt-cinq minutes. Le débat porte sur la littérature, et il rejoint le droit.**\n\n---\n\n## La question\n\n> **Un auteur qui écrit sur sa vie a-t-il le droit d''y raconter les autres ?**\n\nElle vient du corpus : les quatre textes étudiés décrivent des parents, des grands-parents, des professeurs — vivants au moment de la publication, et sans leur accord.\n\n## Les positions\n\n**Oui.** Sa vie est faite des autres. Lui interdire d''en parler reviendrait à lui interdire d''écrire sur lui.\n\n**Non.** Ceux qui sont racontés n''ont pas choisi de l''être, ne peuvent pas répondre, et sont reconnaissables par leurs proches.\n\n**Position intermédiaire, qui apparaît toujours.** Cela dépend de ce qu''on raconte : un souvenir partagé n''est pas une révélation, et un défaut moqué n''est pas un fait rapporté.\n\n## Ce qui rend ce débat particulier en 3e\n\nIl **croise l''EMC** de la même année. Les élèves ont travaillé la diffamation et le droit à l''image ; ils disposent d''une distinction utilisable :\n\n| Ce que le droit protège | Ce qu''il sanctionne |\n|---|---|\n| Une opinion, un ressenti, un souvenir | L''imputation d''un fait précis et faux |\n| Ce qui est déjà public | Ce qui relève de la vie privée |\n\nUn élève fera le rapprochement — et s''il ne le fait pas, on le provoque : *est-ce qu''on a vu quelque chose là-dessus cette année ?*\n\n## L''argument qui fait basculer\n\n> « Si quelqu''un écrivait un livre sur son adolescence et qu''on était dedans, on n''aurait rien à dire. »\n\nIl vient d''un élève, et il déplace le débat de l''auteur vers **celui qui est raconté**. C''est le meilleur moment de la discussion.\n\n## La nuance à ne pas laisser passer\n\nUn texte autobiographique **ne raconte pas les autres : il raconte comment l''auteur les a perçus.** Ce n''est pas la même chose, et cela change ce qu''on peut lui reprocher.\n\nUne mère décrite comme distante n''est pas dite distante : elle est dite avoir été perçue comme telle par un enfant. Le texte de Sarraute rend ce partage visible en faisant dialoguer deux voix qui ne sont pas d''accord.\n\nCette distinction est difficile et elle vaut le débat entier.\n\n## Trace écrite\n\nCinq lignes : la position retenue, un exemple pris dans le corpus, et la nuance apportée par la discussion.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Défend une position sans exemple |\n| Satisfaisante | S''appuie sur au moins deux textes du corpus |\n| Très bonne | Distingue raconter quelqu''un et raconter comment on l''a perçu |',
 'termine', now(), now()),

-- ══ Séance 59 — Français : la langue du souvenir ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 59, 1, 136, 'dictée', NULL,
 12, true, 'Dictée préparée : récit, décor et commentaire dans un même paragraphe',
 'Français', '3e', 'academique',
 'Sept lignes composées à partir du corpus autobiographique, annoncées une semaine à l''avance.',
 E'# Dictée préparée — trois temps dans un paragraphe\n\n**Sept lignes, douze verbes conjugués. Annoncée une semaine à l''avance.**\n\n---\n\n## Le texte dicté\n\n> La maison sentait le linge humide. Ma grand-mère refermait la porte derrière moi sans un mot, et je montais l''escalier en comptant les marches. Il y en avait dix-sept ; je les ai comptées pendant douze ans. **Aujourd''hui je sais** qu''elle ne refermait pas la porte contre moi, mais contre le froid. **Je ne l''ai compris qu''après sa mort.**\n\nDouze verbes : cinq à l''imparfait, deux au passé composé, deux au présent, et trois formes secondaires.\n\n## Pourquoi ce texte\n\nIl contient **le basculement**, deux fois, et sans qu''aucun mot ne l''annonce. La phrase change de temps, et c''est tout.\n\nC''est exactement ce que les élèves ne repèrent pas : ils sont dans l''histoire et ils écrivent tout au passé.\n\n---\n\n# Corrigé\n\n## Les trois emplois, verbe par verbe\n\n| Verbe | Temps | Emploi |\n|---|---|---|\n| sentait, refermait, montais, avait | imparfait | Le décor et l''habitude : ce qui se répétait |\n| ai comptées, ai compris | passé composé | Les événements, vus depuis aujourd''hui |\n| sais, refermait (2ᵉ) | présent / imparfait | **Le commentaire de celui qui écrit** |\n\n## Le test\n\n> **Est-ce l''enfant qui vit, ou l''adulte qui écrit ?**\n\nSi c''est l''adulte, le présent s''impose — et rien dans la phrase ne le signale à l''avance.\n\n## Le piège principal : « je les ai comptées »\n\nL''accord du participe passé avec *avoir* : le COD *les* (= les marches) est placé avant, donc accord au féminin pluriel.\n\nC''est une règle vue en 4e, réemployée ici dans un contexte où l''attention est ailleurs. C''est délibéré : une règle ne se maîtrise que quand elle survit à la distraction.\n\n## Le second piège : « douze ans »\n\n*Je les ai comptées pendant douze ans* — « douze ans » n''est pas un COD mais un complément de durée. Il n''entre dans aucun accord.\n\n## Ce qu''on corrige, et rien d''autre\n\nLes temps, et les deux participes passés. Les autres erreurs sont signalées d''un trait dans la marge sans être traitées.\n\nUne dictée dont on corrige tout produit une copie rouge et aucun apprentissage.\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Écrit tout au passé |\n| Fragile | Repère un basculement sur deux |\n| Satisfaisante | Les trois emplois justes, accords traités |\n| Très bonne | Écarte le faux COD « douze ans » |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 59, 2, 134, 'réécriture', NULL,
 3, true, 'Trois passages : ajouter la voix d''aujourd''hui',
 'Français', '3e', 'operationnel',
 'Le premier jet du texte autobiographique, annoté d''un trait dans la marge à trois endroits.',
 E'# Réécriture ciblée — faire entrer l''adulte\n\n**Trois traits dans la marge. Trois raisons différentes.**\n\n---\n\n## Le défaut central des premiers jets\n\nIls sont écrits **du point de vue de l''enfant, sans jamais que l''adulte se manifeste**. Ce sont des récits, pas des textes autobiographiques.\n\nCe n''est pas une faute d''écriture : c''est ce qui vient naturellement. Se souvenir, c''est revivre — et écrire ce qu''on revit produit un récit au présent de l''enfance.\n\n## La grille des trois reprises\n\n| Trait | Ce qui est en cause | Le geste attendu |\n|---|---|---|\n| **Début** | On entre dans la scène sans savoir qui parle ni quand | Poser d''où l''on écrit : aujourd''hui, à quel âge, avec quel recul |\n| **Milieu** | L''enfant explique ce qu''il ressent, avec les mots d''aujourd''hui | Rendre à l''enfant ses mots, et donner à l''adulte une phrase à lui |\n| **Fin** | Le texte s''arrête quand l''épisode s''arrête | Ajouter ce que l''adulte en fait maintenant |\n\n## Trois exemples, avant et après\n\n**Le début sans point de vue**\n\n> *Avant* : « J''avais huit ans et j''habitais chez ma grand-mère. »\n> *Après* : « J''ai passé six étés chez ma grand-mère. Je n''en garde qu''un seul, et je ne suis même pas sûr que ce soit le bon. »\n\nLa seconde version dit d''où l''on parle et installe le doute — qui est le sujet de toute la séquence.\n\n**L''enfant qui parle comme un adulte**\n\n> *Avant* : « Je me sentais rejeté par ma famille, ce qui a affecté ma confiance en moi. »\n> *Après* : « Je restais dans le couloir. Personne ne me disait de venir, et personne ne me disait de partir. Aujourd''hui je crois que personne ne me voyait. »\n\nL''enfant a des gestes, l''adulte a l''analyse. Les mélanger produit le faux le plus fréquent des copies.\n\n**La fin qui s''arrête**\n\n> *Avant* : « Puis les vacances se sont terminées et je suis rentré chez moi. »\n> *Après* : « Puis les vacances se sont terminées. Je n''y suis jamais retourné, et je ne sais toujours pas si c''est moi qui ai décidé cela. »\n\n## La règle matérielle\n\nLa reprise se fait **en couleur, sur le premier jet**. L''élève doit voir ce qu''il a ajouté — et sur cet exercice, ce qui est ajouté est presque toujours ce qui fait le texte.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Recopie, ou corrige seulement l''orthographe |\n| Fragile | Ajoute des commentaires plaqués, tous sur le même modèle |\n| Satisfaisante | Les trois voix distinguées, l''enfant garde ses mots |\n| Très bonne | La phrase ajoutée à la fin change le sens de tout ce qui précède |',
 'termine', now(), now()),

-- ══ Séance 60 — Français : cercle de lecture ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 60, 1, 128, 'cercle de lecture', NULL,
 4, false, 'Quatre écritures de soi, quatre solutions',
 'Français', '3e', 'operationnel',
 'Quatre extraits longs : Sarraute, Sartre, Camus, et un roman graphique autobiographique.',
 E'# Cercle de lecture — quatre solutions au même problème\n\n**Quarante minutes en autonomie. Le professeur ne répond à aucune question de compréhension.**\n\n---\n\n## La question commune\n\n> **Comment cet auteur règle-t-il le problème des deux voix ?**\n\nLe problème a été posé à la première séance. Chaque groupe découvre une solution différente, et aucune n''est la bonne.\n\n## Les quatre textes\n\n| Groupe | Texte | La solution |\n|---|---|---|\n| 1 | *Enfance*, Sarraute | Deux voix dialoguent et se contredisent, sans hiérarchie |\n| 2 | *Les Mots*, Sartre | L''adulte commente sans interruption, avec ironie |\n| 3 | *Le Premier Homme*, Camus | La troisième personne : l''enfant devient un autre |\n| 4 | Un roman graphique autobiographique | Séparation matérielle : le dessin montre l''enfant, le récitatif porte l''adulte |\n\nLe quatrième groupe a le texte le plus accessible et la découverte la plus forte : la séparation des deux voix y est **physique**, sur la page.\n\n## Les quatre rôles\n\nMeneur, gardien du temps, secrétaire, porte-parole — ils tournent d''une séance à l''autre.\n\n## Ce que fait le professeur\n\nIl circule, il écoute, il note. Une question de compréhension lui est renvoyée au meneur du groupe.\n\nCe qu''il a relevé est rendu à la classe en fin de séance : c''est ce retour qui justifie vingt minutes de silence.\n\n## La mise en commun, et la question qui la transforme\n\nUne colonne au tableau : *la solution retenue*. Puis :\n\n> **Laquelle emploieriez-vous pour votre propre texte ?**\n\nCette question change tout : la comparaison devient une décision d''écriture. Les élèves choisissent, et doivent dire pourquoi.\n\n## Ce qu''on observe chaque année\n\nLa troisième solution — la troisième personne — est écartée en discussion (« ça fait bizarre de parler de soi comme quelqu''un d''autre »), puis retenue par deux ou trois élèves qui produisent les meilleurs textes de la séquence.\n\nIl vaut la peine de le remarquer, sans l''annoncer d''avance : c''est la solution qui donne le plus de liberté, précisément parce qu''elle met de la distance.\n\n## Ce qu''on évalue\n\nLe compte rendu du porte-parole. Les notes du secrétaire sont ramassées sans être notées : elles montrent quels groupes ont discuté.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 60, 2, 133, 'écrit d''invention', NULL,
 NULL, true, 'Écrire un souvenir en assumant le point de vue d''aujourd''hui',
 'Français', '3e', 'academique',
 'Le travail final de la séquence, préparé par cinq rituels d''écriture et une réécriture ciblée.',
 E'# Écrit — un souvenir, deux voix\n\n**Deux pages maximum. Deux jets, avec une réécriture ciblée entre les deux.**\n\n---\n\n## Le sujet\n\n> Racontez un souvenir en faisant entendre **deux voix** : celle de l''enfant qui a vécu la scène, et celle de vous aujourd''hui.\n\nLa solution d''écriture est libre : les quatre du cercle de lecture sont disponibles, et une cinquième est autorisée si elle est expliquée.\n\n## Les trois contraintes\n\n1. **Un seul souvenir.** Pas une enfance : un moment.\n2. **Les deux voix doivent être distinguables** par le lecteur — un temps, une typographie, une personne, une mise en page. Le moyen est libre, la distinction ne l''est pas.\n3. **Une chose que l''enfant ne savait pas** doit apparaître. C''est ce qui justifie la seconde voix.\n\n## Ce qui n''est pas demandé, et qu''il faut dire\n\n**On ne demande à personne de raconter quelque chose de difficile.** Un souvenir minuscule — une file d''attente, un trajet en voiture, un objet perdu — donne d''excellents textes.\n\nL''annoncer avant l''écriture libère plus qu''on ne croit : les élèves pensent qu''un texte autobiographique doit être grave, et ils s''inventent des drames.\n\n---\n\n# Corrigé — les trois écueils, et ce qu''on répond\n\n## L''adulte qui explique tout\n\n> *« Je pleurais. Aujourd''hui je comprends que je pleurais parce que j''avais peur d''être abandonné, ce qui est fréquent à cet âge. »*\n\nLa seconde voix ne doit pas **résoudre** le souvenir. Un texte qui explique tout ferme ce qu''il vient d''ouvrir.\n\nLa correction : remplacer l''explication par une constatation. *« Aujourd''hui, je pleure toujours dans les gares. »*\n\n## Les deux voix qui se ressemblent\n\nMême vocabulaire, même longueur de phrase, même ton. Le lecteur ne les distingue pas.\n\nLa correction est concrète : **l''enfant a des gestes et des sensations ; l''adulte a des dates et des conclusions.** Il suffit souvent de retirer les mots abstraits de la voix enfantine.\n\n## Le souvenir emprunté sans le dire\n\nCertains textes racontent un épisode que l''élève ne peut pas avoir en mémoire — il avait deux ans.\n\nCe n''est pas une faute : c''est le sujet de la séquence. La correction consiste à **l''écrire** : *« Je ne me souviens pas de ça. On me l''a raconté si souvent que je le vois. »*\n\nCette phrase, ajoutée, transforme un texte faible en un des meilleurs.\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Un récit d''enfance sans seconde voix |\n| Fragile | Deux voix, mais indistinguables |\n| Satisfaisante | Les deux voix distinguées, une chose que l''enfant ignorait |\n| Très bonne | La seconde voix ouvre au lieu d''expliquer |',
 'termine', now(), now()),

-- ══ Séance 61 — Langues vivantes : le témoignage ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 61, 1, 132, 'lecture à haute voix', NULL,
 NULL, false, 'Lire un témoignage : garder les hésitations',
 'Langues vivantes (étrangères ou régionales)', '3e', 'operationnel',
 'La transcription du témoignage sur le premier emploi, distribuée après les trois écoutes.',
 E'# Reading aloud — keeping the hesitations\n\n**Vingt minutes. On ne lit à voix haute qu''un texte déjà compris.**\n\n---\n\n## Les trois marques habituelles\n\n1. **Barres de souffle** — les élèves respirent à la virgule française, ce qui hache le texte.\n2. **Mots accentués**, deux par groupe — le reste se réduit.\n3. **Contractions entourées** — *I''d*, *she''s*, *wasn''t* se disent en un temps.\n\n## La marque supplémentaire, propre à ce document\n\n**Les hésitations.** Le témoignage en contient trois, laissées telles quelles à l''enregistrement : *well…*, *I mean…*, un silence d''une seconde avant de répondre.\n\nLes élèves veulent les supprimer en lisant. On demande le contraire.\n\n| Où elle est | Ce qu''elle porte |\n|---|---|\n| Avant *I''m not sure yet* | Elle n''est pas sûre, et la voix le dit avant les mots |\n| Après la question sur le salaire | Une gêne, laissée audible |\n| Avant la conclusion | Elle cherche comment finir sans se plaindre |\n\n**Une hésitation n''est pas un défaut de parole : c''est une information.** Lire un témoignage en la supprimant, c''est lisser ce qu''il avait de vrai.\n\nC''est un point de langue et un point de lecture : à l''oral, le sens passe aussi par ce qui n''est pas dit.\n\n## Le déroulement\n\n1. Préparation individuelle des marques (5 min).\n2. Lecture en binômes, l''auditeur ne corrige que les barres, les accents et **la présence des hésitations**.\n3. Quatre volontaires lisent devant la classe.\n\n## Ce qu''on commente, et ce qu''on ne commente pas\n\n**On commente** : le rythme, les pauses, la restitution des hésitations.\n\n**On ne commente pas l''accent.** La règle est annoncée à la classe, et elle change l''atmosphère — surtout en 3e, où la peur du ridicule est à son maximum.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Lit mot à mot, supprime tout ce qui n''est pas une phrase |\n| Satisfaisante | Groupes de souffle respectés, contractions fluides |\n| Très bonne | Restitue les hésitations, et le sens s''entend |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 61, 2, 130, 'compte rendu', NULL,
 6, true, 'Rendre compte du témoignage : ce qu''elle a fait, ce qu''elle envisage',
 'Langues vivantes (étrangères ou régionales)', '3e', 'academique',
 'L''enregistrement de deux minutes écouté trois fois en début de séance.',
 E'# Reporting back — past and future\n\n**Six phrases. Trois au passé, trois sur l''avenir. Third person.**\n\n---\n\n## La consigne\n\n> **Report what she did, and what she is going to do. Six sentences: three about the past, three about the future.**\n\nLa répartition imposée oblige à employer les deux systèmes dans un même texte — ce qu''aucun exercice cloisonné ne fait faire.\n\n## Ce que chaque phrase porte\n\n| Phrase | Contenu |\n|---|---|\n| 1 | Où était le stage, et quand |\n| 2 | Ce qu''elle y faisait concrètement |\n| 3 | Ce qui a été le plus difficile |\n| 4 | Ce qui est **déjà décidé** pour l''an prochain |\n| 5 | Ce qu''elle envisage sans l''avoir décidé |\n| 6 | Ce dont elle n''est pas sûre |\n\nLes phrases 4, 5 et 6 appellent trois formes différentes. C''est la difficulté et c''est l''objectif.\n\n## Le tableau des trois formes\n\n| Ce que la locutrice dit | Forme | Ce que ça signifie |\n|---|---|---|\n| *I''m starting a course in September* | présent progressif | C''est **inscrit**, c''est fait |\n| *I''m going to apply for an apprenticeship* | going to | Décidé, pas encore engagé |\n| *I think I''ll work with children* | will | Une idée, une prédiction sur soi |\n\n**L''erreur à corriger** : employer *will* partout. Elle vient de la règle « will = futur », qui est fausse et qui bloque les trois quarts des emplois réels.\n\n---\n\n# Corrigé\n\n> Last May, she spent a week in a bakery near her home. She started at six in the morning and mostly watched, but she also helped with the packaging. The hardest part was standing up for seven hours — she says nobody had warned her about that. She is starting a first-aid course in September, because the school offers it. She is going to apply for an apprenticeship next year, in a different bakery. She thinks she''ll work with food, but she is not sure yet.\n\n## Les erreurs les plus fréquentes\n\n1. **Le présent au lieu du passé** dans les trois premières phrases : *she spends a week*.\n2. **Le possessif oublié** : *she helped with the packaging in my bakery*.\n3. **Les trois formes du futur ramenées à une seule.**\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Recopie des bribes du document |\n| Satisfaisante | Six phrases, passé et futur distingués |\n| Très bonne | Emploie les trois formes du futur à bon escient |',
 'termine', now(), now()),

-- ══ Séance 62 — Langues vivantes : l'entretien ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 62, 1, 137, 'jeux de rôle', NULL,
 3, false, 'Trois interlocuteurs pour parler de son stage',
 'Langues vivantes (étrangères ou régionales)', '3e', 'operationnel',
 'Cartes de rôles : the recruiter, the school journalist, the cousin who doesn''t get it.',
 E'# Role play — talking about work experience\n\n**Cinq mots-clés, aucune phrase rédigée. Vingt-cinq minutes.**\n\n---\n\n## La contrainte, plus difficile à tenir en 3e\n\nLes élèves veulent bien faire et se réfugient dans l''écrit. Le professeur passe et retourne les feuilles où des phrases complètes apparaissent.\n\n> Exemple au tableau : *bakery — 6 a.m. — bread — customers — tired*\n\n## Les trois cartes\n\n| Carte | Ce que fait l''auditeur | Ce que cela force |\n|---|---|---|\n| **The recruiter** | Demande des exemples précis, prend des notes | Illustrer au lieu d''affirmer |\n| **The school journalist** | Cherche l''anecdote, l''inattendu | Raconter un moment, pas résumer une semaine |\n| **The cousin who doesn''t get it** | Ne comprend pas l''intérêt du métier | Justifier, défendre, expliquer |\n\nLa troisième est la plus productive. Défendre un métier devant quelqu''un qui le trouve sans intérêt oblige à trouver des arguments — et à employer un vocabulaire qu''on n''aurait pas cherché.\n\nElle a aussi un effet secondaire utile : les élèves défendent souvent mieux le métier qu''ils ont observé qu''ils ne l''auraient fait spontanément.\n\n## Les relances, au dos de la carte\n\n- *Can you give me an example?*\n- *What was the hardest part?*\n- *Would you do it again?*\n- *So what are you going to do next year?*\n\nLa dernière fait passer du récit au projet — donc du passé au futur — dans la même conversation. C''est exactement ce que la séquence travaille.\n\n## Le déroulement\n\nDeux tours de trois minutes, puis échange des rôles. Minuteur projeté.\n\nEntre les deux tours, trente secondes de silence : chacun note **un** mot qui lui a manqué. Ces mots forment le lexique de la séance suivante — meilleur qu''une liste préparée d''avance, parce qu''il vient du besoin réel.\n\n## Repères d''évaluation\n\n| Degré | Prise de parole en continu |\n|---|---|\n| Fragile | Phrases isolées, longs silences |\n| Satisfaisante | Deux minutes tenues, exemples concrets |\n| Très bonne | Adapte son récit à l''interlocuteur, et défend son point de vue |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 62, 2, 131, 'mise en voix', NULL,
 3, false, 'Trois prises pour présenter son projet',
 'Langues vivantes (étrangères ou régionales)', '3e', 'operationnel',
 'Les projets travaillés en jeu de rôle, enregistrés sur tablette en fin de séance.',
 E'# Mise en voix — three takes, one kept\n\n**Trois prises d''une minute. L''élève choisit celle qu''il garde.**\n\n---\n\n## Pourquoi trois prises\n\nUne prise unique produit de la panique : c''est un contrôle déguisé. Trois prises produisent du travail.\n\nEt surtout : **c''est lui qui choisit.** Le professeur n''écoute que la prise retenue.\n\n## Le protocole\n\n1. **Prise 1**, tout de suite après le jeu de rôle.\n2. **Écoute au casque**, seul, avec la grille.\n3. **Prise 2**, une seule chose corrigée.\n4. **Prise 3**, une autre chose corrigée.\n5. **Choix**, et une phrase écrite : *pourquoi celle-là*.\n\n## La grille d''auto-écoute\n\n| Ce que j''écoute | Ce que je vérifie |\n|---|---|\n| **Le débit** | Est-ce que je parle trop vite pour être compris ? |\n| **Les silences** | Ai-je un blanc de plus de cinq secondes ? |\n| **La fin** | Est-ce que ça se termine, ou est-ce que ça s''arrête ? |\n\n## Ce qui change en 3e\n\nLe contenu est un **projet personnel**, pas un exercice. Un élève qui s''écoute dire ce qu''il veut faire après la troisième s''entend hésiter — et l''hésitation, cette fois, n''est pas linguistique.\n\nIl faut le savoir et ne pas le commenter. La grille porte sur la parole, pas sur le projet.\n\n## Ce que l''enregistrement change\n\nS''entendre est désagréable, et il faut le dire d''emblée pour désamorcer les rires.\n\nC''est pourtant le seul moyen de sortir d''une illusion tenace : la plupart des élèves croient parler beaucoup plus vite et beaucoup moins bien qu''ils ne le font.\n\nEn pratique, la prise 3 est presque toujours meilleure que la 1 — non parce que l''anglais a progressé en dix minutes, mais parce que le débit s''est calmé.\n\n## Ce qui est évalué\n\nLa prise choisie et la phrase de justification. Un élève qui garde sa prise 2 en expliquant « la 3 était plus fluide mais j''ai oublié de dire ce qui était décidé » a exactement compris ce qu''on lui demandait d''écouter.',
 'termine', now(), now()),

-- ══ Séance 63 — Arts plastiques : le lieu ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 63, 1, 139, 'croquis', NULL,
 2, false, 'Le croquis d''implantation : ce que le lieu impose',
 'Arts plastiques', '3e', 'operationnel',
 'Les quatre lieux du collège repérés en début de séance, et le lieu retenu par chaque groupe.',
 E'# Croquis d''implantation\n\n**Deux croquis : le lieu vu du point de vue principal, et le lieu en plan.**\n\n---\n\n## Ce qu''un croquis d''implantation doit porter\n\n| Élément | Pourquoi |\n|---|---|\n| Les dimensions relevées au mètre ruban | Sans cotes, aucun projet n''est réalisable |\n| **Le point de vue principal**, marqué d''un œil et d''une flèche | C''est de là qu''on verra, donc de là qu''on conçoit |\n| **La hauteur des yeux**, en trait fin | Cette ligne décide de tout : ce qui est au-dessus est vu par en dessous |\n| Ce qui est déjà là | Aucun lieu n''est vide : affiches, traces, habitudes |\n| Le sens de circulation | Un couloir se voit en marchant, de côté |\n\n## Les deux croquis, et leur complémentarité\n\n**Le croquis en vue** montre ce que voit le passant : les proportions, ce qui masque, ce qui attire l''œil.\n\n**Le croquis en plan** montre ce que la vue ne dit pas : d''où l''on arrive, combien de temps on reste, où l''on ne va jamais.\n\nAucun des deux ne suffit. Ensemble, ils décrivent un lieu.\n\n## La ligne d''horizon, qui est le vrai contenu\n\nLa hauteur des yeux — environ 1,60 m pour un élève de 3e — se trace en trait fin sur le croquis en vue.\n\nCe qui est **au-dessus** est vu par en dessous, donc raccourci ; ce qui est **en dessous** est vu par au-dessus, donc étalé. Une intervention posée à 2,50 m n''aura pas la forme qu''on lui a dessinée sur la table.\n\nC''est la découverte de la séance, et elle ne se fait que le crayon à la main.\n\n## Ce que les quatre lieux imposent\n\n| Lieu | Sa contrainte principale |\n|---|---|\n| Couloir du premier étage | Vu trois secondes, de côté, en marchant : il faut du grand et du simple |\n| Angle près du préau | Vu longtemps par ceux qui attendent : il supporte le détail |\n| Cage d''escalier | Deux points de vue opposés, d''en haut et d''en bas |\n| Mur près des casiers | Vu de très près, dans la bousculade : il faut résister au frottement |\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Dessin du lieu sans cotes ni point de vue |\n| Fragile | Croquis cotés, ligne d''horizon absente |\n| Satisfaisante | Les deux croquis, point de vue et hauteur des yeux marqués |\n| Très bonne | Tire du croquis une contrainte que le projet devra respecter |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 63, 2, 144, 'commentaire comparé', NULL,
 2, true, 'Deux œuvres in situ : ce que le lieu fait à l''œuvre',
 'Arts plastiques', '3e', 'academique',
 'Deux références projetées : une intervention de Daniel Buren dans une cour, et un travail de Georges Rousse dans un bâtiment vide.',
 E'# Commentaire comparé — deux œuvres faites pour un lieu\n\n**Deux œuvres qui n''existeraient pas ailleurs. Par quels moyens différents ?**\n\n---\n\n## Les deux œuvres\n\n**A** — Une intervention de Daniel Buren dans une cour : des bandes verticales régulières, posées sur des colonnes de hauteurs différentes.\n**B** — Un travail de Georges Rousse dans un bâtiment désaffecté : des formes peintes sur les murs, le sol et le plafond, qui ne composent une figure géométrique nette **que d''un point unique**.\n\n## La grille\n\n| | Œuvre A | Œuvre B |\n|---|---|---|\n| Qu''est-ce qui a été ajouté au lieu ? | | |\n| D''où faut-il regarder ? | | |\n| Que se passe-t-il si on regarde d''ailleurs ? | | |\n| Que reste-t-il si on la déplace ? | | |\n| Que voit-on du lieu qu''on ne voyait pas avant ? | | |\n\nLa dernière ligne est la plus difficile et la plus importante : une œuvre in situ ne décore pas un lieu, elle le **rend visible**.\n\n---\n\n# Corrigé\n\n## Œuvre A — Buren\n\n**Ajouté** : des bandes régulières, toujours de la même largeur, sur des supports de hauteurs différentes.\n\n**D''où regarder** : de partout. L''œuvre fonctionne sous tous les angles.\n\n**Ailleurs** : elle reste lisible, elle change simplement de rythme.\n\n**Déplacée** : les bandes existeraient encore, mais elles ne diraient plus rien — leur régularité ne mesurerait plus rien.\n\n**Ce qu''on voit du lieu** : **les différences de hauteur**. La bande régulière sert d''étalon ; en la posant partout, elle révèle que rien n''est à la même hauteur. Le lieu paraissait uniforme, il ne l''est pas.\n\n## Œuvre B — Rousse\n\n**Ajouté** : des surfaces peintes, déformées, réparties sur trois plans.\n\n**D''où regarder** : d''un point unique, marqué au sol.\n\n**Ailleurs** : on ne voit que des taches sans forme, réparties sans logique apparente.\n\n**Déplacée** : rien ne subsiste. L''œuvre est indissociable des dimensions exactes de la pièce.\n\n**Ce qu''on voit du lieu** : **sa profondeur**. La figure ne se referme qu''à la distance juste ; en la cherchant, le spectateur mesure la pièce avec son corps.\n\n## Ce que la comparaison fait comprendre\n\n> **Les deux révèlent le lieu, par des moyens opposés.** Buren emploie un étalon constant qui rend les écarts visibles. Rousse emploie une déformation qui n''est corrigée que d''un seul endroit. L''une fonctionne de partout, l''autre d''un point.\n\nAucune des deux, seule, ne permettait cette phrase.\n\n## Le mot interdit\n\n**« Mieux ».** Les deux ne cherchent pas la même chose : l''une veut être vue par tous ceux qui passent, l''autre veut être cherchée.\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Décrit les deux œuvres sans les relier au lieu |\n| Satisfaisante | Remplit la grille, distingue les deux moyens |\n| Très bonne | Formule ce que chaque œuvre révèle du lieu |',
 'termine', now(), now()),

-- ══ Séance 64 — Arts plastiques : intervenir ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 64, 1, 141, 'production audio-visuelle', NULL,
 3, false, 'Trois prises de vue pour documenter ce qui va disparaître',
 'Arts plastiques', '3e', 'operationnel',
 'L''intervention réalisée par chaque groupe dans le lieu choisi, avant son retrait.',
 E'# Documenter une œuvre éphémère\n\n**L''intervention sera retirée à la fin de l''heure. Il n''en restera que ces images.**\n\n---\n\n## Ce que la contrainte a de particulier\n\nCe n''est pas une contrainte matérielle déguisée : c''est le sujet.\n\nUne grande partie de l''art contemporain n''existe plus que par sa documentation. Les élèves en font ici l''expérience directe — et le moment du retrait est ce qui la rend réelle.\n\n## Les trois prises de vue imposées\n\n| Prise | Ce qu''elle montre | Pourquoi elle est obligatoire |\n|---|---|---|\n| **Depuis le point de vue principal** | Ce que voit celui qui passe | C''est pour lui que le travail a été conçu |\n| **De détail** | La matière, le geste, la fabrication | La documentation doit garder trace du faire |\n| **Avec quelqu''un dedans** | L''échelle | Sans corps, une image ne donne aucune taille |\n\n## La troisième prise, celle qu''on oublie\n\nElle est la plus importante pour la documentation. Une intervention de trois mètres et une de trente centimètres se ressemblent sur un écran.\n\nUn corps dans l''image règle la question en une seconde — et c''est exactement ce que les élèves ont découvert en traçant les dimensions des œuvres au mètre sur le mur, en histoire des arts.\n\n## Les erreurs de prise de vue à corriger\n\n| Erreur | Conséquence |\n|---|---|\n| Photographier au flash | La lumière du lieu disparaît, et elle faisait partie du travail |\n| Cadrer serré sur l''intervention seule | On perd le rapport au lieu, donc tout le propos |\n| Photographier depuis l''endroit le plus commode | Ce n''est presque jamais le point de vue principal |\n| Redresser l''image après coup | On corrige la déformation que le lieu imposait |\n\nLa dernière est la plus tentante et la plus dommageable, surtout pour les interventions qui jouent sur un point de vue unique.\n\n## Le choix de l''image qui reste\n\nUne seule photographie par groupe, avec une phrase de justification. La question posée :\n\n> **Laquelle donne à quelqu''un qui n''était pas là l''idée la plus juste de ce qu''on a fait ?**\n\nCe n''est ni la plus belle ni la plus spectaculaire. C''est presque toujours celle qui contient un corps.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Une seule prise, cadrée au hasard |\n| Fragile | Les trois prises, mais sans respecter le point de vue principal |\n| Satisfaisante | Les trois prises conformes, choix justifié |\n| Très bonne | L''image retenue rend compte du travail à quelqu''un qui n''était pas là |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 64, 2, 147, 'micro-fiction', NULL,
 NULL, false, 'Le cartel de l''œuvre disparue, en trois phrases',
 'Arts plastiques', '3e', 'operationnel',
 'La photographie retenue par chaque groupe, à accompagner d''un cartel.',
 E'# Micro-fiction — le cartel de ce qui n''existe plus\n\n**Trois phrases, dans le ton d''un cartel de musée. L''œuvre n''existe plus.**\n\n---\n\n## Ce qu''est un cartel\n\nLe petit texte à côté d''une œuvre, dans un musée. Il porte des informations factuelles — titre, auteur, date, technique — et parfois une phrase de contexte.\n\nIci, il doit faire quelque chose de plus : **rendre compte d''une œuvre que le lecteur ne verra jamais.**\n\n## Les trois phrases\n\n| Phrase | Ce qu''elle porte |\n|---|---|\n| 1 | Les informations : qui, où, quand, avec quoi |\n| 2 | Ce que l''œuvre faisait au lieu |\n| 3 | Ce qui n''est plus, et depuis quand |\n\nLa troisième est celle qui n''existe pas dans un cartel ordinaire. Elle est propre à l''œuvre éphémère, et c''est elle qui donne son ton à l''exercice.\n\n## L''exemple écrit devant les élèves\n\n> *Groupe 3, couloir du premier étage, 14 mai, papier kraft et adhésif repositionnable, 2,40 × 1,10 m.*\n> *Les bandes suivaient la ligne des casiers et s''arrêtaient là où le couloir tourne, si bien qu''on voyait le virage avant d''y arriver.*\n> *Retirée le jour même à 16 h 05. Il n''en reste qu''une photographie et cette phrase.*\n\nLa troisième phrase n''est pas mélancolique : elle est factuelle. C''est ce qui la rend forte.\n\n## Ce qui ne marche pas\n\n> *« On a fait une belle œuvre dans le couloir, c''était vraiment cool et les gens ont aimé. »*\n\nElle ne dit ni ce qui a été fait, ni ce que cela produisait, ni ce qu''il en reste. Un cartel n''est ni un avis ni un bilan : c''est un **relevé**.\n\nLa relance : *que faut-il savoir pour se représenter ce qui a eu lieu ?*\n\n## Le lien avec le français\n\nIl est direct et vaut d''être signalé aux élèves : ils écrivent un texte sur quelque chose de disparu, à partir d''une trace incomplète. C''est exactement le problème de l''écriture de soi qu''ils travaillent en français cette année.\n\nLa photographie joue le rôle du souvenir : elle atteste, elle ne restitue pas.\n\n## L''accrochage final\n\nLes photographies et leurs cartels sont affichés ensemble, en salle d''arts plastiques. C''est **la seule trace** de la séquence, et elle y reste jusqu''à la fin de l''année.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Donne un avis au lieu d''un relevé |\n| Fragile | Les informations, sans ce que l''œuvre faisait au lieu |\n| Satisfaisante | Les trois phrases, ton factuel tenu |\n| Très bonne | Le cartel permet de se représenter une œuvre qu''on n''a pas vue |',
 'termine', now(), now()),

-- ══ Séance 65 — Éducation musicale : l'engagement ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 65, 1, 144, 'commentaire comparé', NULL,
 3, true, 'Trois œuvres engagées : par quels moyens agissent-elles ?',
 'Éducation musicale', '3e', 'academique',
 'Les trois extraits écoutés sans titre ni texte : un chant de résistance, une œuvre orchestrale de commémoration, une chanson contemporaine.',
 E'# Commentaire comparé — trois façons de prendre parti\n\n**Les deux premières écoutes se font sans titre, sans texte, sans contexte.**\n\n---\n\n## Le protocole, et sa raison\n\nDonné avec son titre, un chant de résistance est entendu à travers ce qu''on en sait. Donné nu, il est entendu **pour ce qu''il fait**.\n\nLa seule question de la première écoute :\n\n> **Qu''est-ce que cette musique cherche à produire chez celui qui l''écoute ?**\n\n## Le tableau, rempli collectivement\n\n| | Chant de résistance | Œuvre orchestrale | Chanson contemporaine |\n|---|---|---|---|\n| **Tempo** | de marche, régulier | très lent | proche du parlé |\n| **Registre** | médium, chantable par tous | grave, cordes basses | voix seule très en avant |\n| **Mélodie** | simple, peu d''intervalles, répétée | pas de mélodie mémorisable | presque parlée |\n| **Effectif** | des voix, à l''unisson | orchestre entier | une voix, accompagnement minimal |\n| **Ce que ça produit** | on peut chanter avec | on écoute, immobile | on écoute quelqu''un |\n\n## La ligne qui fait tout comprendre\n\nLa dernière. Les trois œuvres traitent du même type de sujet et produisent trois situations différentes :\n\n- la première fait **un groupe** ;\n- la deuxième fait **une assemblée** ;\n- la troisième fait **un tête-à-tête**.\n\nCe n''est pas une différence de qualité : c''est une différence de **fonction**.\n\n## Ce que la musique ajoute au texte\n\nOn le vérifie, on ne l''affirme pas : le texte du chant est lu à voix haute, sans musique.\n\nL''effet tombe. Les mots restent justes, mais rien ne pousse à les dire ensemble.\n\n**La conclusion à obtenir des élèves** : la musique rend un texte **partageable**. Une mélodie simple, dans un registre accessible, répétée, se chante à plusieurs — c''est ce qui en fait un instrument collectif et pas seulement un message.\n\n## La mise en contexte, en dernier\n\nDate, circonstances, destination. Elle éclaire ce qui vient d''être entendu au lieu de le précéder.\n\nOn découvre alors que la simplicité mélodique du premier extrait n''est pas une pauvreté mais une **condition** : il devait pouvoir être chanté par des gens qui ne l''avaient jamais entendu, une seule fois, et le retenir.\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Ne s''exprime qu''en jugements |\n| Fragile | Décrit avec quelques termes justes |\n| Satisfaisante | Remplit le tableau, distingue les trois fonctions |\n| Très bonne | Relie un choix musical à la situation qu''il produit |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 65, 2, 131, 'mise en voix', NULL,
 2, false, 'Chanter à l''unisson, puis à deux voix : ce que ça change',
 'Éducation musicale', '3e', 'operationnel',
 'Le chant de la séquence, travaillé d''abord à l''unisson puis à deux voix.',
 E'# Mise en voix — l''unisson et les deux voix\n\n**Le même chant, deux traitements. Ce n''est pas le même effet.**\n\n---\n\n## À l''unisson\n\nTout le monde chante la même chose. C''est le traitement du chant de résistance étudié en écoute.\n\n**Ce qu''il produit** : un groupe. Aucune voix ne se distingue, et c''est le but — un chant collectif n''a pas de soliste.\n\n**La difficulté** : elle n''est pas là où on croit. Chanter à l''unisson à vingt-six est plus exigeant qu''à deux voix, parce que **le moindre écart s''entend**. Une voix trop haute ressort immédiatement.\n\n**Le geste qui règle** : chanter moins fort. On l''a installé en 5e sur la pulsation ; il vaut aussi pour la justesse.\n\n## À deux voix\n\nLa classe est partagée. La seconde voix est simple — une tierce en dessous, ou une note tenue.\n\n**Ce qu''il produit** : autre chose. L''ensemble devient plus riche, et **moins mobilisateur**. On écoute au lieu de chanter avec.\n\n## La découverte de la séance\n\nElle se formule d''elle-même quand on enchaîne les deux :\n\n> **Un chant qui veut être repris par tout le monde ne peut pas être à deux voix.**\n\nCe n''est pas une règle esthétique : c''est une conséquence pratique. Une seconde voix demande une répartition, une répétition, quelqu''un qui organise — tout ce qu''un chant destiné à circuler ne peut pas exiger.\n\nLes élèves l''éprouvent en dix minutes, là où une explication n''aurait rien produit.\n\n## Le lien avec l''écoute\n\nIl devient évident : la simplicité de l''extrait entendu n''était pas un manque de moyens. C''était une **condition de sa fonction**.\n\nEt inversement, l''œuvre orchestrale n''avait pas à être chantable : elle était faite pour être écoutée par une assemblée immobile.\n\n## Le point technique à ne pas laisser passer\n\nÀ deux voix, la voix grave a tendance à suivre la voix aiguë. On travaille les deux séparément, puis on les superpose lentement, sans accompagnement — l''accompagnement masquerait le problème au lieu de le résoudre.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Ne tient pas sa voix quand l''autre entre |\n| Satisfaisante | Tient sa partie, justesse correcte |\n| Très bonne | Sait dire ce que chaque traitement produit, et pourquoi |',
 'termine', now(), now()),

-- ══ Séance 66 — Éducation musicale : changer le camp ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 66, 1, 143, 'montage numérique', NULL,
 2, true, 'Deux versions d''un même texte, deux effets opposés',
 'Éducation musicale', '3e', 'operationnel',
 'Le texte et la mélodie fournis en fichiers séparés, sur les six postes équipés d''un séquenceur.',
 E'# Montage — changer le camp d''une chanson\n\n**Le texte ne change pas d''un mot. Seule la musique change.**\n\n---\n\n## Ce que la consigne démontre\n\nSi deux versions d''un même texte peuvent produire des effets opposés — et elles le peuvent — alors la musique ne se contente pas d''accompagner un propos : **elle en décide une part**.\n\nC''est une démonstration, pas une opinion, et les élèves la produisent eux-mêmes.\n\n## La fiche, avant le logiciel\n\n> **Version 1 — effet visé** : ……  **trois moyens** : ……\n> **Version 2 — effet visé** : ……  **trois moyens** : ……\n\nUn binôme qui ouvre le séquenceur sans avoir rempli la fiche est renvoyé au papier.\n\n## Les moyens, et leurs contraires\n\n| Moyen | Un effet | L''effet opposé |\n|---|---|---|\n| Tempo | rapide : entraînant, décidé | lent : grave, résigné |\n| Registre | aigu : clair, léger | grave : pesant |\n| Accompagnement | dense : collectif, majestueux | nu : intime, fragile |\n| Voix | plusieurs à l''unisson : un groupe parle | une seule, proche : une personne parle |\n| Fin | suspendue : la question reste | conclusive : l''affaire est réglée |\n\n---\n\n# Corrigé — ce que les binômes obtiennent\n\n## La version « appel »\n\nTempo de marche, plusieurs voix à l''unisson, accompagnement dense, fin conclusive.\n\nElle est entendue comme **une mobilisation**. Le texte devient un mot d''ordre.\n\n## La version « constat »\n\nTempo lent, une seule voix proche du micro, presque rien derrière, fin suspendue.\n\nElle est entendue comme **un témoignage**, parfois comme un deuil. Le même texte devient une confidence.\n\n## Le moyen qui décide, et celui qui ne change rien\n\nÀ l''écoute à l''aveugle, on identifie ce qui a produit le basculement :\n\n- **L''effectif vocal** est décisif : une voix seule ou plusieurs, c''est ce qui distingue une personne d''un groupe.\n- **Le tempo** compte beaucoup.\n- **Le registre** compte peu — les binômes qui n''ont joué que là-dessus n''obtiennent pas d''effet net.\n\nCe classement n''est pas donné : il sort de la comparaison des productions.\n\n## La question qui reste ouverte\n\n> **Est-ce que la musique peut trahir un texte ?**\n\nOn ne tranche pas. Un texte de résistance mis en berceuse choque certains élèves et pas d''autres — et la discussion vaut mieux qu''une réponse.\n\nElle rejoint, sans qu''on ait besoin de le souligner, ce qu''ils travaillent en histoire des arts sur les œuvres de commande.\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Une seule version, ou aucune intention écrite |\n| Fragile | Deux versions peu différenciées |\n| Satisfaisante | Deux effets opposés obtenus, moyens identifiables |\n| Très bonne | Sait dire quel moyen a produit le basculement, et lequel n''a rien changé |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 66, 2, 142, 'playlist', NULL,
 6, false, 'Six morceaux, du mot d''ordre à la question ouverte',
 'Éducation musicale', '3e', 'operationnel',
 'La banque d''écoutes de l''année et les trois extraits de la séquence.',
 E'# Playlist — six façons de prendre parti\n\n**Un fil annoncé, une phrase de justification par morceau, un ordre nécessaire.**\n\n---\n\n## Les fils proposés\n\n| Fil | Ce qu''il fait chercher |\n|---|---|\n| Du mot d''ordre à la question ouverte | Ce que le texte demande à l''auditeur |\n| Du chant collectif au témoignage individuel | L''effectif, et la situation qu''il crée |\n| Six façons de dire non | La diversité des moyens pour un même propos |\n| De la colère à l''ironie | Le registre de l''engagement |\n\nLe premier est le plus exigeant et le plus riche. Il demande d''écouter **ce que la chanson attend de celui qui l''écoute** — reprendre en chœur, réfléchir, se souvenir, se décider.\n\n## Ce qui distingue une playlist d''une liste\n\n**L''ordre.**\n\n> Test : si j''échange le morceau 2 et le morceau 5, est-ce que quelque chose se casse ?\n\nSi la réponse est non, le fil n''existe pas.\n\n**La justification.** Elle porte sur la musique et sur la fonction, pas sur le goût. « Je l''ai mis en cinquième parce que c''est le premier où la voix est seule » se discute ; « je l''aime bien » ne se discute pas.\n\n## Un exemple complet\n\n**Fil : du mot d''ordre à la question ouverte.**\n\n1. Un chant repris en chœur, refrain de quatre notes — il demande qu''on le chante.\n2. Une chanson à refrain, mais avec des couplets narratifs — il demande qu''on écoute une histoire.\n3. Une chanson sans refrain, forme continue — on ne peut plus reprendre, seulement suivre.\n4. Un texte presque parlé sur un accompagnement minimal — il demande qu''on écoute quelqu''un.\n5. Une œuvre instrumentale de commémoration — elle ne demande rien, elle installe un état.\n6. Une pièce qui s''arrête sans conclure — elle laisse la question à l''auditeur.\n\nSix étapes, une progression continue. Échanger deux morceaux casse la marche.\n\n## Ce que l''exercice apprend, au-delà de la musique\n\nUne œuvre engagée n''a pas une seule forme. Le mot d''ordre et la question ouverte s''adressent à des auditeurs différents, dans des situations différentes — et l''un n''est pas plus sincère que l''autre.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Six morceaux sans fil, ou un fil thématique |\n| Fragile | Fil annoncé, justifications par le goût |\n| Satisfaisante | Le fil tient sur les six, justifications musicales |\n| Très bonne | L''ordre est nécessaire, et l''élève sait dire ce qui se casserait |',
 'termine', now(), now());
