-- ============================================================================
-- college4e — 5e, partie 3/3 (a) : les activités des séances 29 à 38
--
-- Français, langues vivantes, arts plastiques, éducation musicale.
-- Trois des six précisions du référentiel se posent ici : compte rendu de
-- lecture, débats interprétatifs et débats littéraires.
-- ============================================================================

INSERT INTO activites (user_id, seance_id, position, activite_type_id, activite_label, sous_type,
                       nb, avec_correction, objet, matiere, niveau, ton, texte_source, resultat,
                       statut, created_at, updated_at) VALUES

-- ══ Séance 29 — Français : pourquoi part-on ? ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 29, 1, 130, 'compte rendu', 'compte rendu de lecture',
 NULL, true, 'Rendre compte des trois premiers chapitres sans raconter l''intrigue',
 'Français', '5e', 'academique',
 'Les trois premiers chapitres du roman d''aventure lu en œuvre intégrale.',
 E'# Compte rendu de lecture — les trois premiers chapitres\n\n**Une page. Trente minutes en classe, le reste à la maison.**\n\n---\n\n## La consigne\n\nRendre compte des trois premiers chapitres **sans raconter ce qui s''y passe**.\n\nCela paraît impossible et ne l''est pas : un compte rendu n''est pas un résumé. Il donne à quelqu''un de quoi décider s''il va lire, et garde trace de ce qu''on y a trouvé.\n\n## Les quatre parties\n\n**1. La situation de départ, trois lignes.** Qui, où, quand — on s''arrête avant le départ.\n\n**2. Le personnage, en trois traits appuyés sur le texte.** Pas « il est courageux » mais « il ment à sa mère au chapitre 2 et le texte ne le lui reproche pas ».\n\n**3. Un passage qu''on a dû relire.** Lequel, et pourquoi il a arrêté. Obligatoire : un lecteur qui n''a jamais buté n''a pas vraiment lu.\n\n**4. Ce qu''on en dit à quelqu''un qui hésite.** Cinq lignes, sans révéler ce qui arrive.\n\n## Ce qui est interdit\n\n- Raconter les péripéties, même à demi-mot.\n- Écrire « c''est bien » sans dire ce qui est bien.\n- Recopier une notice trouvée en ligne : elles racontent toutes l''intrigue, ce que la consigne interdit — elles se repèrent immédiatement.\n\n---\n\n# Corrigé — un compte rendu attendu\n\n## 1. La situation\n\nUn port, au début du siècle dernier. Le narrateur a quinze ans, vit avec sa mère dans une auberge à l''écart, et n''a jamais quitté la région.\n\n## 2. Le personnage, en trois traits\n\n**Il observe plus qu''il ne parle.** Les trois chapitres sont pleins de descriptions de gens et vides de ses propres répliques.\n\n**Il ment sans que le texte le juge.** Au chapitre 2, il cache une information à sa mère. Le narrateur le rapporte sans commentaire — c''est un choix d''écriture, pas un oubli.\n\n**Il s''ennuie, et il ne le dit jamais.** Le mot n''apparaît pas. On le comprend au nombre de fois où il décrit ce qu''il voit par la fenêtre.\n\n## 3. Le passage relu\n\nCelui où un client de l''auberge parle de la mer sans jamais dire où il est allé. À la première lecture, c''est un dialogue ordinaire ; à la seconde, on comprend qu''il évite les questions.\n\n## 4. À quelqu''un qui hésite\n\nLes trois premiers chapitres ne contiennent aucune aventure : ils installent un garçon qui regarde par la fenêtre et une auberge où passent des gens qui ont vu autre chose. C''est ce qui rend le départ, quand il arrive, plus fort que si le livre avait commencé par lui.\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Raconte l''intrigue malgré la consigne |\n| Fragile | L''évite mais reste général : « il est courageux », « c''est bien » |\n| Satisfaisante | Trois traits appuyés sur des passages précis |\n| Très bonne | Relie deux passages éloignés pour en tirer une remarque |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 29, 2, 135, 'rituel d''écriture', NULL,
 5, false, 'Cinq minutes, un objet rapporté de voyage',
 'Français', '5e', 'operationnel',
 'Rituel hebdomadaire de début de séance, cinq minutes chronométrées, cahier d''écriture personnel jamais noté.',
 E'# Rituel d''écriture — l''objet rapporté\n\n**Tous les lundis, cinq minutes chronométrées. Le cahier n''est jamais noté.**\n\n---\n\n## Le principe\n\nUn objet est posé sur le bureau. Cinq minutes d''écriture sans lever le stylo, une consigne unique :\n\n> **Écrivez d''où vient cet objet et comment il est arrivé ici — sans le décrire.**\n\nÀ la fin, personne ne lit sauf volontaire. Le cahier est ramassé une fois par trimestre et n''est jamais noté.\n\n## Pourquoi cette consigne pendant cette séquence\n\nElle prolonge le travail sur le voyage : un objet rapporté porte un trajet. Écrire ce trajet, c''est inventer un récit d''aventure en cinq lignes, sans avoir à l''appeler ainsi.\n\n**Interdire la description** est ce qui fait travailler. Sans cet interdit, on obtient « c''est un coquillage blanc avec des rayures » et l''élève s''arrête, satisfait.\n\n## Les cinq objets du trimestre\n\n| Semaine | L''objet | Ce qu''il fait chercher |\n|---|---|---|\n| 1 | Un coquillage percé, enfilé sur un fil usé | Qui l''a percé, et pourquoi le garder si longtemps |\n| 2 | Un billet de bateau dans une langue inconnue | Le trajet, la date, celui qui n''a pas jeté le billet |\n| 3 | Une pièce de monnaie qui n''a plus cours | La valeur perdue, et ce qui reste |\n| 4 | Une carte pliée jusqu''à se déchirer aux plis | L''usage : une carte qu''on a beaucoup ouverte |\n| 5 | Une clé qui n''ouvre plus rien | Ce qu''on garde d''un lieu qu''on a quitté |\n\n## Trois débuts écrits par des élèves\n\n> *Il l''a percé lui-même, avec un clou, le premier soir. Il n''avait rien d''autre à faire et il ne voulait pas dormir.*\n\n> *La carte a été ouverte quarante fois. Trente-neuf pour savoir où on allait, une pour savoir où on était.*\n\n> *La clé n''ouvre plus rien parce que la maison a été vendue. Elle est dans le tiroir avec les choses qu''on ne jette pas.*\n\nAucun ne décrit l''objet. Tous partent d''un détail matériel et arrivent à une personne.\n\n## Ce que le rituel produit\n\nAu bout de cinq semaines, la moitié de la classe écrit sans hésiter pendant les cinq minutes, contre trois ou quatre élèves au départ.\n\nLe bénéfice n''est pas le texte : c''est la disparition du blocage devant la page blanche, qui se transporte ensuite dans les travaux notés.\n\n**La règle qui rend cela possible est de ne pas noter**, et elle est rappelée chaque fois. Un rituel noté redevient un exercice, et un exercice réveille l''angoisse qu''on cherche à défaire.',
 'termine', now(), now()),

-- ══ Séance 30 — Français : fiction et voyage réel ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 30, 1, 127, 'débat argumenté', 'débats interprétatifs',
 NULL, false, 'Le personnage part-il vraiment pour la raison qu''il donne ?',
 'Français', '5e', 'academique',
 'Le chapitre du départ, relu à voix haute, et le relevé des motifs de la séance précédente.',
 E'# Débat interprétatif — le motif du départ\n\n**Vingt-cinq minutes, en cercle. Un tour de parole complet avant toute discussion.**\n\n---\n\n## La question\n\n> **Le personnage part-il vraiment pour la raison qu''il donne ?**\n\nElle ne se tranche pas par un relevé : le texte donne une raison explicite, et sème ailleurs de quoi en douter.\n\n## Les trois lectures en présence\n\n**A — Il part pour la raison qu''il dit.** Le texte l''écrit, personne ne le contredit, et lui prêter des arrière-pensées est une invention du lecteur.\n\n**B — Il part pour fuir.** Trois passages du début décrivent ce qu''il supporte mal ; le départ arrive juste après le pire d''entre eux.\n\n**C — Il ne le sait pas lui-même.** Le texte ne tranche pas, et c''est volontaire : à quinze ans, on part sans savoir pourquoi.\n\n## Le déroulement\n\n**1. Tour complet (8 min).** Chacun annonce A, B ou C avec **un** indice. Personne ne répond encore : ce tour lent empêche que trois élèves tiennent la salle.\n\n**2. Discussion (12 min).** Règle affichée : *on commence par citer, on conclut par interpréter.* Un élève qui commence par « moi je pense » est invité à reprendre par le texte.\n\n**3. Trace écrite (5 min).** L''interprétation retenue **et** l''argument adverse le plus fort. Les deux comptent également.\n\n## Ce que le texte permet d''opposer\n\n| Lecture | L''indice le plus solide | Sa limite |\n|---|---|---|\n| A | La raison est écrite, en toutes lettres | Un personnage peut se tromper sur lui-même |\n| B | Le départ suit immédiatement une scène pénible | La succession n''est pas une cause |\n| C | Le narrateur ne commente jamais la décision | Un texte qui ne commente pas ne dit pas forcément qu''on ne sait pas |\n\nLa colonne de droite fait la valeur du débat : **chaque lecture a un point faible, et le trouver n''est pas perdre.**\n\n## Ce qui se produit presque toujours\n\nDeux ou trois élèves changent d''avis en cours de discussion. On le rend visible et on le salue — c''est le seul moment de l''année où changer d''avis est présenté comme une réussite.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Donne un avis sans revenir au texte |\n| Satisfaisante | Appuie son interprétation sur un passage précis |\n| Très bonne | Formule l''objection adverse mieux que celui qui la portait |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 30, 2, 127, 'débat argumenté', 'débats littéraires',
 NULL, false, 'Un récit de voyage réel est-il moins intéressant qu''un roman d''aventure ?',
 'Français', '5e', 'academique',
 'Le corpus de la séquence : trois chapitres du roman et deux extraits de carnets de voyage authentiques.',
 E'# Débat littéraire — le réel contre l''inventé\n\n**Vingt-cinq minutes. Le débat porte sur la littérature, pas sur un texte particulier.**\n\n---\n\n## La question\n\n> **Un récit de voyage réellement fait est-il moins intéressant qu''un roman d''aventure ?**\n\nElle vient des élèves : après la lecture comparée, une partie de la classe trouve les carnets « moins bien » parce qu''il n''y arrive « rien ».\n\n## Les positions\n\n**Oui.** Dans un roman, tout est choisi : les dangers arrivent au bon moment, la fin ferme l''histoire. Un carnet contient des attentes, des trajets ratés, des repas médiocres.\n\n**Non.** C''est précisément ce qui fait sa valeur : ce qui est arrivé sans être choisi. Et on sait que c''est vrai, ce qui change la lecture.\n\n**Position intermédiaire, qui apparaît toujours.** Les deux ne cherchent pas la même chose. Le roman veut tenir en haleine ; le carnet veut rapporter.\n\n## L''argument qui fait basculer\n\nIl vient d''un élève, et il vaut d''être attendu :\n\n> « Dans le carnet, quand il a peur, on sait qu''il a eu peur pour de vrai. Dans le roman, on sait que l''auteur a décidé qu''il aurait peur. »\n\nC''est une remarque de lecteur, et elle est juste. Elle ouvre la seule conclusion qui tienne : **ce n''est pas la même confiance qu''on accorde aux deux textes.**\n\n## Le contre-argument à ne pas laisser passer\n\nUn carnet de voyage est **écrit après**, souvent des mois plus tard, et il est publié. Il choisit lui aussi ce qu''il raconte.\n\nLes élèves l''oublient : « réel » ne veut pas dire « non écrit ». Nicolas Bouvier ou Ella Maillart sont des écrivains — ils composent, coupent, ordonnent.\n\nCette nuance est la plus difficile de la séance et c''est celle qui vaut le plus.\n\n## Trace écrite\n\nCinq lignes : la position retenue, un exemple pris dans le corpus, et la nuance apportée par le débat.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Défend un goût sans exemple |\n| Satisfaisante | Appuie sa position sur au moins deux textes du corpus |\n| Très bonne | Admet qu''un récit réel est aussi composé, sans abandonner sa position |',
 'termine', now(), now()),

-- ══ Séance 31 — Français : la langue du récit ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 31, 1, 136, 'dictée', NULL,
 11, true, 'Dictée préparée : imparfait et passé simple dans le récit',
 'Français', '5e', 'academique',
 'Six lignes composées à partir du roman lu en classe, annoncées une semaine à l''avance.',
 E'# Dictée préparée — six lignes, onze verbes\n\n**Le texte est annoncé une semaine avant : les élèves savent ce qui est travaillé, pas ce qui sera dicté mot pour mot.**\n\n---\n\n## Le texte\n\n> Le vent soufflait depuis le matin. Il attacha la corde, vérifia le nœud deux fois, puis se retourna. Personne ne le regardait. Il descendit sans bruit, longea le mur, et disparut avant que quelqu''un pût donner l''alerte.\n\nOnze verbes conjugués : six au passé simple, trois à l''imparfait, un au subjonctif imparfait — laissé exprès, il ne sera pas exigé mais il sera expliqué.\n\n## Le protocole\n\n1. Lecture intégrale, stylos posés.\n2. Dictée par groupes de souffle, deux fois chacun.\n3. Relecture complète, lentement.\n4. **Cinq minutes de relecture guidée** : « cherchez les verbes conjugués », rien de plus.\n\nLe quatrième temps installe le geste qu''on veut voir survivre : relire en cherchant **une seule chose**.\n\n---\n\n# Corrigé\n\n## Les verbes, un par un\n\n| Verbe | Temps | Pourquoi |\n|---|---|---|\n| soufflait | imparfait | le décor : supprimé, l''histoire avance quand même |\n| attacha, vérifia, se retourna | passé simple | trois actions successives, l''histoire avance |\n| regardait | imparfait | l''état du monde autour, pas un événement |\n| descendit, longea, disparut | passé simple | la suite des actions |\n| pût | subjonctif imparfait | expliqué, non exigé — il signale une action empêchée |\n\n## Le test qu''on installe\n\n> **Si je supprime la phrase, l''histoire avance-t-elle quand même ?**\n\nSi oui, c''était de l''imparfait. C''est une règle utilisable, contrairement à « imparfait pour la description » — *il marcha pendant trois heures* est une action longue au passé simple, et *il pleuvait* est un état bref.\n\n## Les terminaisons, après le repérage\n\n| Groupe | Passé simple, 3ᵉ personne du singulier |\n|---|---|\n| 1ᵉʳ (chanter) | il chant**a** |\n| 2ᵉ (finir) | il fin**it** |\n| 3ᵉ (descendre) | il descend**it** |\n| 3ᵉ (courir, vouloir) | il cour**ut**, il voul**ut** |\n\nElles se travaillent **après** le repérage. Conjuguer avant d''avoir compris à quoi sert le temps ne produit rien.\n\n## Ce qu''on corrige, et rien d''autre\n\nUniquement les verbes conjugués. Les autres erreurs sont signalées d''un trait dans la marge, sans être traitées : une dictée dont on corrige tout produit une copie rouge et aucun apprentissage.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | N''identifie pas les verbes conjugués |\n| Fragile | Les identifie, alterne au hasard |\n| Satisfaisante | Applique le test « l''histoire avance-t-elle ? » |\n| Très bonne | Écrit correctement les terminaisons du 3ᵉ groupe |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 31, 2, 134, 'réécriture', NULL,
 3, true, 'Trois passages à reprendre dans son épisode d''aventure',
 'Français', '5e', 'operationnel',
 'Le premier jet de l''épisode d''aventure, annoté d''un simple trait dans la marge à trois endroits.',
 E'# Réécriture ciblée — trois passages, pas la copie entière\n\n**On ne réécrit jamais tout. Trois traits dans la marge, trois raisons différentes.**\n\n---\n\n## Pourquoi trois passages seulement\n\nUn premier jet rendu couvert d''annotations est recopié au propre, sans une idée nouvelle. La réécriture n''a lieu que si elle est **bornée**.\n\nLes traits sont posés par le professeur ; la raison n''est pas écrite. C''est à l''élève de la trouver, avec la grille.\n\n## La grille\n\n| Trait | Ce qui est en cause | Le geste attendu |\n|---|---|---|\n| **Début** | L''aventure commence à la première ligne | Poser d''abord ce qui manque au personnage |\n| **Milieu** | L''obstacle est franchi trop vite | Faire échouer une première tentative |\n| **Fin** | Le personnage revient comme il est parti | Changer une chose en lui, une seule |\n\n## Trois exemples, avant et après\n\n**Le début qui commence trop tôt**\n\n> *Avant* : « Je suis parti à l''aventure un matin de juin. »\n> *Après* : « Depuis trois ans, je regardais les bateaux partir sans jamais monter dedans. »\n\nLa seconde version ne raconte pas encore le départ — et c''est pour cela qu''on veut lire la suite.\n\n**L''obstacle franchi trop vite**\n\n> *Avant* : « La porte était fermée, alors j''ai trouvé la clé et je suis entré. »\n> *Après* : « La porte était fermée. J''ai cherché la clé pendant une heure. Je suis entré par la fenêtre, et je me suis coupé la main. »\n\nUn obstacle qui se franchit en une phrase n''était pas un obstacle.\n\n**Le retour sans changement**\n\n> *Avant* : « Je suis rentré chez moi et tout était comme avant. »\n> *Après* : « Je suis rentré chez moi. Ma mère m''a demandé où j''étais, et pour la première fois j''ai dit la vérité. »\n\nC''est la reprise la plus difficile, et celle qui transforme le texte : **ce qu''on rapporte d''un voyage n''est presque jamais ce qu''on était parti chercher** — le fil de toute la séquence.\n\n## La règle matérielle\n\nLa reprise se fait **en couleur, sur le premier jet**, jamais sur une feuille neuve. L''élève doit voir ce qu''il a changé.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Recopie, ou corrige seulement l''orthographe |\n| Fragile | Modifie les trois passages sans traiter le problème |\n| Satisfaisante | Trouve seul la raison de deux traits sur trois |\n| Très bonne | La fin modifiée change le sens de tout l''épisode |',
 'termine', now(), now()),

-- ══ Séance 32 — Français : cercle de lecture ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 32, 1, 128, 'cercle de lecture', NULL,
 4, false, 'Quatre récits de départ, quatre groupes, une question commune',
 'Français', '5e', 'operationnel',
 'Quatre extraits longs : Stevenson, Verne, Tournier, et un carnet de voyage contemporain.',
 E'# Cercle de lecture — ce qu''on trouve sans l''avoir cherché\n\n**Quarante minutes en autonomie. Le professeur ne répond à aucune question de compréhension.**\n\n---\n\n## La question commune\n\n> **Qu''est-ce que le héros trouve, qu''il ne cherchait pas ?**\n\nElle prolonge la première séance : on part pour une raison, et l''aventure donne autre chose. C''est ce décalage qui fait le récit d''aventure, et non l''accumulation des dangers.\n\n## Les quatre extraits\n\n| Groupe | Récit | Ce qui est trouvé sans être cherché |\n|---|---|---|\n| 1 | *L''Île au trésor* | Ce que valent les adultes en qui il avait confiance |\n| 2 | *Le Tour du monde en 80 jours* | Qu''un pari peut compter moins qu''une personne |\n| 3 | *Vendredi ou la vie sauvage* | Qu''il n''était pas obligé de refaire son ancien monde |\n| 4 | Carnet de voyage contemporain | Que ce qui reste n''est presque jamais ce qui était prévu |\n\n## Les quatre rôles\n\n| Rôle | Ce qu''il fait | Ce qu''il ne fait pas |\n|---|---|---|\n| **Meneur** | Pose la question, relance, distribue la parole | Donner son avis en premier |\n| **Gardien du temps** | Annonce la mi-temps et les deux dernières minutes | Décider qu''on passe à autre chose |\n| **Secrétaire** | Note les accords **et** les désaccords non résolus | Trier ce qui mérite d''être noté |\n| **Porte-parole** | Rend compte en deux minutes | Lire les notes du secrétaire |\n\nLes rôles tournent d''une séance à l''autre.\n\n## Ce que fait le professeur\n\nIl circule, il écoute, il note — et il ne répond à aucune question de compréhension. Une question qui lui est adressée est renvoyée au meneur.\n\nCe qu''il a relevé est **rendu à la classe en fin de séance**. C''est ce retour qui justifie vingt minutes de silence.\n\n## La mise en commun\n\nUne seule colonne au tableau : *ce qui est trouvé sans avoir été cherché*.\n\nLa comparaison sort d''elle-même : dans les quatre récits, ce qui est trouvé porte sur **les autres ou sur soi**, jamais sur l''objet du départ. Le trésor, quand il existe, arrive en dernier et compte peu.\n\n## Ce qu''on évalue\n\nLe compte rendu du porte-parole. Les notes du secrétaire sont ramassées sans être notées : elles montrent quels groupes ont discuté et lesquels se sont partagé le travail en silence.',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 32, 2, 133, 'écrit d''invention', NULL,
 NULL, true, 'Écrire l''épisode : un obstacle, une tentative ratée, un passage',
 'Français', '5e', 'academique',
 'Le travail final de la séquence, préparé par le rituel d''écriture et la séance de réécriture.',
 E'# Écrit d''invention — un épisode d''aventure\n\n**Deux pages maximum. Deux jets, avec une réécriture ciblée entre les deux.**\n\n---\n\n## Le sujet\n\n> Écrivez l''épisode où votre personnage rencontre **un obstacle qu''il ne franchit pas du premier coup**.\n\nLa contrainte est là et pas ailleurs : l''échec de la première tentative. C''est ce qui sépare un récit d''aventure d''une suite d''événements.\n\n## Les trois contraintes\n\n1. **Un seul obstacle.** Pas trois dangers empilés : un, traité jusqu''au bout.\n2. **Une tentative qui échoue**, racontée en entier — pas résumée en une phrase.\n3. **Un changement de méthode**, pas un coup de chance. Le personnage réussit parce qu''il s''y prend autrement, pas parce qu''un allié surgit.\n\nLa troisième contrainte est celle qui coûte le plus. Elle interdit l''intervention providentielle, qui est la solution de facilité de tous les premiers jets.\n\n---\n\n# Corrigé — les trois écueils, et ce qu''on répond\n\n## « Je n''ai pas d''idée d''obstacle »\n\nRéponse concrète : reprendre le cahier de rituel. Cinq objets y ont produit cinq amorces — une carte déchirée aux plis, une clé qui n''ouvre plus rien. Chacune contient un obstacle tout fait.\n\n## L''obstacle qui n''en est pas un\n\n> *« Le pont était cassé. J''ai fait le tour et je suis passé. »*\n\nCe n''est pas un obstacle : c''est un détour. Le test à donner : **le personnage a-t-il dû changer quelque chose à lui-même, ou seulement à son trajet ?**\n\n## Le sauveur providentiel\n\n> *« Je n''y arrivais pas, mais un vieux marin est arrivé et m''a montré comment faire. »*\n\nCe n''est pas interdit — c''est un ressort classique. Mais si le vieux marin arrive **au moment exact** où le personnage échoue, le lecteur ne croit plus à rien.\n\nLa correction : le faire apparaître **avant** l''échec, dans une scène où il ne sert à rien. Le lecteur l''a vu, il l''a oublié, et son retour devient satisfaisant au lieu d''être commode.\n\nC''est une règle d''écriture qui vaut bien au-delà de cet exercice : **ce qui sauve doit avoir été montré avant d''être utile.**\n\n---\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Une suite d''événements sans obstacle identifiable |\n| Fragile | Un obstacle, franchi du premier coup |\n| Satisfaisante | Une tentative ratée racontée en entier, puis un changement de méthode |\n| Très bonne | Ce qui permet la réussite avait été introduit plus tôt, sans en avoir l''air |',
 'termine', now(), now()),

-- ══ Séance 33 — Langues vivantes : comprendre puis lire ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 33, 1, 132, 'lecture à haute voix', NULL,
 NULL, false, 'Lire la transcription : souffle, accents, contractions',
 'Langues vivantes (étrangères ou régionales)', '5e', 'operationnel',
 'La transcription de la description de journée, distribuée après les trois écoutes.',
 E'# Reading aloud — rhythm before accent\n\n**Vingt minutes. On ne lit à voix haute qu''un texte déjà compris.**\n\n---\n\n## L''ordre, qui n''est pas négociable\n\nLa lecture arrive **après** les trois écoutes et le classement des formes verbales. Lire ce qu''on ne comprend pas produit une récitation plate et n''apprend rien.\n\n## Les trois marques au crayon\n\n**1. Les barres de souffle**\n\n> *I get up at seven | and I have breakfast | with my little brother.*\n\nLes élèves respirent à la virgule française, ce qui hache le texte anglais. Les barres se posent aux articulations de sens.\n\n**2. Les mots accentués, soulignés** — deux par groupe, pas davantage.\n\n> *I get **up** at **seven** | and I have **breakfast** | with my little **brother**.*\n\nLe reste s''efface : les syllabes non accentuées se réduisent, et c''est ce qui rend le rythme anglais reconnaissable.\n\n**3. Les contractions, entourées** — *I''m*, *don''t*, *she''s* se disent en un seul temps. C''est l''erreur la plus fréquente et la plus facile à corriger.\n\n## Le déroulement\n\n1. Préparation individuelle des trois marques (5 min).\n2. Lecture en binômes : l''un lit, l''autre suit et ne corrige **que** les barres et les accents.\n3. Quatre volontaires lisent devant la classe.\n\n## Ce qu''on commente, et ce qu''on ne commente pas\n\n**On commente** : le rythme, les pauses, les mots mis en avant, la fluidité des contractions.\n\n**On ne commente pas l''accent.** Un élève à qui l''on dit que son accent n''est pas bon cesse de parler — et ce silence coûte bien plus cher que quelques voyelles approximatives.\n\nLa règle est annoncée à la classe, et elle change l''atmosphère de l''exercice, surtout pour ceux qui n''osent pas.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Lit mot à mot, respire à chaque virgule |\n| Satisfaisante | Respecte les groupes de souffle, marque quelques accents |\n| Très bonne | Rythme naturel, contractions fluides, le sens s''entend |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 33, 2, 130, 'compte rendu', NULL,
 5, true, 'Rendre compte de la journée entendue, en cinq phrases',
 'Langues vivantes (étrangères ou régionales)', '5e', 'academique',
 'L''enregistrement d''une minute écouté trois fois en début de séance.',
 E'# Reporting back — five sentences\n\n**Cinq phrases, troisième personne, en anglais.**\n\n---\n\n## La consigne\n\n> **Report what she does every day. Five sentences. Third person. No opinion.**\n\nCinq phrases, c''est peu, et c''est voulu : rendre compte oblige à choisir.\n\n## Ce que chaque phrase porte\n\n| Phrase | Contenu attendu |\n|---|---|\n| 1 | Qui parle, et de quoi |\n| 2 | Le début de la journée |\n| 3 | Le milieu — ce qui occupe le plus de temps |\n| 4 | Ce qui change selon les jours |\n| 5 | Ce qu''elle est en train de faire au moment où elle parle |\n\nLa cinquième phrase est celle qui force le présent progressif au milieu d''un texte au présent simple. Elle n''est pas décorative : sans elle, la moitié des comptes rendus n''emploie qu''un seul temps.\n\n## La difficulté réelle\n\nLe passage de la première à la troisième personne, et le **s** qui va avec.\n\n| Dans le document | Dans le compte rendu |\n|---|---|\n| I get up at seven | She get**s** up at seven |\n| I have breakfast with my brother | She ha**s** breakfast with her brother |\n| I''m sitting in my room | She i**s** sitting in her room |\n\nLe **s** de troisième personne ne s''installe jamais par les exercices écrits. Ici il est indispensable cinq fois de suite, et l''erreur s''entend.\n\n---\n\n# Corrigé\n\n> A girl describes her school day. She gets up at seven and has breakfast with her little brother. She spends most of the day at school, from eight to five, with a long lunch break. On Wednesdays she finishes earlier and goes to her dance class. Right now she is sitting in her bedroom, recording this.\n\n## Les erreurs les plus fréquentes\n\n1. **L''opinion qui s''invite** : *her day is very busy*. Hors consigne.\n2. **Le possessif oublié** : *she has breakfast with my brother*.\n3. **Le présent progressif étendu à tout** : *she is getting up at seven every day*.\n\nLa troisième est la plus instructive : elle montre que la règle n''est pas comprise, seulement recopiée.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Recopie des bribes sans les organiser |\n| Satisfaisante | Cinq phrases, chronologie, troisième personne tenue |\n| Très bonne | Emploie les deux temps à bon escient, possessifs transformés |',
 'termine', now(), now()),

-- ══ Séance 34 — Langues vivantes : jouer et rendre compte ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 34, 1, 137, 'jeux de rôle', NULL,
 3, false, 'Trois interlocuteurs, trois façons de raconter sa journée',
 'Langues vivantes (étrangères ou régionales)', '5e', 'operationnel',
 'Cartes de rôles : the journalist, the foreign penfriend, the curious little brother.',
 E'# Role play — three interviews\n\n**Cinq mots-clés, aucune phrase rédigée. Vingt-cinq minutes.**\n\n---\n\n## La contrainte\n\nTant qu''ils ont un texte, les élèves lisent — et lire n''est pas parler. Le professeur passe et retourne les feuilles où des phrases complètes apparaissent.\n\n> Exemple au tableau : *seven — bus — canteen — homework — football*\n\n## Les trois cartes\n\n| Carte | Ce que fait l''auditeur | Ce que cela force |\n|---|---|---|\n| **The journalist** | Prend des notes, demande des horaires | Situer, chiffrer, être exact |\n| **The foreign penfriend** | Ne connaît rien du collège français | Expliquer ce qui va de soi |\n| **The curious little brother** | Demande *why?* après chaque phrase | Justifier, développer |\n\nLa deuxième carte est la plus formatrice. Expliquer la cantine, la permanence ou le carnet de correspondance à quelqu''un qui ne les connaît pas oblige à sortir du vocabulaire appris tel quel — et fait apparaître qu''une traduction mot à mot ne suffit pas.\n\n## Les relances, au dos de la carte\n\n- *What time do you…?*\n- *Do you do that every day?*\n- *What are you doing right now?*\n- *Why?*\n\nLa troisième fait réapparaître le présent progressif au milieu du présent simple, sans qu''on ait à le demander.\n\n## Le déroulement\n\nDeux tours de trois minutes, puis échange des rôles. Minuteur projeté : la contrainte de temps vaut mieux qu''un rappel du professeur, qui casse la fiction.\n\nEntre les deux tours, trente secondes de silence : chacun note **un** mot qui lui a manqué. Ces mots sont ramassés et forment le lexique de la séance suivante — ce qui vaut mieux qu''une liste préparée d''avance.\n\n## Repères d''évaluation\n\n| Degré | Prise de parole en continu |\n|---|---|\n| Fragile | Phrases isolées, longs silences, retour au français |\n| Satisfaisante | Quarante secondes tenues, chronologie suivie |\n| Très bonne | Adapte son récit à l''interlocuteur qu''il a en face |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 34, 2, 131, 'mise en voix', NULL,
 3, false, 'Trois prises, une seule gardée',
 'Langues vivantes (étrangères ou régionales)', '5e', 'operationnel',
 'Les récits de journée travaillés en jeu de rôle, enregistrés sur tablette en fin de séance.',
 E'# Mise en voix — three takes, one kept\n\n**Trois prises de quarante secondes. L''élève choisit celle qu''il garde.**\n\n---\n\n## Pourquoi trois prises\n\nUne prise unique produit de la panique : c''est un contrôle déguisé. Trois prises produisent du travail — l''élève s''écoute, repère, recommence.\n\nEt surtout : **c''est lui qui choisit.** Le professeur n''écoute que la prise retenue.\n\n## Le protocole\n\n1. **Prise 1**, tout de suite après le jeu de rôle. Repère, pas performance.\n2. **Écoute au casque**, seul, avec la grille à trois cases.\n3. **Prise 2**, une seule chose corrigée.\n4. **Prise 3**, une autre chose corrigée.\n5. **Choix** de la prise gardée, et une phrase écrite : *pourquoi celle-là*.\n\n## La grille d''auto-écoute\n\nTrois cases. Plus, et l''élève ne corrige rien.\n\n| Ce que j''écoute | Ce que je vérifie |\n|---|---|\n| **Le débit** | Est-ce que je parle trop vite pour être compris ? |\n| **Les silences** | Ai-je un blanc de plus de cinq secondes ? |\n| **La fin** | Est-ce que ça se termine, ou est-ce que ça s''arrête ? |\n\nLa troisième case surprend : beaucoup de récits s''arrêtent net parce que le temps est écoulé. L''élève l''entend immédiatement en se réécoutant, là où une remarque du professeur glisserait.\n\n## Ce que l''enregistrement change\n\nS''entendre est désagréable, et il faut le dire d''emblée pour désamorcer les rires.\n\nMais c''est le seul moyen de sortir d''une illusion tenace : la plupart des élèves croient parler beaucoup plus vite et beaucoup moins bien qu''ils ne le font.\n\nEn pratique, la prise 3 est presque toujours meilleure que la 1 — non parce que l''anglais a progressé en dix minutes, mais parce que le débit s''est calmé.\n\n## Ce qui est évalué\n\nLa prise choisie et la phrase de justification. Un élève qui garde sa prise 2 en expliquant « la 3 était plus fluide mais j''ai oublié la fin » a compris ce qu''on lui demandait d''écouter.',
 'termine', now(), now()),

-- ══ Séance 35 — Arts plastiques : la profondeur ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 35, 1, 139, 'croquis', NULL,
 4, false, 'Quatre croquis, quatre moyens de creuser une feuille',
 'Arts plastiques', '5e', 'operationnel',
 'La nature morte en profondeur installée dans la salle, et l''interdiction de la perspective à points de fuite.',
 E'# Quatre croquis, quatre moyens\n\n**Sept minutes par croquis. La perspective à points de fuite est interdite.**\n\n---\n\n## L''interdit, et sa raison\n\nElle n''est pas mauvaise : elle est la seule que les élèves connaissent, et ils l''appliquent sans regarder. En la retirant, on oblige à chercher — et on découvre que les peintres ont creusé l''espace pendant des siècles sans elle.\n\n## Les quatre moyens\n\n| Croquis | Moyen | Ce qu''on fait |\n|---|---|---|\n| 1 | **Le recouvrement** | Un objet en cache partiellement un autre |\n| 2 | **La taille** | Ce qui est loin est plus petit |\n| 3 | **La hauteur sur la feuille** | Ce qui est loin est placé plus haut |\n| 4 | **Le contraste** | Ce qui est loin est plus pâle, moins net |\n\nUn seul moyen par croquis, c''est la règle. Les mélanger dès le début empêcherait de mesurer ce que chacun produit.\n\n## Ce qu''un croquis de sept minutes doit porter\n\n| À noter | À laisser tomber |\n|---|---|\n| Les masses et leur position relative | Les contours précis |\n| Le moyen imposé, employé franchement | Les textures |\n| Le cadre : où s''arrête l''image | La ressemblance |\n\n## Ce qu''on observe en comparant\n\n**Le recouvrement gagne**, alors qu''il est le plus pauvre techniquement : un objet qui en cache un autre est immédiatement lu comme étant devant, et aucune construction ne peut contredire cette lecture.\n\n**Le contraste est le plus discret** et le plus efficace en combinaison : c''est lui qui donne la sensation d''air entre les choses.\n\n**La taille seule devient vite mécanique** : elle produit un empilement plutôt qu''une profondeur.\n\n## La question qui clôt\n\n> **Lequel creuse le plus ?**\n\nEt non « lequel est le mieux dessiné ». Les deux questions donnent des réponses différentes, et c''est exactement ce qu''il faut faire éprouver en 5e.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Un seul croquis, ou la perspective employée malgré l''interdit |\n| Fragile | Quatre croquis sans différence visible |\n| Satisfaisante | Les quatre moyens identifiables |\n| Très bonne | Sait dire lequel fonctionne le mieux, et pourquoi |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 35, 2, 144, 'commentaire comparé', NULL,
 2, true, 'Deux images qui creusent l''espace autrement',
 'Arts plastiques', '5e', 'academique',
 'Une estampe japonaise et une photographie contemporaine au téléobjectif, projetées côte à côte.',
 E'# Commentaire comparé — deux espaces\n\n**Deux images, même question : où se place le spectateur, et comment le sait-il ?**\n\n---\n\n## Les deux images\n\n**A** — Une estampe japonaise du XIXe siècle : un village, une montagne, un premier plan de branches.\n**B** — Une photographie contemporaine prise au téléobjectif : une rue, des passants, un immeuble au fond.\n\n## La grille\n\n| | Image A | Image B |\n|---|---|---|\n| Comment le lointain est-il indiqué ? | | |\n| Y a-t-il des lignes qui fuient ? | | |\n| Les tailles diminuent-elles avec la distance ? | | |\n| Où est placé le spectateur ? | | |\n| Quelle sensation d''espace ? | | |\n\n---\n\n# Corrigé\n\n## Image A — l''estampe\n\n**Le lointain** est indiqué par la **hauteur sur la feuille** et par le **contraste** : la montagne est en haut, pâle, presque sans trait.\n\n**Aucune ligne ne fuit.** Les bords des maisons restent parallèles. Un élève habitué à la perspective y voit d''abord une « erreur ».\n\n**Les tailles diminuent peu.** Ce n''est pas une maladresse : c''est un système différent, cohérent avec lui-même.\n\n**Le spectateur** est placé nulle part en particulier — ou plutôt, il flotte. L''image ne lui assigne pas un point unique.\n\n## Image B — le téléobjectif\n\n**Le lointain** est presque supprimé. Le téléobjectif **écrase** l''espace : l''immeuble du fond paraît collé aux passants.\n\n**Les lignes fuient à peine**, elles aussi — mais pour la raison inverse : le champ est si étroit que la fuite ne se voit plus.\n\n**Les tailles diminuent très peu**, ce qui donne l''impression d''une foule compressée.\n\n**Le spectateur** est loin, et il le sait : on ne voit pas de cette manière à l''œil nu.\n\n## Ce que la comparaison fait comprendre\n\nAucune des deux, seule, ne le dirait :\n\n> **Deux images peuvent renoncer à la perspective pour des raisons opposées** — l''une parce qu''elle emploie un autre système, l''autre parce que l''optique l''a supprimée. Et les deux produisent un espace, différent mais lisible.\n\n## Le mot interdit\n\n**« Mieux ».** Comparer une estampe et une photographie en les classant reviendrait à noter un nageur et un cycliste sur la même grille.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Décrit les deux images sans les mettre en rapport |\n| Satisfaisante | Relie l''espace produit à un moyen identifié |\n| Très bonne | Ne hiérarchise pas, et explique pourquoi les deux systèmes tiennent |',
 'termine', now(), now()),

-- ══ Séance 36 — Arts plastiques : le lieu impossible ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 36, 1, 147, 'micro-fiction', NULL,
 NULL, false, 'La légende du lieu impossible, en trois phrases',
 'Arts plastiques', '5e', 'operationnel',
 'La production de chaque élève : un lieu qui ne peut pas exister, représenté avec les moyens de profondeur travaillés.',
 E'# Micro-fiction — la légende du lieu\n\n**Trois phrases maximum, au dos de la production. La légende ne décrit pas l''image.**\n\n---\n\n## La consigne\n\n> Écrivez la légende de ce lieu **comme si elle figurait dans un guide de voyage** — et sans décrire ce qu''on voit.\n\nLe ton du guide est ce qui fait tout : il énonce des faits pratiques sur un lieu, avec le plus grand sérieux. Appliqué à un lieu impossible, il produit exactement l''effet cherché.\n\n## L''exemple écrit devant les élèves\n\n> *On y accède seulement en repartant. Les habitants s''y sont faits. Prévoir des chaussures.*\n\nTrois phrases. Aucune description. Et la dernière, parfaitement banale, est celle qui fait croire aux deux premières.\n\n## Les trois leviers\n\n| Levier | Ce qu''il ajoute | Exemple |\n|---|---|---|\n| **Le détail pratique** | Le sérieux du guide | « Prévoir des chaussures » |\n| **L''habitude** | Le lieu existe depuis longtemps | « Les habitants s''y sont faits » |\n| **La restriction** | Une règle qui suppose des cas | « Interdit aux plus de douze ans » |\n\nLe premier levier est le plus efficace et le moins spontané : c''est le détail inutile qui rend crédible l''impossible.\n\n## Ce qui ne marche pas\n\n> *« C''est un escalier bizarre qui monte et qui descend en même temps, on dirait que ça tourne. »*\n\nLa phrase décrit, hésite, et commente. Le lecteur qui a l''image sous les yeux n''apprend rien.\n\nLa relance, toujours la même : **qu''est-ce que je sais de ce lieu que l''image ne montre pas ?**\n\n## Le rapport texte / image, nommé en fin d''activité\n\nTrois cas se dégagent des productions :\n\n1. **Le texte répète l''image** — l''ensemble n''ajoute rien.\n2. **Le texte contredit l''image** — intrigue, parfois trop.\n3. **Le texte décale l''image** — c''est ce qu''on cherche : le même dessin, vu autrement une fois le texte lu.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Décrit l''image malgré l''interdit |\n| Fragile | Trois phrases, mais aucun ton de guide |\n| Satisfaisante | Le ton est tenu, un détail pratique rend le lieu crédible |\n| Très bonne | L''image se regarde autrement une fois la légende lue |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 36, 2, 150, 'affiche', NULL,
 NULL, false, 'L''affiche touristique d''un lieu qui n''existe pas',
 'Arts plastiques', '5e', 'operationnel',
 'Le dessin du lieu impossible et sa légende, à mettre en page au format A3.',
 E'# L''affiche touristique\n\n**Format A3. Une image, un nom de lieu, une phrase. Rien d''autre.**\n\n---\n\n## Le cahier des charges\n\n1. **L''image** — le dessin du lieu, recadré si nécessaire.\n2. **Un nom de lieu** — trois mots maximum, dans le style d''un nom de station.\n3. **Une phrase** — une seule, qui ne décrit pas l''image.\n\nPas de date, pas de logo, pas de prix. Chaque élément ajouté affaiblit les trois autres.\n\n## Ce que le format d''affiche impose\n\nUne affiche touristique se lit **à distance et en passant**. Cela commande trois choses :\n\n| Contrainte | Conséquence |\n|---|---|\n| Lisible à trois mètres | Le nom du lieu en très grand, la phrase en dessous |\n| Vue en deux secondes | Une seule zone d''intérêt dans l''image |\n| Comprise sans explication | Le nom et l''image doivent se répondre |\n\n## Les choix plastiques à opérer\n\n- **La place du texte.** En bas par défaut ; sur l''image, il faut une zone calme pour l''accueillir — et cette zone se prévoit **avant** de dessiner, ce que personne ne fait la première fois.\n- **La taille du nom par rapport à la phrase.** Le nom plus gros, mais pas trois fois : un titre écrasant efface la phrase, qui est pourtant ce qui accroche.\n- **La marge.** Une image qui touche les bords sort du cadre ; une image cernée de blanc est un objet posé. Les deux se défendent : il faut choisir et savoir dire pourquoi.\n- **Une seule couleur d''accent.**\n\n## Exemples produits par des classes\n\n> **LES ESCALIERS BAS**\n> *Le village est plus haut que l''escalier qui y mène. Personne ne s''en étonne.*\n\n> **PLAGE 7**\n> *Au bout du couloir, troisième porte. Serviettes non fournies.*\n\nLa seconde fonctionne mieux, et il vaut la peine de demander pourquoi : la phrase pratique — « serviettes non fournies » — installe le lieu dans le réel bien plus sûrement qu''une phrase mystérieuse.\n\n## L''accrochage\n\nLes affiches sont accrochées au mur du fond, en agence de voyage. La classe circule **en silence** pendant dix minutes.\n\nChacun repart avec une consigne : retenir le lieu où il irait, et savoir dire ce qui, dans l''affiche, lui en a donné envie. La discussion a lieu la séance suivante, à froid.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Les trois éléments présents, la phrase décrit l''image |\n| Satisfaisante | Texte et image se complètent, lisible à trois mètres |\n| Très bonne | Un choix de mise en page assumé et explicable |',
 'termine', now(), now()),

-- ══ Séance 37 — Éducation musicale : la pulsation ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 37, 1, 144, 'commentaire comparé', NULL,
 3, true, 'Trois musiques, trois façons de tenir le temps',
 'Éducation musicale', '5e', 'academique',
 'Les trois extraits écoutés en séance : marche militaire, pièce pour piano en rubato, musique de danse électronique.',
 E'# Commentaire comparé — où est la pulsation ?\n\n**Le mot « j''aime » est interdit jusqu''à la fin du tableau.**\n\n---\n\n## L''interdit, et sa raison\n\nTant que le jugement est disponible, il remplace la description. Il est levé une fois le tableau rempli — et les élèves constatent alors que leurs préférences se disent beaucoup mieux.\n\n## Le tableau\n\n| | Marche | Piano en rubato | Danse électronique |\n|---|---|---|---|\n| **La pulsation est** | jouée, marquée | ressentie, non jouée | tenue par une machine |\n| **Qui la porte ?** | la grosse caisse | personne — l''auditeur la reconstruit | la boîte à rythmes |\n| **Peut-elle varier ?** | non, ou très peu | oui, elle respire | jamais |\n| **Tempo** | régulier, modéré | souple, il ralentit et repart | invariable |\n| **Effet produit** | on marche ensemble | on écoute une personne | on danse, on ne pense pas au temps |\n\n## Le cas difficile, et le plus instructif\n\n**Le piano en rubato.** Les élèves veulent conclure qu''il n''y a pas de pulsation. On leur demande de frapper doucement en écoutant : ils la trouvent, et ils constatent qu''elle s''étire puis se rattrape.\n\n**La formulation à obtenir** : la régularité n''est pas la rigidité. Une musique peut respirer et rester tenue.\n\n## Le vocabulaire fourni\n\nLes élèves n''ont pas les mots, et sans mots ils reviennent au jugement. La liste est affichée :\n\n**Tempo** — lent, modéré, rapide, régulier, souple, mécanique\n**Pulsation** — marquée, sous-entendue, absente\n**Nuances** — faible, forte, contrastée, constante\n**Texture** — une seule voix, voix et accompagnement, plusieurs couches\n\nUn mot employé correctement vaut mieux que trois employés au hasard, et on le dit.\n\n## La question qui conclut\n\n> **Laquelle de ces trois musiques serait la plus difficile à jouer à vingt-huit ?**\n\nLa deuxième, de loin. Un groupe peut suivre une pulsation marquée ou une machine ; suivre une respiration commune demande une écoute que la classe n''a pas encore.\n\nC''est exactement ce que la séance de chant travaille ensuite.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Ne s''exprime qu''en jugements |\n| Fragile | Deux termes justes, retour rapide au goût |\n| Satisfaisante | Remplit le tableau avec le vocabulaire adéquat |\n| Très bonne | Repère la pulsation là où elle n''est pas jouée |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 37, 2, 131, 'mise en voix', NULL,
 2, false, 'Chanter en tenant la pulsation : moitié qui frappe, moitié qui chante',
 'Éducation musicale', '5e', 'operationnel',
 'Le chant travaillé depuis le début de la séquence, et la pulsation installée en début de séance.',
 E'# Mise en voix — tenir à vingt-huit\n\n**Vingt minutes. La moitié frappe, l''autre chante. Puis on inverse.**\n\n---\n\n## Le problème, nommé devant la classe\n\nUn groupe de vingt-huit accélère. Toujours. Ce n''est pas un défaut d''attention : chacun anticipe légèrement sur le voisin, et vingt-huit anticipations font une accélération continue.\n\nLe dire change tout : les élèves cessent de chercher qui est fautif.\n\n## Le dispositif\n\n**La moitié frappe la pulsation, l''autre chante. Puis on inverse.**\n\nC''est le seul dispositif qui produise la prise de conscience : chacun entend ce qu''il fait subir aux autres quand il accélère. Un rappel du professeur n''y suffit jamais.\n\n## Les trois gestes qui stabilisent\n\n| Geste | Pourquoi ça marche |\n|---|---|\n| **Frapper moins fort** | On est obligé d''entendre les autres pour rester ensemble |\n| **Respirer ensemble avant d''attaquer** | Le départ décide du tempo : une respiration commune, un tempo commun |\n| **Regarder un point fixe, pas le voisin** | Se regarder produit des micro-ajustements qui s''additionnent |\n\nLe premier est le plus efficace, et le plus contre-intuitif pour des élèves qui croient qu''un groupe qui chante fort chante bien.\n\n## Les deux manières travaillées\n\n**Sur pulsation frappée, tempo modéré.** Difficulté : ne pas accélérer. On mesure — le professeur relève le tempo au début et à la fin du couplet.\n\n**Sans pulsation frappée.** Difficulté : la tenir quand même. C''est l''objectif de la séquence, et il n''est pas atteint en une séance.\n\n## Le point technique à ne pas laisser passer\n\nLa justesse se dégrade quand le tempo monte : les élèves montent aussi. On le signale sans dramatiser et on corrige par une reprise lente.\n\n**La vitesse ne se travaille jamais en accélérant** : on installe proprement, puis on accélère.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Fragile | Ne tient pas la pulsation quand elle n''est plus frappée |\n| Satisfaisante | Chante en restant dans le tempo du groupe |\n| Très bonne | S''ajuste au groupe sans qu''on le lui demande, et entend la dérive |',
 'termine', now(), now()),

-- ══ Séance 38 — Éducation musicale : décaler exprès ══
((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 38, 1, 143, 'montage numérique', NULL,
 NULL, true, 'Trente secondes où le décalage est voulu',
 'Éducation musicale', '5e', 'operationnel',
 'Une banque de percussions libres de droits et le thème de la séquence, sur les six postes équipés.',
 E'# Montage rythmique — décaler exprès\n\n**Trente secondes. Les choix s''écrivent avant d''ouvrir le logiciel.**\n\n---\n\n## La fiche, remplie en dix minutes\n\n> **Effet visé** : ……\n> **Le décalage que je vais fabriquer** : ……\n> **Ce que je ne dois pas faire** : ……\n\nUn binôme qui ouvre le séquenceur sans avoir rempli la fiche est renvoyé au papier. Sans cette règle, la séance devient une heure de manipulation agréable et sans intention.\n\n## Les trois décalages\n\n| Décalage | Comment | Effet ordinaire |\n|---|---|---|\n| **En avant** | Le son tombe juste avant le temps | Presse, tend, donne de l''urgence |\n| **En arrière** | Le son tombe juste après | Détend, alourdit — c''est le groove |\n| **Contretemps** | Le son tombe entre deux temps | Fait danser, déplace l''appui |\n\n## La distinction qui fait la séance\n\n**Entre « en arrière » et « mal joué », il n''y a qu''une différence : la constance.**\n\nUn retard régulier est un choix. Un retard variable est une erreur. C''est vérifiable à l''écran, sur la grille du séquenceur : les sons décalés doivent l''être **du même écart**.\n\nCette vérification visuelle est un des rares cas où le logiciel apprend quelque chose que l''oreille seule mettrait des mois à installer.\n\n---\n\n# Corrigé — trois montages attendus\n\n## Visé « urgent »\n\nCaisse claire posée trois centièmes avant le temps, sur toute la boucle. Tempo inchangé.\n\n**Pourquoi ça marche** : l''auditeur anticipe le temps suivant sans s''en rendre compte. Rien n''a accéléré, et pourtant ça presse.\n\n## Visé « lourd »\n\nGrosse caisse sur le temps, caisse claire cinq centièmes après. Un seul élément décalé, pas les deux.\n\n**Le piège** : décaler tout revient à ralentir. Ce qui produit le groove est l''écart **entre** deux éléments, pas le retard général.\n\n## Visé « dansant »\n\nUn son sur chaque contretemps, aucun sur les temps eux-mêmes.\n\n**Ce qu''on découvre** : la pulsation reste parfaitement audible alors que rien ne la joue. L''auditeur la reconstruit — exactement ce qui avait été observé dans le piano en rubato.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | A manipulé sans intention écrite |\n| Fragile | Fiche remplie, montage sans rapport avec elle |\n| Satisfaisante | Le décalage est constant et audible |\n| Très bonne | Distingue dans sa production le décalage voulu de l''erreur |',
 'termine', now(), now()),

((SELECT id FROM users WHERE email='demo.college4e@aschool.fr'), 38, 2, 142, 'playlist', NULL,
 6, false, 'Six morceaux, un fil rythmique, un ordre nécessaire',
 'Éducation musicale', '5e', 'operationnel',
 'La banque d''écoutes de l''année et les trois extraits de la séquence, accessibles depuis les postes.',
 E'# Playlist — six morceaux, un fil rythmique\n\n**Le fil est rythmique, pas thématique. Une phrase de justification par morceau.**\n\n---\n\n## La consigne\n\n> Six morceaux qui suivent **un même fil rythmique**, annoncé en tête. Pour chacun : *pourquoi celui-là, à cette place*.\n\nLe fil n''est pas un thème de paroles. C''est une manière de traiter le temps.\n\n## Les fils proposés\n\n| Fil | Ce qu''il fait chercher |\n|---|---|\n| Du plus régulier au plus libre | Entendre la souplesse, la classer |\n| Six façons d''installer une pulsation dans les dix premières secondes | Une écoute très fine sur une durée très courte |\n| Six musiques qui font danser, mais pas de la même façon | Distinguer ce qui déclenche le mouvement |\n| De la pulsation jouée à la pulsation seulement ressentie | Le fil le plus difficile, et le plus proche du cours |\n\nLe deuxième est celui qui produit les meilleures playlists : accessible à tous, et il oblige à réécouter vingt débuts de morceaux.\n\n## Ce qui distingue une playlist d''une liste\n\n**L''ordre.** Une liste se mélange sans dommage ; une playlist non.\n\n> **Le test** : si j''échange le morceau 2 et le morceau 5, est-ce que quelque chose se casse ?\n\nSi la réponse est non, le fil n''existe pas.\n\n**La justification.** Elle porte sur la musique, pas sur le souvenir personnel. « Je l''aime bien » ne se discute pas ; « je l''ai mis en troisième parce que c''est le premier où la pulsation n''est plus jouée » se discute.\n\n## Un exemple complet\n\n**Fil : de la pulsation jouée à la pulsation ressentie.**\n\n1. Une marche — la grosse caisse la joue, impossible de la manquer.\n2. Une chanson pop — la batterie la tient, mais elle s''efface au refrain.\n3. Un morceau où seule la basse la marque.\n4. Un morceau à contretemps — rien sur les temps, et on l''entend quand même.\n5. Une pièce pour piano en rubato — elle respire, elle s''étire.\n6. Un chant sans accompagnement — elle n''existe que dans la tête de celui qui écoute.\n\nSix étapes, une progression. Échanger deux morceaux casse la marche.\n\n## Repères d''évaluation\n\n| Degré | Ce qu''on observe |\n|---|---|\n| Insuffisante | Six morceaux sans fil, ou un fil thématique |\n| Fragile | Un fil annoncé, justifications par le goût |\n| Satisfaisante | Le fil tient sur les six, justifications musicales |\n| Très bonne | L''ordre est nécessaire, et l''élève sait dire ce qui se casserait |',
 'termine', now(), now());
